= Introduction

The history of higher Lie algebras is best understood as the meeting point of three long developments in modern mathematics: the passage from classical symmetry to infinitesimal symmetry, the replacement of strict algebraic identities by coherent homotopies, and the use of algebraic structures to encode deformation problems. In this essay, the expression _higher Lie algebra_ will be used in a deliberately broad sense. It includes differential graded Lie algebras, $L_∞$-algebras, Lie algebra objects in stable $∞$-categories, and the spectral Lie structures that arise in homotopy theory. These notions are not merely formal generalizations of ordinary Lie algebras. They were created because many geometric and topological objects possess Lie-type operations whose Jacobi identities, functoriality, or equivalences hold only up to homotopy. The purpose of the present survey is to explain how these structures emerged historically and why operads, Koszul duality, Goodwillie calculus, and deformation theory provide a natural common language for them. 

Classical Lie theory began in the nineteenth century with Sophus Lie's study of continuous transformation groups and their applications to differential equations and geometry. Lie's decisive idea was that a continuous group of symmetries could be studied through its infinitesimal generators. The commutator of infinitesimal transformations produced the bilinear bracket $[-,-] : frak(g) times.o frak(g) -> frak(g)$. 

#align(center)[#figure(image("assets/image.png", width: 50%), caption: [Sophus Lie])]

The later work of Wilhelm Killing and Élie Cartan developed the structure and classification theory of finite-dimensional Lie algebras, especially the semisimple ones. In this classical setting, the bracket is strictly antisymmetric and satisfies the Jacobi identity exactly. This strictness is appropriate for finite-dimensional symmetry groups, but it becomes too rigid in homological algebra and homotopy theory, where objects are considered only up to quasi-isomorphism or homotopy and where algebraic identities naturally come equipped with higher correction terms.

A first step toward higher Lie theory came from the growth of homological algebra in the middle of the twentieth century. The Chevalley--Eilenberg complex placed Lie algebras inside the language of chain complexes and cohomology. Once a grading and a differential are introduced, the natural strict object is a differential graded Lie algebra, or DGLA. A DGLA is a graded vector space
$ frak(g) = plus.o.big_i frak(g)^i $
equipped with a differential $d$ and a graded Lie bracket such that $d$ acts as a derivation. It is more precise to say that a DGLA is a Lie algebra object in the symmetric monoidal category of chain complexes than to say that it merely “lives in the derived category.” The ordinary derived category remembers morphisms only after passing to homotopy classes; the modern stable $∞$-category of chain complexes retains the higher mapping-space information that is essential for homotopy-coherent algebra. Thus DGLAs already contain the basic principle of higher algebra: classical operations are combined with homological degrees, differentials, and equivalences weaker than strict isomorphisms. A modern account of the role of differential graded Lie algebras in homotopy and deformation theory may be found in @LieDef.

The decisive topological appearance of DGLAs occurred in rational homotopy theory. Long before Quillen, the Whitehead product and the closely related Samelson product showed that homotopy groups carry Lie-like operations after an appropriate shift. Rationalization removes much of the torsion from homotopy groups and makes these operations more accessible to linear and homological algebra. In his paper Rational Homotopy Theory, Daniel Quillen constructed algebraic models for simply connected rational homotopy types using both differential graded Lie algebras and differential graded cocommutative coalgebras @Quillen1. One should formulate his result carefully: Quillen did not simply place a DGLA structure on the rational homotopy groups and declare that this graded Lie algebra completely determines the space. Rather, he associated to a space a differential graded Lie model whose homology recovers the rational homotopy groups, with the induced bracket corresponding to the Whitehead product. The differential and the additional chain-level information encode attaching and extension data that the graded homotopy groups alone cannot retain. Dennis Sullivan's later theory of minimal commutative differential graded algebras supplied a dual and highly effective model, and the Quillen and Sullivan approaches together established rational homotopy theory as one of the principal origins of modern homotopical algebra. 

Quillen's simultaneous use of Lie algebras and cocommutative coalgebras also foreshadowed a duality that was later placed in an operadic framework. Classical Koszul duality concerns resolutions of quadratic algebras, while in homotopical settings related dualities appear through bar and cobar constructions that pass between algebraic and coalgebraic objects. Quillen's rational models make the relation between Lie and commutative structures visible at the chain level, although it would be historically misleading to identify his construction with the complete modern theory of operadic Koszul duality. 

#figure(image("assets/image-1.png"), caption: [Daniel Quillen, except for his work mentioned above, he is also mostly know for his works in $K$-theory and homotopy theory])

In 1994, Victor Ginzburg and Mikhail Kapranov developed Koszul duality for operads and proved, with the appropriate suspensions and dualizations, that the Lie and commutative operads form a Koszul-dual pair @GK. This reformulation is central for higher Lie theory. A cofibrant, or homotopically correct, resolution of the strict Lie operad produces the $L_oo$-operad; consequently, an $L_oo$-algebra can be viewed as a Lie algebra in which the defining relations are resolved rather than imposed as literal equalities.

The terminology _strongly homotopy Lie algebra_, later abbreviated to $L_oo$-algebra, emerged from work in deformation theory, rational homotopy theory, and mathematical physics. Schlessinger and Stasheff encountered higher Lie operations in their study of deformations of rational homotopy types, while Lada and Stasheff gave an influential formulation motivated partly by closed string field theory. An $L_oo$-algebra carries multilinear brackets
$ ell_n : frak(g)^(times.o n) -> frak(g), forall n>=1 $
of prescribed degrees. Here $ell_1$ is the differential, $ell_2$ is the ordinary graded bracket, $ell_3$ measures the failure of the Jacobi identity to hold strictly, and the higher $ell_n$ provide successive coherences among these failures. A DGLA is the special case in which $ell_n = 0$ for every $n ≥ 3$. The importance of the general notion is that higher brackets are often unavoidable after transferring a DGLA structure to its homology or along a homotopy equivalence. The transferred object may no longer admit a natural strict DGLA structure, but it does admit an $L_oo$-structure that remembers the chain-level information lost in passing to homology.

A second major source of higher Lie algebras is deformation theory. Its basic equation is the Maurer--Cartan equation
$ d alpha + 1/2 [alpha,alpha] = 0 $
whose terminology comes from the structure equations of differential geometry. In the common cohomological grading convention, when a DGLA controls a deformation problem, degree-one elements represent infinitesimal changes, the Maurer--Cartan equation expresses the compatibility or integrability of those changes, and degree-zero elements generate gauge equivalences. The cohomology of the DGLA then records tangent directions, infinitesimal automorphisms, and obstructions. This pattern appeared in several classical settings: Kodaira--Spencer theory for deformations of complex structures, Gerstenhaber's deformation theory of associative algebras through Hochschild cochains, and the deformation theory of Lie algebra structures developed by Nijenhuis and Richardson. These examples form part of the historical background of the Lie methods surveyed in @LieDef.

During the 1980s, the principle often associated with Deligne---that a reasonable deformation problem in characteristic zero should be controlled by a DGLA up to quasi-isomorphism—became a unifying viewpoint. Goldman and Millson, Schlessinger and Stasheff, Hinich, and others supplied increasingly homotopy-invariant formulations of this principle. The use of quasi-isomorphism is essential: two different DGLAs can give equivalent deformation theories even when they are not isomorphic as strict algebraic objects. In derived algebraic geometry, this philosophy culminated in the independently developed correspondence of Lurie, which identifies formal moduli problems over a characteristic-zero field with suitable differential graded Lie algebras @SAG. Thus higher Lie theory is not merely one technique among many in deformation theory; it gives the infinitesimal algebraic form of the moduli problem itself.

Kontsevich's work illustrates the power of this viewpoint but should be described more precisely than by saying that DGLAs directly produced mirror symmetry. In deformation quantization, Kontsevich's formality theorem constructs an $L_oo$-quasi-isomorphism between polyvector fields, equipped with the Schouten bracket, and Hochschild cochains, equipped with the Gerstenhaber bracket. This converts Poisson structures, regarded as Maurer--Cartan elements on one side, into associative star products on the other. In mirror symmetry, $A_oo$-categories, deformation theory, and homological algebra play similarly fundamental roles, especially in Kontsevich's formulation of homological mirror symmetry. The historical lesson is that $A_oo$- and $L_oo$-structures became indispensable whenever one needed constructions that remain meaningful after passing to derived or homotopy-equivalent models.

To formulate these structures systematically, one needs the language of operads. An operad $P$ records, for every $n$, a space or chain complex $P(n)$ of $n$-ary operations, together with symmetric-group actions and substitution maps expressing how operations compose. This idea refines the older language of universal algebra: rather than listing operations and equations only at the level of sets, an operad can allow the operations themselves to vary in a topological space or chain complex. Trees provide the natural combinatorial picture, because grafting the output of one tree into an input of another represents substitution of operations. The associative, commutative, and Lie operads encode the familiar strict algebraic theories, while resolutions of these operads encode their homotopy-coherent analogues.

The topological history of operads is closely connected with the problem of recognizing loop spaces. In 1963, Stasheff introduced $A_n$- and $A_oo$-spaces and the associahedra in order to organize higher homotopies for associativity. A multiplication on an $H$-space may be associative up to a chosen homotopy, but a single associating homotopy is not sufficient. For four inputs, the different composites of associators must themselves be coherently homotopic; for five inputs, one requires homotopies among these homotopies; and the same problem continues in every arity. The associahedra encode precisely these compatibility conditions. In the early 1970s, Boardman--Vogt and J. Peter May developed the operadic theory of iterated loop spaces. The little $n$-cubes or little $n$-disks operad acts naturally on an $n$-fold loop space, and the recognition principle states, under appropriate connectedness and grouplikeness hypotheses, that spaces carrying the corresponding structure arise up to homotopy as $n$-fold loop spaces. A modern $∞$-categorical treatment of these operadic structures is given in @HA. 

#figure(image("assets/image-2.png"), caption: [J. Peter May, whose research founds many aspects of modern homotopy theory])

It is therefore better to regard an $E_n$-algebra not as an algebra that is “commutative through exactly $n$ levels,” but as an algebra whose operations are parametrized by configurations of little $n$-dimensional disks or cubes. An $E_1$-algebra is homotopy-coherently associative, while an $E_oo$-algebra is homotopy-coherently commutative. The intermediate $E_n$-structures contain geometric interchange operations unavailable to an arbitrary $A_oo$-algebra. In this way, the sequence
$ E_1, E_2, dots, E_oo $
interpolates between homotopy-coherent associativity and homotopy-coherent commutativity, although it should not be understood as a simple truncation of a fixed list of commutativity axioms. 

As homotopy theory developed, strict operads were themselves replaced by homotopy-coherent versions. Several models now coexist. Lurie's theory describes an $oo$-operad through a suitable functor to the category of pointed finite sets @HA, while Moerdijk and Weiss's dendroidal sets generalize simplicial sets by replacing linear simplices with trees @Dendroidal1. Both approaches express the same guiding principle: composition laws should include not only operations and equations but also all higher homotopies among possible composites. This framework is especially natural for chain complexes, spectra, and derived categories, where quasi-isomorphic models should determine equivalent algebraic structures. It also permits a clean definition of Lie algebra objects and $L_oo$-algebras inside symmetric monoidal $oo$-categories rather than only over ordinary vector spaces.

A further topological route to Lie structures comes from Goodwillie calculus. Beginning in the late twentieth century, Goodwillie developed a Taylor-tower approximation for homotopy functors, replacing ordinary derivatives by spectra with symmetric-group actions @Goodwillie1. Brenda Johnson identified the derivatives of the identity functor on pointed spaces @DerIdentity, and Michael Ching subsequently constructed their operad structure and related it to the Lie operad through bar--cobar and Koszul-duality methods @Ching1. In particular, the homology of the resulting spectral operad has the form of a shifted Lie operad. Later work further clarified the relation between topological $E_n$-operads and Koszul duality @Ching2. This construction reveals that higher Lie operations are intrinsic to unstable homotopy theory: they appear not only because one chooses an algebraic model for a space, but also as the derivatives of the identity functor on spaces themselves. The connection among Goodwillie derivatives, operadic Koszul duality, and spectral Lie algebras is one of the principal modern explanations for the ubiquity of Lie-type structures in homotopy theory. 

The organization of this essay follows these historical and conceptual connections. We first introduce symmetric sequences, operads, $oo$-categories, $oo$-operads, and the basic ideas of Goodwillie calculus. We then turn to Koszul duality, beginning with quadratic duality and proceeding to bar and cobar constructions. These tools lead to the definition of the $L_oo$-operad and to its alternative description through the Goodwillie derivatives of the identity. Finally, we study the role of DGLAs and $L_oo$-algebras in deformation theory through Maurer--Cartan equations and formal moduli problems. The central theme throughout is that higher Lie algebras provide a common algebraic language for infinitesimal symmetry, coherent homotopy, and deformation.