#import "import.typ": *
= Koszul Duality

As we mentioned in the introduction, Koszul duality first appeared in Quillen's paper on rational homotopy theory (@Quillen1). In this paper, the main theorem is the following: 

#thm(name: "Quillen")[
	The category $Ani_(QQ,>=2)$ of simply connected rational homotopy types of spaces is equivalent to both of the following: 
	-	The category of differential graded Lie algebras, given by sending a space to its rational homotopy groups, equipped with the Whitehead product as the Lie bracket. 
	-	The category of 2-reduced coalgebras, given by sending a space to its rational coefficient homology, with the coalgebra structure induced by the diagonal map $X inj X times X$. 
]

This theorem hints a certain duality relation between the Lie algebras and coalgebras, which is now known as Koszul duality. This duality was soon enhanced to the Koszul duality between the Lie operad and the commutative cooperad (a cooperad is simply an operad in the opposite category). In this chapter, we will introduce the Koszul duality of $oo$-operads, and define the $LL_oo$-operad by it. Moreover, we will give an alternative definition of the $LL_oo$-operad via Goodwillie calculus. 

We give a tiny remark here that the Koszul duality for operads only holds for reduced operads. 

== Quadratic duality 

We begin the chapter with the most ancient version of Koszul duality, introduced by Kapranov and Ginzburg in @GK. In short, some operads are generated by binary operations modulo trinary axioms. In this case, the duality of vector spaces gives the desired Koszul duality. In this section, we work over the category $Vect_k$. 

#def[
	Let $K$ be an assoiciative $k$-algebra. We define a $K$-collection to be a collection $E={E(n)}_(n>=2)$ of $k$-vector spaces with the following additional data and compatibilities: 
	+	A left $Sigma_n$-action on $E(n)$. 
	+	A $(K,K^(times.o n))$-bimodule structure on $E(n)$. 
	+	For $s in Sigma_n$, $s$ commutes with the left $K$-action and permutes the right $K^(times.o n)$-action. 
]

#const[
	For any $K$-collection ${E(n)}$ we may define a corresponding free operad $E$ defined via the following process. Firstly, we define for any tree $T$ the $k$-vector space 
	$ E(T)=times.o.big_(v in T)E(I(v)) $
	and finally define 
	$ E(n)=plus.o.big_T E(T) $
	where the $T$ in the above sum runs through trees with $n$ leaves. 

	This gives the definition of a symmetric sequence in $Vect_k$. Moreover, it is a monoid by definition. Thus, this gives the construction of an operad. 
]

#rem[
	This definition may seem contradictory to the previous theorem relating the operads as presheaves and operads as symmetric sequences. However, recall that the grafting morphisms are all equivalences, so we have for an operad $P$ the object $P(T)$ depend only on the number of leaves of $T$. 
]

#def[
	Let $P$ be an operad (regarded as a symmetric sequence). We define its ideal to be a sub-symmetric sequence $I(n) subset P(n)$ such that for $lambda in P(m)$ and $lambda_i in P(n_i)$ where $1<=i<=m$, if any one of $lambda$ and $lambda_i$ lie in $I$, then the composition $lambda(lambda_1,dots.c,lambda_m)$ lies in $I$. 
]

#coro[
	For $P$ an operad and $I subset P$ an ideal, the termwise quotient $P\/I(n)=P(n)\/I(n)$ admits an operad structure. 
]

#const[
	For a sub-symmetric sequence $R subset P$, we may define the ideal $(R)$ generated by $R$ given by the minimal ideal of $P$ containing $R$. One may also define it as the sub-symmetric sequence of $R$ generated by multiplying with elements in $I$, like the case of rings. 
]

#const[
	We now construct a special type of operads. 

	Let $K$ be a semisimple $k$-algebra. Let $E$ be a $(K,K^(times.o 2))$-bimodule with an $Sigma_2$-action $sigma$ satisfying the axioms that an object $E(2)$ in a $K$-collection would satisfy. Then, let ${E(n)}$ denote the $K$-collection with $E(2)=E$ and $E(n)=0$ for $n>2$. Then let $F(E)$ denote the free operad generated by this $K$-collection. Then, by definition we have $F(E)(3)=ind_(Sigma_2)^(Sigma_3)(E times.o_K E)$. Then, let $R subset F(E)(3)$ be a $Sigma_3$-stable $(K,K^(times.o 3))$-submodule. Finally, we construct $P(K,E,R)=P(E)\/(R)$. 
]

#def[
	We define a quadratic operad to be an operad arising from the above construction. 
]

#const[
	For a quadratic operad $P=P(K,E,R)$, we define its Koszul dual $K(P)$ to be the quadratic operad $P(K^op,E^or,R^perp)$, where $E^or$ is the dual module $Hom_K (E,K)$ regarded as a right $K$-module, so a left $K^op$-module. Finally, note that $F(E^or)(3)=F(E)(3)^or$, so the notation $R^perp$ simply denote the orthogonal complement in the dual space. Obviously for $K$ finite dimensional and $V$ finite dimensional, we have $K^2=id$. 
]

#exam[
	The operads $Assoc$, $Comm$, and $Lie$ are actually quadratic operads. Notice that if we take $K=k$, and fix a set of basis of $E$, say $E=plus.o.big k e_i$. We regard these $e_i$ as binary operations. So, when we take quotients of the set of the trinary operations $F(E)(3)\/R$, we regard this as identifying some compositions of binary operations. We give an example on giving the quadratic structures of $Assoc$, $Comm$, and $Lie$. 

	We first consider $Assoc$. We show $Assoc=P(k,k^2,R)$, where $k^2 ract Sigma_2$ by permutation. We may regard $k^2=Span(x_1x_2,x_2x_1)$. Under this, we have $F(k^2)(3)=k^12$, which is the space spanned by the operations $x_(s(1))(x_(s(2))x_(s(3)))$ and $(x_(s(1))x_(s(2)))x_(s(3))$ for $s in Sigma_3$. Then, we let $R subset k^12$ be spanned by the elements $x_i (x_j x_k)-(x_i x_j)x_k$. By definition, this is $Assoc$. 

	Then, we consider the operads $Comm$ and $Lie$. 
	
	Recall that $Sigma_3$ has 3 irreducible representations $1$, $bold("sgn")$, and $bold("std")$. We show that $Comm=P(k,k,bold("std"))$. Firstly, the $k$ in the second place is equipped with the trivial $Sigma_2$-action, so $F(k)(3)=1 plus.o bold("std")$. This is the $3$-dimensional $Sigma_3$-representation given by permutation, which we regard as the space generated by the three operations $(x_1 x_2)x_3$, $(x_2 x_3)x_1$, and $(x_3 x_1)x_2$. Then by the commutataivity axioms, we should obviously have the difference of any two zero, so $R=bold("std")$ the space of vectors $sum x_i=0$. 
	
	Then, we show that $Lie=P(k,bold("sgn"),bold("std"))$, where $bold("sgn")$ is the 1-dimensional $Sigma_2$-representation given by sign. We have $F(bold("sgn"))(3)=bold("sgn")plus.o bold("std")$, regarded as the space spanned by the operations $[[x_1,x_2],x_3], [[x_2,x_3],x_1],[[x_3,x_1],x_2]$. We notice that $bold("std")$ is the subspace generated by the Jacobi identities. 
]

#coro[
	We have $K(Assoc)=Assoc$, $K(Comm)=Lie$, $K(Lie)=Comm$. 
]
#proof[
	This is directly seen by the above presentation. 
]

Over the quadratic operads, there is a special type of algebras called quadratic algebras. 

#const[
	Let $P$ be an operad regarded as a symmetric sequence. Let $K=P(1)$, which is an algebra under the composition morphism, and $P(n)$ admit natural $K$-module structures by the composition morphisms. Note that there is a forgetful functor $Alg_P->Mod_K$ given by taking the underlying vector space, equipped with the natural $K$-module structure. 

	The above forgetful functor has a left adjoint, which is the free algebra functor $F_P:Mod_K->Alg_P$, given by 
	$ V mapsto plus.o.big_(n>=1)(P(n)times.o_(K^(times.o n))V^n)_(Sigma_n) $
]

#def[
	Let $A$ be a $P$-algebra. We define an ideal in $A$ to be a subspace $I subset A$ such that for any $mu in P(n)$, and $a_1,dots.c,a_(n-1) in A$, $i in I$, we have $mu(a_1,dots.c,a_(n-1),i) in I$, where this element comes from the $P$-algebra structure morphism 
	$ P(n) times.o A^(times.o n)->Hom(A^(times.o n), A)times.o A^(times.o n)->A $ 
	We have by definition $A\/I$ still a $P$-algebra. 
]

#const[
	We now construct a special type of algebras. Again, let $P$ be a quadratic operad $P(K,E,R)$. Take any $K$-module $V$, we have $F_P (V)$ the free $P$-algebra generated by $V$. Then, we consider the second piece of this free algebra, namely $(E times.o_(K^(times.o 2))V^(times.o 2))_(Sigma_2)$. This is a $K$-bimodule, where the right $K$-action is given by the diagonal action. Then, for $S subset(E times.o_(K^(times.o 2))V^(times.o 2))_(Sigma_2)$ be a $K$-sub-bimodule, we let $A(V,S)=F_P (V)\/(S)$, where $(S)$ again denote the ideal generated by $S$. 
]

#def[
	We define a quadratic algebra over a quadratic operad $P$ to be an algebra of the form $A(V,S)$. 
]

#exam[
	Again, when $K=k$, the quadratic algebras are instances of $P(K,E,R)$-algebras freely generated by some elements under some relations in $S$. For example, consider any finitely presented ring $A=k[x_1,dots.c,x_n]\/(f_1,dots.c,f_m)$, where each $f_i$ is of degree 2. Then, we let $P=Comm$, and take $V=Span(x_1,dots.c,x_n)$, so we have  
	$ F_P (V)=plus.o.big_(n>=0)V^(times.o n)_(Sigma_n)=plus.o.big_(n>=0)Sym^n V=Sym^*V=k[x_1,dots.c,x_n] $
	Then, take $S subset Sym^2 V$ to be generated by $f_i$. Thus we have $A(V,S)=k[x_1,dots.c,x_n]\/(f_1,dots.c,f_m)$. 
]

#const[
	For a quadratic operad $P$ and a quadratic algebra $A=A(V,S)$, we define its Koszul dual $K(A)$ to be the $K(P)$-algebra $A(V^or,S^perp)$. 

	Obviously, for finite dimensional $V$, we have $K^2=id$. 
]

== The bar and cobar construction

Now, we follow @Koszul and generalize the above definition to more general operads and algebras. In this section, we work with operads and algebras in general presentably symmetric monoidal stable $oo$-categories. For readers who are not familiar with this, one may simply think the above as the $oo$-categorical analogue of triangulated categories with limits and colimits. 

#figure(image("assets/image-7.png"), caption: [Gijs Heuts, who works on spectral Lie theory and its applications in chromatic homotopy theory])

#def[
	Let $cal(C)$ be any $oo$-category. We define $SSeq(cal(C))=Fun(Fin^tilde.eq,cal(C))$. 
]

#const[
	We now upgrade the composition product to an  monoidal structure on $SSeq(cal(C))$, for $cal(C)$ a presentably symmetric monoidal stable $oo$-category (recall previously it is only a monoidal structure in the $1$-categorical sense, which has no higher coherences required). 

	Firstly, recall that $cal(C)$ is the universal presentable $cal(C)$-linear $oo$-category, so any such $cal(D)$ has a unique exact presentable map $cal(C)->cal(D)$. Then, if we equip $SSeq(cal(C))$ with the Day convolution product, this category becomes the universal presentably symmetric monoidal $cal(C)$-linear $oo$-category over one object, that is, for any presentably symmetric monoidal $cal(C)$-linear $oo$-category $cal(D)$, we have an equivalence of categories 
	$ Fun^(times.o,L)(SSeq(cal(C)),cal(D))->^tilde.eq cal(D) $
	In particular, if we substitute $cal(D)=SSeq(cal(C))$, we have an equivalence 
	$ Fun^(times.o,L)(SSeq(cal(C)),SSeq(cal(C)))->^tilde.eq SSeq(cal(C)) $
	Then, the composition on LHS is naturally a monoidal structure. Passing this monoidal structure to RHS gives the monoidal structure of the composition product. In particular, the tensor unit is given by the unit symmetric sequence $I$ with $I(1)=1_(cal(C))$ and $0$ otherwise. 
]

#const[
	There is an inclusion functor $SSeq(cal(C))inj End(cal(C))$ given by sending a symmetric sequence $S$ to the functor 
	$ Sym_S:X mapsto plus.o.big_(n>=1)(S(n)times.o X^(times.o n))_(h Sigma_n) $
	The composition product is the unique monoidal structure on $SSeq(cal(C))$ such that this inclusion is monoidal. Namely, we have $Sym_(T compose S)=Sym_T compose Sym_S$. 
]

#def[
	For an operad $P$ in $cal(C)$, we define the category of $P$-algebras $Alg_P(cal(C))$ to be the category $Alg_(Sym_P)(cal(C))$, where since the inclusion $SSeq(cal(C))inj End(cal(C))$ is monoidal, we have for $P$ an operad $Sym_P$ a monad. 
]

#def[
	Recall we define $Alg(cal(C))$ to be the category of $EE_1$-algebras in $cal(C)$. We define $coAlg(cal(C))$ to be the category of $EE_1$-coalgebras in $cal(C)$, that is, $Alg(cal(C)^op)^op$. 

	Unwinding definitions, an $EE_1$-coalgebra in $cal(C)$ is equivalently an object $C$ equipped with a counit map $epsilon:C->1_(cal(C))$ and a homotopy associative comultiplication $Delta:C->C times.o C$. 
]

#def[
	Unwinding the definition of the dendroidal $oo$-operad, the category of $oo$-operads in $cal(C)$ is identified with the category of algebras in $SSeq(cal(C))$ with the composition product. Namely, we define 
	$ Op(cal(C)):=Alg(SSeq(cal(C))) $
]

For the complete notion of Koszul duality, we need the dual construction for operads. 

#def[
	We define a cooperad in $cal(C)$ to be an operad in $cal(C)^op$, in which $cal(C)^op$ is equipped with the opposite monoidal structure. Using the definition $Op(cal(C))=Alg(SSeq(cal(C)))$, we have 
	$ coOp(cal(C))=coAlg(SSeq(cal(C))) $
]

#def[
	We define an operad or cooperad to be reduced if its underlying symmetric sequence $S$ has $S([1])=1_(cal(C))$. 
]

Now we give some common operations on algebras. 

#const[
	Let $f:P_1->P_2$ be a morphism of operads. Then, it induces $f:Sym_(P_1)->Sym_(P_2)$ a morphism of monads. Recall that for a morphism of monads $f:T_1->T_2$, there is a pullback of algebras $f^*:Alg_(T_2)->Alg_(T_1)$ by sending the morphism $T_2 B->B$ to $T_1 B->T_2 B->B$, with the obvious algebra structure. This functor admits a left adjoint $f_! adj f^*$, where 
	$ f_!A=colim_(Delta^op)T_2 T_1^n A $
	the boundary maps are given by either $T_1^2->T_1$, $T_1 A->A$, or $T_2 T_1->T_2 T_2->T_2$, and the degeneracies the unit maps of monads. $f_!A$ is a $T_2$-algebra since it is a colimit of free-$T_2$-algebras, and is the left adjoint since 
	$ 
	&Hom_(T_2)(f_! A,B) \
	=&Hom_(T_2)(colim_(Delta^op)T_2T_1^n A,B) \
	=&lim_(Delta)Hom_(T_2)(T_2 T_1^n A,B) \
	=&lim_(Delta)Hom(T_1^n A,B) \
	=&lim_Delta Hom_(T_1)(T_1^(n+1)A,B) \
	=&Hom_(T_1)(colim_(Delta^op)T_1^(n+1)A,B) \
	=&Hom_(T_1)(A,B)
	$
	The above construction, applied to the case of operads, gives an adjunction
	$ f_!:Alg_(P_1)(cal(C))arrows.rl Alg_(P_2)(cal(C)):f^* $
	for any map $f:P_1->P_2$. 

	Dually, for a map of comonads $f:T_1->T_2$, there is a natural pushforward functor and its right adjoint given by totalization of the likewise diagram 
	$ f_*:coAlg_(T_1)(cal(C))arrows.rl coAlg_(T_2)(cal(C)):f^! $
]

Notice that all our operads constucted before admit an augmentation, for example, there is a natural map of symmetric sequences $Assoc->I$. It turns out that it is the augmented versions of these operads that we are caring about, which is shown in the following constructions. 

#const[
	Let $cal(C)$ be a presentably symmetric monoidal $oo$-category. Let $A in Alg(cal(C))$ be an associative algebra equipped with an augmentation $A->1_(cal(C))$. We define its bar construction to be $Bar(A)=1_(cal(C))times.o_A 1_(cal(C))$. Here, the relative tensor is the geometric realization of the simplicial object 
	$ 
		1_(cal(C))times.o_A 1_(cal(C))=colim_(Delta^op) (// https://q.uiver.app/#r=typst&q=WzAsNCxbMSwwLCJBIHRpbWVzLm8gQSJdLFsyLDAsIkEiXSxbMywwLCIxXyhjYWwoQykpIl0sWzAsMCwiZG90cy5jIl0sWzAsMV0sWzAsMSwiIiwyLHsib2Zmc2V0IjotNH1dLFswLDEsIiIsMSx7Im9mZnNldCI6NH1dLFsxLDIsIiIsMSx7Im9mZnNldCI6Mn1dLFsxLDIsIiIsMSx7Im9mZnNldCI6LTJ9XSxbMiwxXSxbMSwwLCIiLDEseyJvZmZzZXQiOjJ9XSxbMSwwLCIiLDEseyJvZmZzZXQiOi0yfV0sWzMsMCwiZG90cy5jIl1d
		#align(center, diagram({
			node((-1, 0), [$A times.o A$])
			node((0, 0), [$A$])
			node((1, 0), [$1_(cal(C))$])
			node((-2, 0), [$dots.c$])
			edge((-1, 0), (0, 0), "->")
			edge((-1, 0), (0, 0), shift: 0.2, "->")
			edge((-1, 0), (0, 0), shift: -0.2, "->")
			edge((0, 0), (1, 0), shift: -0.1, "->")
			edge((0, 0), (1, 0), shift: 0.1, "->")
			edge((1, 0), (0, 0), "->")
			edge((0, 0), (-1, 0), shift: -0.1, "->")
			edge((0, 0), (-1, 0), shift: 0.1, "->")
			edge((-2, 0), (-1, 0), [$dots.c$], label-side: left, "->")
		}))) 
	$
	
	This object has the natural structure of an augmented coalgebra. 

	The coalgebra structure is given by the following: 
	$ 1_(cal(C))times.o_A 1_(cal(C))->1_(cal(C))times.o_A A times.o_A 1_(cal(C))->1_(cal(C))times.o_A 1_(cal(C)) times.o_A 1_(cal(C))->(1_(cal(C))times.o_A 1_(cal(C)))times.o (1_(cal(C))times.o_A 1_(cal(C))) $
	where the middle map is induced by the augmentation of $A$. 

	The augmentation is the natural map 
	$ 1_(cal(C))=1_(cal(C))times.o 1_(cal(C))->1_(cal(C))times.o_A 1_(cal(C)) $

	Dually, for a augmented coalgebra $C$, we may consider the cobar construction $coBar(C)$ to be the totalization of the cosimplicial object 
	$
		coBar(C)=lim_(Delta)(// https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCIxXyhjYWwoQykpIl0sWzEsMCwiQyJdLFsyLDAsIkMgdGltZXMubyBDIl0sWzMsMCwiZG90cy5jIl0sWzAsMSwiIiwxLHsib2Zmc2V0IjotMn1dLFswLDEsIiIsMSx7Im9mZnNldCI6Mn1dLFsxLDBdLFsxLDJdLFsxLDIsIiIsMSx7Im9mZnNldCI6LTR9XSxbMSwyLCIiLDEseyJvZmZzZXQiOjR9XSxbMiwxLCIiLDEseyJvZmZzZXQiOi0yfV0sWzIsMSwiIiwxLHsib2Zmc2V0IjoyfV0sWzIsMywiZG90cy5jIl1d
		#align(center, diagram({
			node((-2, 0), [$1_(cal(C))$])
			node((-1, 0), [$C$])
			node((0, 0), [$C times.o C$])
			node((1, 0), [$dots.c$])
			edge((-2, 0), (-1, 0), shift: 0.1, 	"->")
			edge((-2, 0), (-1, 0), shift: -0.1, "->")
			edge((-1, 0), (-2, 0), "->")
			edge((-1, 0), (0, 0), "->")
			edge((-1, 0), (0, 0), shift: 0.2, "->")
			edge((-1, 0), (0, 0), shift: -0.2, "->")
			edge((0, 0), (-1, 0), shift: 0.1, "->")
			edge((0, 0), (-1, 0), shift: -0.1, "->")
			edge((0, 0), (1, 0), [$dots.c$], label-side: left, "->")
		})))
	$
	The two functors admit a mild generalization: for an algebra $A$, a left $A$-module $M$, and a right $A$-module $N$, we denote $Bar(M,A,N)$ by the geometric realization of the simplicial object as in $Bar(A)$, but tensoring with a $M$ on the right and $N$ on the left. Dually, for a coalgebra $C$, a left $C$-comodule $M$, and a right $C$-comodule $N$, $coBar(M,C,N)$ the likewise totalization. 

	We denote by $Bar_n(M,A,N)$ the $n$-th object in the above diagram, and $Bar_(<=n)(M,A,N)$ the colimit taken to the diagram restricted to the first $n$-elements. The identical definitions are made for $coBar$. 
	
	In the above sense, the augmentation of the (co)algebras may be regarded as giving a module structure on $1_(cal(C))$. 
]

#thm(name: [@HA, Theorem 5.2.2.17])[
	We have an equivalence of mapping spaces 
	$ Hom_(Alg(cal(C))_(\/1_(cal(C)))) (A,coBar(C))tilde.eq Hom_(coAlg(cal(C))_(1_(cal(C))\/))(Bar(A),C) $
	Moreover, both space admit the following moduli description: both spaces are the moduli space of lifting the pair $(A,C)$. 
]

In our setting, we take $cal(C)=SSeq(cal(C))$, so $Bar$ and $coBar$ induces an adjunction between augmented operads and augmented cooperads. In fact, in our setting, a better conclusion holds: $Bar$ and $coBar$ are actually equivalence of categories inverse to each other, after restricting to a nicer subcategory. 

#thm(name: [@Koszul, Theorem 3.4])[
	The above $Bar$-$coBar$ adjunction restricts to an equivalence on the categories of reduced operads and reduced cooperads. 
]
#proof[
	We prove for a reduced operad $P$ we have the counit map $P->coBar(Bar(P))$ is an equivalence. The counit $Bar(coBar(Q))->Q$ is likewise an equivalence. 

	Let $tau_n P$ denote the truncation of $P$ to stage $n$, which is the symmetric sequence with $tau_n P([k])=P([k])$ for $k<=n$, and $0$ otherwise. Then, we obviously have $tau_n P$ a right $P$-module. We claim that we have an equivalence 
	$ tau_n P->^tilde.eq coBar(Bar(tau_n P,P,I)),Bar(P),I) $
	Firstly note that this equivalence implies the result since $lim tau_n P=P$, and 
	$ lim(Bar(tau_n P,P,I))=Bar(lim tau_n P,P,I))=Bar(P,P,I)=I $
	Then, for this equivalence, we apply induction on $n$. For the base case $n=1$, since $P$ is reduced, we have $tau_1 P=I$, the unit symmetric sequence. So, the equivalence is simply 
	$ I=coBar(Bar(P),Bar(P),I)=coBar(Bar(I,P,I),Bar(P),I)=coBar(Bar(tau_1 P,P,I),Bar(P),I) $
	Then, for the induction step, consider the fiber sequence of morphisms 
	// https://q.uiver.app/#r=typst&q=WzAsNixbMCwwLCJQKG4pIl0sWzAsMSwidGF1X24gUCJdLFswLDIsInRhdV8obi0xKVAiXSxbMSwwLCJjb0JhcihCYXIoUChuKSxQLEkpLEJhcihQKSxJKSJdLFsxLDIsImNvQmFyKEJhcih0YXVfKG4tMSlQLFAsSSksQmFyKFApLEkpIl0sWzEsMSwiY29CYXIoQmFyKHRhdV9uIFAsUCxJKSxCYXIoUCksSSkiXSxbMCwxXSxbMSwyXSxbMyw1XSxbNSw0XSxbMCwzXSxbMSw1XSxbMiw0XV0=
	#align(center, diagram({
		node((-1, 0), [$P(n)$])
		node((-1, 1), [$tau_n P$])
		node((-1, 2), [$tau_(n-1)P$])
		node((0, 0), [$coBar(Bar(P(n),P,I),Bar(P),I)$])
		node((0, 2), [$coBar(Bar(tau_(n-1)P,P,I),Bar(P),I)$])
		node((0, 1), [$coBar(Bar(tau_n P,P,I),Bar(P),I)$])
		edge((-1, 0), (-1, 1), "->")
		edge((-1, 1), (-1, 2), "->")
		edge((0, 0), (0, 1), "->")
		edge((0, 1), (0, 2), "->")
		edge((-1, 0), (0, 0), "->")
		edge((-1, 1), (0, 1), "->")
		edge((-1, 2), (0, 2), "->")
	}))
	It suffices to prove the top row is an equivalence. By the presentability of the monoidal structure, we have $Bar(P(n),P,I)=P(n)compose Bar(P)$. Then, we have 
	$ coBar(P(n)compose Bar(P),Bar(P),I)=P(n) $
	by explicitly writing down the contracting homotopy in the computation of the limit, analogous to the proof of $coBar(C,C,I)=I$. 
]

The above construction gives the Koszul duality for operads, generalizing vastly the quadratic duality. However, the duality functor on algebras turns out to be much more subtle than the case of quadratic algebras. 

Recall in the above proof, we used the symmetric sequences $tau_n P$ to approximate $P$. We shall make more use of this construction in the following. 

#def[
	We define the category of $n$-truncated symmetric sequences to be 
	$ SSeq_(<=n)(cal(C))=Fun(Fin_(<=n)^tilde.eq,cal(C)) $
	Which is monoidal equipped with the truncated composition product. We define the category of $n$-truncated operads to be $Op_(<=n)(cal(C))=Alg(SSeq_(<=n)(cal(C)))$. Dually, we define $coOp_(<=n)(cal(C))=coAlg(SSeq_(<=n)(cal(C)))$. 
]

#const[
	Obviously, one has a restriction functor $rho_n:SSeq(cal(C))->SSeq_(<=n)(cal(C))$. Clearly we have the direct sum decomposition $SSeq(cal(C))=SSeq_(<=n)(cal(C))plus.o SSeq_(>n)(cal(C))$, so the extension by zero functor $zeta_n:SSeq_(<=n)(cal(C))->SSeq(cal(C))$ is both a left and a right adjoint. In particular, since $rho_n$ is a monoidal functor, $zeta_n$ is both a lax (as a right adjoint) and an op-lax monoidal functor (as a left adjoint). 

	These functors induces corresponding functors on operads. By the adjoint functor theorem, the functors $rho_n:Op(cal(C))->Op_(<=n)(cal(C))$ and $rho_n:coOp(cal(C))->coOp_(<=n)(cal(C))$ admits both left and right adjoints. We now explicitly construct them. Firstly, since lax monoidal functors preserves algebra objects and colax monoidal functors preserves coalgebra objects, we have 
	$ tau_n=zeta_n|_(Op_(<=n)(cal(C))):Op_(<=n)(cal(C))->Op(cal(C)) $
	right adjoint to $rho_n$, and 
	$ tau^n=zeta_n|_(coOp_(<=n)(cal(C))):coOp_(<=n)(cal(C))->coOp(cal(C)) $
	left adjoint to $rho_n$. As in the previous proof, they are the extension by zero functor of operads and cooperads. 

	On the other hand, the left adjoint of $rho_n:Op(cal(C))->Op_(<=n)(cal(C))$ is a bit more mysterious. This functor is denoted by $phi_n$, and is the free operad functor generated by operations with arity lesser or equal to $n$. The same applies to $rho_n adj phi^n$ for cooperads. 

	We abuse notations and abbreviate $tau_n rho_n X$ by $tau_n X$. The rest functors all admit similar abbreviations. 

	To sum up, we have $phi_n adj rho_n adj tau_n$ for operads and truncated operads, and $tau^n adj rho_n adj phi^n$ for cooperads. 
]

#let alg = math.op("alg")
#let coalg = math.op("coalg")

#def[
	Let $F in End(cal(C))$ be an endofunctor. We denote $alg_F (cal(C))$ the category of objects $c in cal(C)$ equipped with a map $F(c)->c$. 
]

#def[
	Let $S$ be a symmetric sequence in $cal(C)$. We define 
	$ D_n^S (X)=(S(n)times.o X^(times.o n))_(h Sigma_n),D^n_S (X)=(S(n)times.o X^(times.o n))^(h Sigma_n) $
]

#prop[
	We have a Cartesian square of $oo$-categories // https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJBbGdfKHBoaV9uIFApKGNhbChDKSkiXSxbMCwxLCJBbGdfKHBoaV8obi0xKSBQKShjYWwoQykpIl0sWzEsMCwiYWxnXyhEX25eUCkoY2FsKEMpKSJdLFsxLDEsImFsZ18oRF9uXihwaGlfKG4tMSlQKShjYWwoQykpIl0sWzAsMl0sWzIsM10sWzEsM10sWzAsMV1d
	#align(center, diagram({
		node((-1, 0), [$Alg_(phi_n P)(cal(C))$])
		node((-1, 1), [$Alg_(phi_(n-1) P)(cal(C))$])
		node((0, 0), [$alg_(D_n^P)(cal(C))$])
		node((0, 1), [$alg_(D_n^(phi_(n-1)P)) (cal(C))$])
		edge((-1, 0), (0, 0), "->")
		edge((0, 0), (0, 1), "->")
		edge((-1, 1), (0, 1), "->")
		edge((-1, 0), (-1, 1), "->")
	}))
	Moreover, taking the natural limit against the left maps gives $Alg_P (cal(C))=lim Alg_(phi_n P) (cal(C))$. 
]

#rem[
	We omit the proof of this proposition, but we state it here that this proposition is merely saying that an algebra of $P$ is a tower of algebras $A_n$ of $phi_n P$, such that the pullback of $A_n$ along the natural inclusion $phi_(n-1)P inj phi_n P$, coincides with $A_(n-1)$. Moreover, the data of an $phi_n P$-algebra $A_n$ restricting to a $phi_(n-1) P$-algebra $A_(n-1)$ can be identified with a map 
	$ (P(n)times.o X^(times.o n))_(h Sigma_n)->X $
	compatible with the map 
	$ (phi_(n-1)P(n)times.o X^(times.o n))_(h Sigma_n)->X $
	(recall $phi_(n-1)P(n)$ is the subobject of $P(n)$ regarded as the subobject "spanned" by the operations with lower arity). 
]

The coalgebras should be taken with more caution. Initially, we defined the coalgebras for $EE_1$ by the $EE_1$-algebras in the opposite categories. However, this definition does not work well generally, essentially because the opposite of presentable categories are not presentable, with the presentability of the monoidal structure especially broken. Hence, this definition does not work well for general cooperads. Here, we introduce the notion of divided power cooperads, which would appear on the dual side of the Koszul duality. 

#def[
	For a cooperad $Q$, we define $hat(Sym)_Q$ to be the functor 
	$ hat(Sym)_Q:X mapsto product_(n>=1)(Q(n)times.o X^(times.o n))_(h Sigma_n) $
]

However, the functor $hat(Sym)_((-))$ is only lax monoidal, so it sends operads to monads but not coalgebras to comonads, and the previous formalism would not apply to define a special class of coalgebras. 

The source of the problem is that the products does not generally commutes with limits. To resolve this, we must pass to the pro-category. 

#def[
	Let $cal(C)$ be an $oo$-category. We define the category $Pro(cal(C))$ to be the category of all cofiltered diagrams in $cal(C)$. There is a pair of adjoint functors $cal(C)arrows.rl Pro(cal(C))$ given by the following: There is a functor $cal(C)->Pro(cal(C))$ sending an object to the constant diagram with values in this object, and its right adjoint given by sending a diagram to its limit. 
]

#rem[
	Officially, $Pro(cal(C))$ is defined as the full subcategory of $Fun(cal(C),Ani)^op$ of the accessible preserving finite limits. The equivalence of definitions is given in Lurie's book @HTT. 
]

#let filt = math.upright("filt")

#thm(name: [@HTT])[
	The category $Pro(cal(C))$ admits the following universal property: for any category $cal(D)$ with small cofiltered limits, we have 
	$ Fun^filt (Pro(cal(C)),cal(D))->^tilde.eq Fun(cal(C),cal(D)) $
	where the natural functor is obtained by pulling back along taking constant diagrams. 
]

Hence, taking $cal(D)=Pro(cal(C))$, we have 

#coro[
	We have an equivalence of categories 
	$ End^filt (Pro(cal(C)))=Fun(cal(C),Pro(cal(C))) $
]

#def[
	For any functor $F:cal(C)->cal(C)$, we define $p F:Pro(cal(C))->Pro(cal(C))$ to be the functor obtained by first composing $F$ with the natural inclusion $cal(C)->Pro(cal(C))$, and then applying the above corollary to obtain $p F in End^filt (Pro(cal(C)))$. 

	Note this functor $p$ is symmetric monoidal, since the monoidal structure on both sides are given by composition. 
]

#const[
	Let $Sym^(<=n):SSeq(cal(C))->End(cal(C))$ denote the functor 
	$ A mapsto plus.o.big_(k<=n)D_k^A $
	Then, we obtain a lax monoidal functor $p Sym^(<=n):SSeq(cal(C))->End^filt (Pro(cal(C)))$. Finally, since the lax monoidalness of functors are preserved under limits, 
	$ hat(p Sym)=lim_n p Sym^(<=n) $
	is a lax monoidal functor. 

	Moreover, this functor is actually monoidal by category theory, essentially because $p Sym^(<=n)$ preserves cofiltered limits by definition. 
]

#let dp = math.upright("dp")

#def[
	By the above construction, for any operad $Q$, we have $hat(p Sym)_Q$ a comonad, so we may define the $hat(p Sym)_Q$-coalgebras in the category $Pro(cal(C))$. 

	We define the category of divided power coalgebras to be $cal(C) inter coAlg_(hat(p Sym)_Q)(Pro(cal(C)))$, or more rigorously the pullback 
	// https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJjb0FsZ19RXmRwIChjYWwoQykpIl0sWzAsMSwiY2FsKEMpIl0sWzEsMSwiUHJvKGNhbChDKSkiXSxbMSwwLCJjb0FsZ18oaGF0KHAgU3ltKV9RKSAoUHJvKGNhbChDKSkiXSxbMCwzXSxbMCwxXSxbMSwyXSxbMywyXV0=
	#align(center, diagram({
		node((-1, 0), [$coAlg_Q^dp (cal(C))$])
		node((-1, 1), [$cal(C)$])
		node((0, 1), [$Pro(cal(C))$])
		node((0, 0), [$coAlg_(hat(p Sym)_Q) (Pro(cal(C))$])
		edge((-1, 0), (0, 0), "->")
		edge((-1, 0), (-1, 1), "->")
		edge((-1, 1), (0, 1), "->")
		edge((0, 0), (0, 1), "->")
	}))
]

#prop[
	Dually, for a functor $F in End(cal(C))$, we define $coalg_F (cal(C))$ to be the objects in $cal(C)$ admitting a morphism $c -> F(c)$. Then, we have a pullback square 
	// https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJjb0FsZ15kcF8ocGhpXm4gUSkoY2FsKEMpKSJdLFswLDEsImNvQWxnXmRwXyhwaGlebiBRKShjYWwoQykpIl0sWzEsMCwiY29hbGdfKERfbl5RKShjYWwoQykpIl0sWzEsMSwiY29hbGdfKERfbl4ocGhpXihuLTEpIFEpKShjYWwoQykpIl0sWzAsMl0sWzAsMV0sWzEsM10sWzIsM11d
	#align(center, diagram({
		node((-1, 0), [$coAlg^dp_(phi^n Q)(cal(C))$])
		node((-1, 1), [$coAlg^dp_(phi^(n-1) Q)(cal(C))$])
		node((0, 0), [$coalg_(D_n^Q)(cal(C))$])
		node((0, 1), [$coalg_(D_n^(phi^(n-1) Q))(cal(C))$])
		edge((-1, 0), (0, 0), "->")
		edge((-1, 0), (-1, 1), "->")
		edge((-1, 1), (0, 1), "->")
		edge((0, 0), (0, 1), "->")
	}))
	Moreover, the natural map 
	$ coAlg_Q^dp (cal(C))=lim_n coAlg_Q^dp (cal(C)) $
]

This would be the coalgebras we will be considering. 

#let nil = math.upright("nil")

#thm(name: [@Koszul])[
	Let $Q$ be a cooperad. Then, the category of ind-conilpotent (we havn't defined this) divided power coalgebras is equivalent to the $Sym_Q$-coalgebras (recall $Sym_((-))$ is monoidal so in particular preserves coalgebra objects). Writing out, we have an equivalence 
	$ coAlg_(Q)^(dp,nil)(cal(C))tilde.eq coAlg_(Sym_Q)(cal(C)) $
]

So for the coalgebras, this actually takes us back to the construction in the beginning. 

We now construct the functors that would relate $P$-algebras to $Bar(P)$-coalgebras and vice versa. 

#let free = math.op("free")
#let forget = math.op("forget")
#let cot = math.op("cot")
#let triv = math.op("triv")

#const[
	Let $P$ be a reduced operad. Then, the projection $P->tau_1 P=I$ gives an augmentation of $P$. That is, we have morphisms $i:I->P$ and $t:P->I$ that composes to $id_I$. These morphisms give rise to the following adjunction 
	// https://q.uiver.app/#r=typst&q=WzAsMyxbMCwwLCJjYWwoQykiXSxbMiwwLCJjYWwoQykiXSxbMSwwLCJBbGdfUCAoY2FsKEMpKSJdLFswLDIsImlfISIsMCx7Im9mZnNldCI6LTJ9XSxbMiwwLCJpXioiLDAseyJvZmZzZXQiOi0yfV0sWzIsMSwidF8hIiwwLHsib2Zmc2V0IjotMn1dLFsxLDIsInReKiIsMCx7Im9mZnNldCI6LTJ9XV0=
	#align(center, diagram({
		node((-1, 0), [$cal(C)$])
		node((1, 0), [$cal(C)$])
		node((0, 0), [$Alg_P (cal(C))$])
		edge((-1, 0), (0, 0), [$i_!$], label-side: left, shift: 0.1, "->")
		edge((0, 0), (-1, 0), [$i^*$], label-side: left, shift: 0.1, "->")
		edge((0, 0), (1, 0), [$t_!$], label-side: left, shift: 0.1, "->")
		edge((1, 0), (0, 0), [$t^*$], label-side: left, shift: 0.1, "->")
	}))
	where since $t i=id_I$, the horizontal arrows compose to $id_(cal(C))$ (here in the diagram, we made the identification $Alg_I (cal(C))tilde.eq cal(C)$). Now, we rename the adjoint functors to provide more intuition, so we have the diagram 
	#align(center, diagram({
		node((-1, 0), [$cal(C)$])
		node((1, 0), [$cal(C)$])
		node((0, 0), [$Alg_P (cal(C))$])
		edge((-1, 0), (0, 0), [$free_P$], label-side: left, shift: 0.1, "->")
		edge((0, 0), (-1, 0), [$forget_P$], label-side: left, shift: 0.1, "->")
		edge((0, 0), (1, 0), [$cot_P$], label-side: left, shift: 0.1, "->")
		edge((1, 0), (0, 0), [$triv_P$], label-side: left, shift: 0.1, "->")
	}))
	where $free_P$ is the free $P$-algebra functor, $forget_P$ the functor forgetting the $P$-algebra structure, and $triv_P$ is the trivial $P$-algebra functor (by inducing the trivial multiplication on some object $c in C$, seen by $forget_P triv_P=id_(cal(C))$). 
]

#rem[
	The most mysterious functor is $cot_P$, the functor of taking cotangent fibers. To provide a first intuition, for $cal(C)=Mod_k$ the derived category over a base ring $k$, and $P$ the $EE_oo$-operad with $A$ a commutative $k$-algebra, we have $cot_(EE_oo) (A)=LL_(A\/k) times.o_A k$ almost the cotangent complex. 
]

#prop[
	The comonad $cot_P triv_P$ obtained by the adjunction can be identified with the comonad arising from the cooperad $Sym_(Bar(P))$. Thus, we have an equivalence of categories 
	$ coAlg_(cot_P triv_P)(cal(C))tilde.eq coAlg_(Bar(P))^(dp,nil)(cal(C)) $
]
#proof[
	Firstly, let $X$ be a $P$-algebra. By definition, $Sym_P=free_P$. Then, by explicitly constructing the contracting homotopy, we have $Bar(Sym_P,Sym_P,X)=X$ (here we slightly abuse notations and let this Bar construction be defined as changing the tensors in the previous Bar construction to composition and application of funcotrs). In this bar construction, we must identify $Sym_P$ with $free_P forget_P$, to keep the categories compatible. Then, applying $cot_P$ on both sides of the equation, we obtain 
	$ cot_P X=Bar(cot_P Sym_P,Sym_P,X)=Bar(id,forget_P free_P,forget_P X)=Bar(id,Sym_P,forget_P X) $
	Finally, substituting $triv_P X$ into the above, we have 
	$ cot_P triv_P X=Bar(id,Sym_P,X)=Sym_(Bar(P))(X) $
	where the last equivalence is given by commuting the two different colimits, one over $Delta^op$ and the other over $Fin^tilde.eq$. 
]

#let indec = math.op("indec")
#let prim = math.op("prim")

#const[
	By general formalism of comonads, the functor $cot_P:Alg_P(cal(C))->cal(C)$ factors through the category of $cot_P triv_P$-coalgebras, so we consider the diagram 
	// https://q.uiver.app/#r=typst&q=WzAsMyxbMCwxLCJBbGdfUChjYWwoQykpIl0sWzEsMSwiY2FsKEMpIl0sWzEsMCwiY29BbGdfKEJhcihQKSkoY2FsKEMpKSJdLFsyLDEsImZvcmdldF4oZHAsbmlsKV8oQmFyKFApKSJdLFswLDEsImNvdF9QIiwyXSxbMCwyLCJpbmRlY19QIl1d
	#align(center, diagram({
		node((0, 1), [$Alg_P (cal(C))$])
		node((1, 1), [$cal(C)$])
		node((1, 0), [$coAlg^(dp,nil)_(Bar(P))(cal(C))$])
		edge((1, 0), (1, 1), [$forget^(dp,nil)_(Bar(P))$], label-side: left, "->")
		edge((0, 1), (1, 1), [$cot_P$], label-side: right, "->")
		edge((0, 1), (1, 0), [$indec^(nil)_P$], label-side: left, "->")
	}))

	We may explicitly construct a right adjoint for $indec_P^nil$, given by 
	$ prim_(Bar(P))^nil (Y)=coBar(triv_P,Sym_(Bar(P)),forget^(dp,nil)_(Bar(P))Y) $
	which is the right adjoint by similar proofs as above. 
]

With some work on category theory, especially the formalism on filtered objects, we may lift the above adjunction to the following: 

#prop[
	There is an adjunction 
	$ indec_P:Alg_P (cal(C))arrows.rl coAlg_(Bar(P))^dp (cal(C)):prim_(Bar(P)) $
]

To formulate the final result, we will take one more technical assumption on our category of (co)algebras. This is called the nilcompleteness conditions, which basically ensures the algebras behaves nicely under the approximation of (co)operads. 

#def[
	Recall we have morphisms $P->tau_n P$ and $tau_n Q->Q$ for operads and cooperads respectively. These maps induces adjuntions on the category of $P$-algebras or $Q$-coalgebras. We let $id->t_n$ denote the unit of the adjunction for $P->tau_n P$ and $t^n->id$ the counit of the adjunction for $tau_n Q->Q$. 

	We define an $P$-algebra $X$ to be nilcomplete if $X->lim_n t_n X$ is an equivalence, and an $Q$-coalgebra $Y$ to be nilcomplete if $colim_n t^n Y->Y$ is an equivalence. Moreover, we define $X->lim_n t_n X$ to be the nilcompletion of $X$ and $colim t^n Y->Y$ the nilcompletion of $Y$. The two nilcompletion functors are idempotent, and projects the category of (co)algebras to the nilcomplete (co)algebras. 
]

#thm(name: [@Koszul])[
	Consider the adjunction 
	$ indec_P:Alg_P (cal(C))arrows.rl coAlg_(Bar(P))^dp (cal(C)):prim_(Bar(P)) $
	The unit of the adjunction is given by the nilcompletion of $P$-algebras, and the counit of the adjunction is given by the nilcompletion of divided power $Bar(P)$-coalgebras. 
]

#rem[
	However, the functors $indec_P^nil$ and $prim_(Bar(P))^nil$ does not restricts to an equivalence on the nilcomplete (co)algebras, which basically states that for some cooperad $Q$ there exists a non-nilpotent but nilcomplete coalgebra. 
]

We omit the proof of this theorem, since we lack the discussion of graded and filtered algebras used in the lifting of $indec_P^nil$ to $indec_P$ and its right adjoint. 

== The definition of Lie algebras 

#def[
	For an operad $P$, we define its operadic suspension $Sigma P$ to be the operad having the underlying symmetric sequence 
	$ Sigma P(n)=SS^(rho(n))times.o P(n) $
	where $SS^(rho(n))$ is the representation sphere of the $n-1$-dimensional standard $Sigma_n$-representation. The operadic structure is given by the operadic structure of $P(n)$ and the compatibilities between $SS^(rho(n))$. 
]

In particular, for $P$ an operad concentrated at degree 0, $Sigma P$ is an operad concentrated at degree $d-1$. 

#def[
	For an operad $P$ in $cal(C)$ which is term-wise a dualizable object, we define its dual $P^or$ to be the cooperad with 
	$ P^or (n)=Map(P(n),1_(cal(C))) $
	(here $Map$ is the internal $Hom$ of $cal(C)$) and the cooperad structure given by the natural map 
	$ Hom(c,e)times.o Hom(d,e)->^tilde.eq Hom(c times.o d,e) $
]

#thm(name: [@Ching1])[
	We have an equivalence of $oo$-cooperads in $Sp$ 
	$ Bar(Comm)=(Sigma Lie)^or $
	Here $Lie(n)=SS^(times.o(n-1)!)$ equipped with the same $Sigma_n$-action as the classical construction. 
]

#coro[
	By the previous section, we have $Bar(Lie)=(Sigma Comm)^or$. 
]

The computation of the homology of the Lie operad can thus be resolved by computing the Bar construction of the commutative operad, which has the easiest possible structure. However, there is another alternative construction of the shifted Lie algebra, given by the Goodwillie derivative of the identity. This gives another possible computation of the homology of the Lie operad. 

#thm(name: [@HA, Conjecture 6.3.0.7, actually proven in the book])[
	+	We have $partial_*id_(Ani)$ a symmetric sequence in spectra. Moreover, it is an operad. #h(1fr)
	+	The Goodwillie derivative functor is a monoidal functor 
		$ partial_*:Hom(Ani,Ani)->BiMod_(partial_*id)(SSeq(Sp)) $
]

#thm(name: [@Ching1])[
	The Goodwillie derivative of the identity is equivalent to the shifted Lie operad. Namely, we have an equivalence of operads $partial_* id_(Ani)->Sigma Lie$. 
]

The above isomorphism gives a calculation for the homology, or say, spectral structure of $partial_* id_(Ani)$. On the other hand, the calculation of $partial_* id_(Ani)$ is an older problem studied by Joyal and other homotopists. We have the theorem of Johnson

#thm(name: [@DerIdentity])[
	The homotopy type of $partial_n id_(Ani)$ is given by the sum of $(n-1)!$ copies of the $(1-n)$-sphere spectrum. 
]

Except for our most beloved operads, we present another important example of the computation of Koszul dual operads. 

#thm(name: [@Ching2])[
	We have 
	$ Bar(EE_n)=(Sigma^n EE_n)^or $
	generalizing the computation on $Bar(Assoc)$ since $Assoc=EE_1$. 
]

This fact will be used in the next chapter. 

The algebra of $Lie$ in other categories are of much importance, as we will also see in the next chapter. 

#def[
	A spectral Lie algebra is an algebra of $Lie$ in the category $Sp$. 
	
	Let $k$ be a characteristic 0 field. We define an $LL_oo$-algebra over $k$ to be an algebra of $Lie$ in $Mod_k$. 
]

#exam[
	A DGLA (differential graded Lie algebra) is a special type of $LL_oo$-algebra. This is the type of $LL_oo$-algebra most close to classical Lie algebras. Namely, a DGLA consists of the data of a chain complex $L$ equipped with a bracket $[-,-]:L^(times.o 2)->L$. This bracket, except for the graded skew-symmetric constraint and the Jacobi identity, must satisfy another axiom: the derivation $d$ should be a derivation of the bracket, namely 
	$ d[x_1,x_2]=[d x_1,x_2]-(-1)^(deg x_1 deg x_2)[d x_2,x_1] $
]

#rem[
	If we list out all the axioms of the DGLAs, we would arrive at the following three axioms on $L$ (here we temporarily regard $L$ just as a graded vector space, and $d$ is a degree $-1$ map on $L$): 
	+	$d(d(x_1))=0$ 
	+	$d[x_1,x_2]-([d x_1,x_2]-(-1)^(deg x_1 deg x_2)[d x_2,x_1])=0$
	+	$[[x_1,x_2],x_3]-(-1)^(deg x_2 deg x_3)[[x_1,x_3],x_2]+(-1)^(deg x_1(deg x_2+deg x_3))[[x_2,x_3],x_1]=0$
	Now, one may notice that a DGLA is simply a $LL_oo$-algebra with higher homotopy coherences identically 0. If we would restore these higher coherences (not setting them 0), we will obtain the classical definition of an $LL_oo$-algebra. 
]

#def[
	Let $p,q>=0$. We define a $(p,q)$-shuffle to be a permutation $sigma in Sigma_(p+q)$ such that 
	$ sigma(1)<sigma(2)<dots.c<sigma(p), #[and] sigma(p+1)<sigma(p+2)<dots.c<sigma(p+q) $
	We define the set of $(p,q)$-shuffles to be $S(p,q)subset Sigma_(p+q)$. 
]

#def[
	Let $V$ be a graded vector space. We define the Koszul sign conventions as the following: 
	+	We let $s:V times.o V->V times.o V$ given by the usual swap map $u times.o v mapsto (-1)^(deg u deg v)v times.o u$. #h(1fr)
	+	For any $sigma in Sigma_n$, the swap map above induces an $n$-ary swap map 
		$ s_sigma:V^(times.o n)->V^(times.o n) $
		by decomposing $sigma$ in to products of 2-cycles. 
	+	Let $sigma in Sigma_n$. We define $epsilon(sigma,v_1,dots.c,v_n)=plus.minus 1$ to be the value such that the identity 
		$ s_sigma (v_1times.o dots.c times.o v_n)=epsilon(sigma,v_1,dots.c,v_n)v_(sigma(1))times.o dots.c times.o v_(sigma(n)) $
		holds. 
	+	Finally, we define $chi(sigma,v_1,dots.c,v_n)=(-1)^(sigma)epsilon(sigma,v_1,dots.c,v_n)$, where $(-1)^(sigma)$ denotes the number of inverses in $sigma$. 
]

#const[
	Now we may formulate the equivalent definition for the $LL_oo$-algebras. Let $k$ be a characteristic 0 field and $L$ be a graded $k$-vector space. We define an $LL_oo$-algebra structure on $L$ to be a set of graded skew-symmetric operations 
	$ ell_n:L^(and n)->L[2-n], n>0 $
	such that for every $n>0$ and any set of homogeneous vectors $x_1,dots.c,x_n in V$, we have 
	$ sum_(k=1)^n (-1)^(n-k) sum_(sigma in S(n,k)) chi(sigma) ell_(n-k+1)(ell_k (x_(sigma(1)), dots.c,x_(sigma(k))), x_(sigma(k+1)),dots.c,x_(sigma(n)))=0 $
]

#rem[
	One can not see the $n$-ary brackets $ell_n$ from the definition of the Lie operad, but the intuition is given as follows. 
	
	Firstly, $ell_1$ is an operation of degree 1, which serves as the differential structure for the graded $k$-vector space $L$. This is because we have for $n=1$, the identity reads $ell_1^2=0$. 
	
	Then, $ell_2$ is a skew-symmetric binary operation of degree 0. This is our Lie bracket, which must be compatible with the differential structure, giving the equation for $n=2$. 

	Now we arrive at the first great difference from $LL_oo$-algebras and Lie algebras (or say, DGLAs), which is the trinary operation $ell_3$ of degree $-1$. This operation comes from the following construction. Recall that we require the Lie bracket to have the Jacobi identity, that is, 
	$ [[x_1,x_2],x_3]-(-1)^(deg x_2 deg x_3)[[x_1,x_3],x_2]+(-1)^(deg x_1(deg x_2+deg x_3))[[x_2,x_3],x_1]=0:L^(and 3)->L $
	Now in the $LL_oo$-setting, we can not directly speak of a morphism equal to 0 since we are working in the derived category. Instead, we can only speak of a morphism homotopic to 0. Recall that to homotope a morphism $f$ to 0 amounts to giving a morphism $g$ of degree $-1$ such that $d g=f$. Here, the trinary bracket serves as the "Jacobiator", which is the map witnissing the Jacobi identity. However, since we require the trinary bracket also to be compatible with the differential structure, it is not directly the trinary bracket serving as the Jacobiator, but instead we have  
	$ 
	&[[x_1,x_2],x_3]-(-1)^(deg x_2 deg x_3)[[x_1,x_3],x_2]+(-1)^(deg x_1(deg x_2+deg x_3))[[x_2,x_3],x_1]\ 
	=&d ell_3(x_1,x_2,x_3)+ell_3(d x_1,x_2,x_3)+dots.c
	$
	which explains the identity for $n=3$. 

	Finally, for higher $n$, the operations of arities up to $n-1$ conbines together to give an $(n-1)$-ary Jacobi identity for $n$-elements, and this serves for the $n$-Jacobiator. 
]

We now present our first example of Koszul duality. 

#thm(name: [@DiffCoh, Proposition 1.2.152])[
	Let $frak(g)$ be an $NN$-graded vector space that is degreewise finite dimensional. Write $frak(g)^*$ for the degreewise dual, also $NN$-graded. Then dg-algebra structures on the Grassmann algebra $Sym^* frak(g)[1]$ are in canonical bijection with $LL_oo$-algebra structures on $frak(g)$. 
]

In fact, since we have the Koszul duality for Lie algebras and cocommutative coalgebras, since the structure of the operad $Comm$ is much more simpler than $Lie$, people sometimes regard morphisms of $LL_oo$-algebras as the dual morphisms in coalgebras, which avoids certain technical details in $LL_oo$-algebra theory. 

In the next chapter, we will focus on the usage of $LL_oo$-algebras in geometry, and finally see some examples of $LL_oo$-algebras. 