#import "import.typ": *

= The Bezrukavnikov-Finkelberg equivalence

We attempt to give a rather complete sketch of the infamous (at least among my friends) article of Bezrukavnikov-Finkelberg. The main theorem of the article is the following: 

#thm[
	$D^check(G)_perf (U_(planck)^square)tilde.eq D_(L^+G times.r GG_m)(Gr)$, and $D^check(G)_perf (Sym^square (check(frak(g))))tilde.eq D_(L^+G)(Gr)$. 
]

where the algebras $U_(planck)^square$ and $Sym^square (check(frak(g)))$ are to be defined later. The strategy of the proof is given by the following steps. 

+	Construct functors $kappa_planck:cal(H C)_planck->QCoh^(GG_m)(M_((check(frak(t))\/W)^2)Delta)$ and $kappa:Coh^(check(G)times GG_m)(check(frak(g))^*)->Coh^(GG_m)(T(check(frak(t))^*\/W))$. The functors are fully faithful on the subcategory of free objects, namely $cal(H C)_planck^fr$ and $Coh_fr^(check(G)times GG_M)(check(frak(g))^*)$. 
+	Extend the Satake functor $S:Rep(check(G))->Perv_(L^+G times.r GG_m)(Gr)$ to fully faithful functors 
	$ S_planck:cal(H C)_planck^fr->D_(L^+G times.r GG_m)(Gr), #[and] S_(q c):Coh_fr^(check(G)times GG_m)(check(frak(g))^*)->D_(L^+G)(Gr) $
	These functors are constructed via the fully faithful cohomology functors 
	$ H^*_(L^+G times.r GG_m):Perv_(L^+G times.r GG_m)(Gr)->Coh^(GG_m)(M_((check(t)\/w)^2)Delta),H^*_(L^+G):Perv_(L^+G)(Gr)->Coh^(GG_m)(T(check(frak(t))^*\/W)) $
	and by analysing the images, we have $kappa_planck|_(cal(H C)_planck^fr)$ and $kappa|_(Coh^(check(G)times GG_m)_fr (check(frak(g))^*))$ factors through the cohomology functors by $S_planck$ and $S_(q c)$, i.e., $kappa_planck=H^*_(L^+G times.r GG_m)compose S_planck$ and $kappa=H^*_(L^+G)compose S_(q c)$. 
+	Extend $S_planck$ and $S_(q c)$ to our final equivalences via the fully faithful inclusions $cal(H C)_planck^fr subset D^check(G)_perf (U_(planck)^square)$ and $Coh_fr^(check(G)times GG_m)(check(frak(g))^*)subset D^check(G)_perf (Sym^square (check(frak(g))))$. 

We will expand the three steps one by one. 

== Step 1

=== Computations of equivariant cohomology 

Before we start, we must compute the equivariant cohomologies of points. 

#def[
	Let $X$ be a scheme and $Z subset X$ be a closed subscheme classified by the quasi-coherent sheaf of ideals $cal(I)$. We construct the deformation to the normal cone as following. Firstly, take $AA^1=Spec k[planck]$. Then, consider the following extended Rees $cal(O)_X$-algebra $cal(R)$ given by the sheaf of subalgebras in $cal(O)_X [planck^plus.minus]$ generated by $planck$ and $f planck^(-1)$ where $f in cal(I)$. We define the deformation to the normal cone $M_X Z=Spec_X cal(R)$. 
]

#def[
	For groups $G$ with $H^*_G (pt)$ is an integral domain, we define the localized equivariant cohomology $H^*_G (X)_loc=H^*_G (X)times.o_(H^*_G (pt))Frac(H^*_G (pt))$. 
]

#thm[
	There is an equivalence 
	$ alpha:cal(O)(N_((check(frak(t))\/W)^2)Delta)tilde.eq plus.o.big_(pi_1(G))H^*_(L^+G times.r GG_m)(Gr) $ 
	Here $Delta$ denote the diagonal embedding. 
]
#proof[
	We first treat the case where $G$ is simply connected. 

	Firstly, notice $H^*_(L^+G times.r GG_m)(Gr)=H^*_(GG_m)(L^+G\\L G\/L^+G)$ admit a bimodule structure of $H^*_(L^+G)(pt)$. Since we have the homotopy equivalence $L^+G tilde.eq G$ by contractibility of $k[[t]]$, we have $H^*_(L^+G)(pt)=H^*_G (pt)=cal(O)(frak(t)\/W)$ by Chern-Weil theory. Thus, we have $H^*_(L^+G times.r GG_m)(Gr)$ is a $H^*_(L^+G)(pt) times.o H^*_(L^+G)(pt) times.o H^*_(GG_m)(pt)=cal(O)((frak(t)\/W)^2 times AA^1)$. This gives a structure map 
	$ alpha:cal(O)((frak(t)\/W)^2 times AA^1)->H^*_(L^+G times.r GG_m)(Gr) $
	Then we show it extends to the extended Rees algebra $cal(R)$, that is, we show that for $f in cal(I)_Delta$, we have $alpha(f)$ contains a factor of $alpha(planck)$ where we regard $H^*_(GG_m)(pt)=k[planck]$, i.e., the two maps $H_(L^+G)^*(pt)->H^*_(L^+G times.r GG_m)(Gr)\/planck$ coincide. This is because $H^*_(L^+G times.r GG_m)(Gr)\/planck=H^*(L^+G\\L G\/L^+G)$. Thus we obtain a map 
	$ alpha:cal(O)(M_((frak(t)\/W)^2)Delta)->H^*_(L^+G times.r GG_m)(Gr) $ 
	We then show it is an equivalence. For injectivity, note $H^*_(L^+G times.r GG_m)(pt)=cal(O)(frak(t)\/W times AA^1)$. Notice by definition that $cal(O)(M_((frak(t)\/W)^2)Delta)$ is an integral domain, so it suffices to prove the localized morphism 
	$ alpha_loc:cal(O)(M_((frak(t)\/W)^2)Delta)times.o_(cal(O)(frak(t)\/W times AA^1))Frac(cal(O)(frak(t) times AA^1))->H^*_(L^+G times.r GG_m)(Gr)times.o_(cal(O)(frak(t)\/W times AA^1))Frac(cal(O)(frak(t) times AA^1)) $
	is an injection. This is because the right hand side can be identified with the localized equivariant cohomology $H^*_(T times GG_m) (Gr)_loc$. 
]

=== The involved categories 

#def[
	Let $U=U(check(frak(g)))$, and let $U_planck$ denote the graded enveloping algebra, explicitly, the graded $k[planck]$-algebra generated by $check(frak(g))$ under the relations $x y-y x=planck[x,y]$. Equivalently, $U_planck$ is the Rees algebra of the filtered algebra $U$. 
	
	These enveloping algebras are equipped with the structure of $check(G)$-representations via the adjoint action $check(G) lact check(frak(g))$. 
]

#def[
	We define the category of $planck$-Harish-Chandra bimodules $tilde(cal(H C))_planck$ to be the category with the following objects with the requirements: 
	+	An object $M$ is a graded $U_planck times.o_(k[planck])U_planck$-module equipped with the structure of a $check(G)$-representation $rho:check(G) lact M$, such that:
	+	the action map $U_planck times.o_(k[planck])U_planck times.o M->M$ is $check(G)$-equivariant, and, 
	+	for $x in frak(check(g))$, the action of $1 times.o x+x times.o 1$ on $M$ is $planck dot d rho(x)$. 
	The intuition to this definition is some sort of Harish-Chandra modules of Harish-Chandra pairs. 

	We define $cal(H C)_planck subset tilde(cal(H C))_planck$ to be the full subcategory spanned by the modules $M$ such that $M$ is finitely generated as $U_planck times.o 1$-modules. 
]

= Koszul duality

== A first glance: Koszul duality for finite type groups

=== Highest weight categories 

In this section, we introduce a special type of Abelian categories which behaves like the category of perverse sheaves over a suitable stratified space or the BGG category $cal(O)$. The history of the developments of such categories is complicated, resulting in various definitions of such categories (some of which are simple generalizations of others). We will begin with the first definition. 

#def[
	Let $cal(A)$ be an Abelian category over some field $k$. We say $cal(A)$ is highest weight in the sense of @Highestwt1 if the following conditions are met.
	+	$cal(A)$ satisfies the condition $"AB5"$ and is locally Artinian. That is, every object is generated by finite-length objects by filtered colimits. In particular, every object admit a (possibly infinite) composition series. 
	+	There is an interval finite poset $Lambda$ (that is, the intervals $[mu,nu]={lambda|mu<=lambda<=nu}subset Lambda$ are finite) with the set of all non-isomorphic simple objects $IC_lambda in cal(A)$ indexed by $Lambda$. 
	+	There is a collection of costandard objects $nabla_lambda$ indexed by $Lambda$. 
	+	These objects contain $IC_lambda subset nabla_lambda$ as a subobject, and the quotient $nabla_lambda\/IC_lambda$ contains only $IC_mu$ with $mu>lambda$ in the composition series. Moreover, $[nabla_mu:IC_nu]$ and $dim_k Hom(nabla_mu,nabla_nu)$ are finite. 
	+	$IC_lambda$ admit an injective envelope $I_lambda$ in $cal(A)$. This injective $I_lambda$ admit another complete filtration 
		$ 0=F_0 subset F_1 subset dots.c subset I_lambda $
		such that $F_1=nabla_lambda$, and $F_i\/F_(i-1)=nabla_mu$ where $mu>lambda$ for $i>1$. Moreover, each $nabla_mu$ appears only finitely many times. 
] <Def_Highest_wt_cat_def_1>

This is not the main focus of this section, so we only present the main theorem of the article. 

#thm(name: [Theorem 3.9, @Highestwt1])[
	Finite length highest weight categories with finitely many simple objects are always of the form as a right module category $Mod_A^(f.g.)$ for some right quasi-hereditary algebra $A$. 
] <Thm_CPS_highest_wt_heri_mod>

This is mainly used in the paper @KoszulFin. In their paper, they only focused on finite length categories with finitely many simple objects, namely, the category of perverse sheaves with respect to a nice enough finite stratification. Their definitions went as follows. 

#def[
	Let $cal(A)$ be an Abelian category over some field $k$. We say $cal(A)$ is highest weight in the sense of @KoszulFin if the following conditions hold. 
	+	$cal(A)$ is of finite length. 
	+	$cal(A)$ has simple objects indexed by a finite poset $Lambda$, denoted by $IC_lambda$. Moreover, $End(IC_lambda)=k$. The poset $Lambda$ will be referred to as the weight poset. 
	+	There are standard and costandard objects $Delta_lambda$ and $nabla_lambda$ indexed by $Lambda$, equipped with structure morphisms $Delta_lambda->IC_lambda$ and $IC_lambda->nabla_lambda$. 
	+	Let $Lambda' subset Lambda$ be any subposet closed under taking smaller elements. We define $cal(A)_(Lambda')$ to be the subcategory of $cal(A)$ spanned by objects with simple components $IC_(lambda')$ for $lambda' in Lambda'$. Then, for any maximal element $m in Lambda'$, we have $Delta_m->IC_m$ a projective cover and $IC_m->nabla_m$ an injective hull in $cal(A)_(Lambda')$. 
	+	$ker(Delta_lambda->IC_lambda)$ and $coker(IC_lambda->nabla_lambda)$ lie in $cal(A)_(<lambda)$. 
	+	$Ext^2(Delta_mu, nabla_nu)=0$. 
] <Def_Highest_wt_cat_def_2>

#lem[
	We have the following orthogonality and Ext vanishing conditions: 
	$ dim_k Hom(Delta_mu,nabla_nu)=delta_(mu,nu),Ext^i(Delta_mu,nabla_nu)=0 $
] <Lem_orthog_ext_vanish_highest_wt>
#proof[
	For the first orthogonality condition, note $Delta_mu->IC_mu$ is a projective cover in $cal(A)_(<=mu)$, so every quotient of $Delta_mu$ must have $IC_mu$ as a factor. Similarly, every subobject of $nabla_nu$ must intersect $IC_nu$. Thus, if there is a non-trivial map $Delta_mu->nabla_nu$, since the image and coimage is non-zero, we have 
	$ [Delta_mu:IC_nu]!=0, [Delta_nu:IC_mu]!=0 $
	which implies $nu<=mu$ and $mu<=nu$, so $mu=nu$. Then, to compute $dim_k Hom(Delta_mu,nabla_mu)$, by the fifth axiom, we have 
	$ Hom(Delta_mu,nabla_mu)=End(IC_mu)=k $
	For the $Ext^1$ vanishing, we put $Lambda' = {<=mu}union{<=nu}$. Then, either $mu$ or $nu$ or both is maximal in $Lambda'$, so the exact sequence 
	$ 0->nabla_nu->M->Delta_mu->0 $
	splits by either projectivity of $nabla_nu$ or injectivity of $Delta_mu$ in $cal(A)_(Lambda')$. 
	
	For higher $Ext$ vanishing, we prove by descending induction on $mu$. If $mu$ is maximal in $Lambda$, then $Delta_mu$ is projective and there is nothing to prove. In general, consider $P_mu->IC_mu$, which has a standard filtration with $Delta_mu$ the last term. Thus considering the long exact sequence of $Hom(-,nabla_nu)$ applied to 
	$ 0-->K-->P_mu-->Delta_mu-->0 $
	we have
	$ Ext^(i-1)(K,nabla_nu)-->Ext^i (Delta_mu,nabla_nu)-->Ext^i (P_mu,nabla_nu) $
	exact with the first term and last term 0 by induction. Thus the claim follows. 
]

#prop[
	Such categories have enough projective objects, with each projective admitting a finite filtration with standard associated graded pieces. The dual argument applies for injective objects. 
]
#proof[
	We prove the following statement by induction: There are enough projectives in $cal(A)_(Lambda')$, and each one admit a standard filtration. 

	We prove by induction on the cardinality of $Lambda'$. The case where $card Lambda'=1$ is trivial. Then, suppose $Lambda'$ and $Lambda' union {lambda}$ are both closed under taking smaller elements. We will prove the statement for $Lambda' union {lambda}$ from the statement for $Lambda'$. 
	
	Now, for any $mu in Lambda' union {lambda}$, we attempt to construct a projective cover of $IC_mu$ in $cal(A)_(Lambda' union {lambda})$. Since $Lambda'$ is closed under taking smaller elements, it is necessary that $lambda$ is an maximal element. Thus, $Delta_lambda->IC_lambda$ is a desired projective cover. Then, for $mu in Lambda'$, we wish to upgrade the projective cover $P->IC_mu$ in $cal(A)_(Lambda')$ to a projective cover in $cal(A)_(Lambda' union {lambda})$. We put $E=Ext^1(P,Delta_lambda)$. Since $P$ is not yet projective, $E$ somehow measures the extend that $P$ is non-projective. Then consider the unit element in 
	$ 1 in E times.o E^*=Ext^1(P,E^* times.o Delta_lambda) $
	This gives rise to an extension 
	$ 0-->E^* times.o Delta_lambda-->tilde(P)-->P-->0 $
	such that the composition 
	$ E->Hom(E^* times.o Delta_lambda,Delta_lambda)->^delta Ext^1(P,Delta_lambda) $
	is the identity. Then, since the first map is an isomorphism because $End(Delta_lambda)=End(IC_lambda)=k$, the boundary map is also an isomorphism. Then, by projectivity of $Delta_lambda$, $Ext^1(Delta_lambda,Delta_lambda)=0$. Hence, the long exact sequence 
	$ Hom(E^* times.o Delta_lambda,Delta_lambda)-->Ext^1(P,Delta_lambda)-->Ext^1(tilde(P),Delta_lambda)-->Ext^1(E^* times.o Delta_lambda,Delta_lambda) $
	gives $Ext^1(tilde(P),Delta_lambda)=0$. Now, it suffices to prove that $tilde(P)$ is a projective cover for $IC_mu$. This is equivalent to saying 
	$ dim_k Hom(tilde(P),IC_nu)=delta_(mu,nu),Ext^1(tilde(P),IC_nu)=0 $
	where the second condition ensures that $tilde(P)$ is projective and the first condition ensures that $tilde(P)->IC_mu$ is a cover. Consider the exact sequence 
	$ Ext^1(P,IC_nu)-->Ext^1(tilde(P),IC_nu)-->Ext^1(E^* times.o Delta_lambda,IC_nu) $
	the first term vanishes by the projectivity of $P$ in $cal(A)_Lambda'$, and the third vanishes by projectivity of $Delta_lambda$. So the second group vanishes. By the same reason, $dim_k Hom(tilde(P),IC_nu)=delta_(mu,nu)$. Thus, it suffices to prove the statement for $IC_lambda$. Then, to compute $Hom(tilde(P),IC_lambda)$, consider the exact sequence 
	$ 0-->K-->Delta_lambda-->IC_lambda-->0 $
	Then, $Hom(tilde(P),IC_lambda)=0$ because $K$ lies in $cal(A)_(Lambda')$ and run the exact sequence, and $Ext^1$ vanishes by the vanishing condition of $Ext^2$. 

	Hence, the original statement follows from induction. 
]

#coro[
	BGG reciprocity holds, that is, we have $(P_mu:Delta_nu)=[nabla_nu:L_mu]$
]
#proof[
	By the Hom orthogonality, the first number is equal to $dim_k Hom(P_mu,nabla_nu)$. For the second, consider the Jordan-Holder series of $nabla_nu$ 
	$ 0=F_0 subset dots.c subset F_n=nabla_nu $
	By the projectivity of $P_mu$, we have 
	$ 0-->Hom(P_mu,F_(i-1))-->Hom(P_mu,F_i)-->Hom(P_mu,IC_lambda)-->0 $
	exact, where $IC_lambda$ is a simple factor. But then, since $P_mu->IC_mu$ is a projective cover, $P_mu->IC_lambda$ is nontrivial iff $lambda=mu$, so the second number is equal to $dim_k Hom(P_mu,nabla_nu)$. 
]

#prop[
	Let $X=product.co_(lambda in Lambda)X_lambda$ be an affine stratification. Then, $Perv_Lambda (X)$ is a highest weight category in the sense of @KoszulFin. 
] <Prop_Perv_highest_wt>
#proof[
	We verify the axioms. The first three axioms are obtained directly by the properties of perverse sheaves on an affine stratified space. For the fourth property, it suffices to prove that $*$- or $!$-restriction to the open strata is exact (which is standard), because 
	$ Hom(Delta,-)=Hom(j_!1,-)=Hom(1,j^*(-))=j^*(-) $
	and the dual holds for $nabla$. Moreover, these objects are indecomposable, so they are the projective cover and injective hull. The fifth property also follows from the property of intermediate extensions. The final property is slightly more difficult, and is proven by the following property of perverse sheaves: firstly, by an analysis of extensions we have 
	$ Ext^2_Perv_Lambda (Delta_mu,nabla_nu)subset Hom^2_(D_Lambda)(Delta_mu,nabla_nu) $
	and for the latter, we have 
	$ 
	Hom^2_(D_Lambda)(Delta_mu,nabla_nu)=&Hom_D_Lambda (j_(mu!)1_mu [dim X_mu],j_(nu*)1_nu [dim X_nu+2]) \
	=&Hom_D_Lambda (j_nu^*j_(mu!)1_mu [dim X_mu],1_nu [dim X_nu+2])
	$
	Then, the first term is 0 for $nu!=mu$, and if $nu=mu$, then the above Hom is an ext group of vector spaces, which is 0. 
]

#coro[
	We have the realization functor an equivalence. 
	$ D(Perv_Lambda (X))->^tilde.eq D_Lambda (X) $
]
#proof[
	Note that $P_lambda$ and $nabla_lambda$ separately generates both $D(Perv_Lambda (X))$ and $D_Lambda (X)$. It suffices to show that 
	$ Ext^i_(Perv_Lambda (X))(P_mu,nabla_nu)=Hom^i_(D_Lambda (X))(P_mu,nabla_nu) $
	By projectivity of $P_mu$, the left hand side vanishes unless $i=0$. The right side also vanishes unless $i=0$ by the standard filtration of $P$ and applying the property of $!$-pushforwards. The statement for $i=0$ is trivial. 
]

Now, we may wish to generalize the above properties to possibly infinite stratifications. This is where the modern definition of highest weight categories come in. 

#def[
	Let $cal(A)$ be an Abelian category over some field $k$. We say $cal(A)$ is highest weight in the sense of @Highestwt2 if it is highest weight in the sense of @KoszulFin, but with the condition of the finite poset $Lambda$ replaced by for any $lambda in Lambda$, the set ${mu|mu<=lambda}subset Lambda$ is finite. 
] <Def_Highest_wt_cat_def_3>

Properties such as the orthogonality and Ext vanishing still holds. However, the category of perverse sheaves over a stratified space may not be highest weight, for example 
$ D(I\\L G\/I)!=D(Perv(I\\L G\/I)) $
which is an evidence of $Perv(I\\L G\/I)$ not being highest weight. Later on, we will adopt this definition of highest weight categories. 

#lem[
	Let $Lambda' subset Lambda$ be a subposet closed under taking smaller objects, and let $cal(A)$ be a highest weight category with weight poset $Lambda$. Then, the Serre quotient $pi:cal(A)->>cal(A)\/cal(A)_Lambda'$ is a highest weight category with weight poset $Lambda-Lambda'$. Its simple, standard, and costandard objects are the image of the projection $pi$ of the original simple, standard, and costandard objects. 
] <Lem_Serre_quot_highest_wt>
#proof[
	Axioms (1), (2), (4), (5) are obvious. Then, for (4), we claim that we have an isomorphism 
	$ Hom_(cal(A))(Delta_lambda,N)=Hom_(cal(A)\/cal(A)_(Lambda'))(pi(Delta_lambda),pi(N)) $
	for $lambda in Lambda-Lambda'$. This is because a map $pi(Delta_lambda)->pi(N)$ is represented by a map $M'->N\/N'$ in $cal(A)$, where $M' subset Delta_lambda$ and $N' subset N$ such that $Delta_lambda\/M$ and $N'$ is in $cal(A)_Lambda$. Then, since every quotient of $Delta_lambda$ necessarily contains $IC_lambda in.not cal(A)_Lambda$, we have $M'=Delta_lambda$. Then, since $N' in cal(A)_Lambda'subset cal(A)_(<=lambda)$, and that $Delta_lambda$ is projective in $cal(A)_(<=lambda)$, we have $Ext^1(Delta_lambda,N')=0$, which implies that the map $Delta_lambda->N\/N'$ factors through $N->N\/N'$. Hence, we have the above map is surjective. Moreover since $M'=Delta_lambda$ necessarily, and any map $Delta_lambda->N\/N'$ does note annihilate $IC_lambda$, it is non-zero. Thus the above map is an isomorphism. This implies that $Delta_lambda$ is projective in $(cal(A)\/cal(A)_Lambda')_(Lambda'')$ for $lambda$ maixmal in $Lambda''$. 

	Finally for axiom $(6)$, it suffices to prove the case where $Lambda$ is finite becuase to compute $Ext^2(pi(Delta_mu),pi(nabla_nu))$, it suffices to compute this in the category $cal(A)_(<=mu,nu)$, which is finite by assumption. However, in the finite case, we have enough projectives, which allows us to prove the claim as follows. We consider the object $pi(P_mu)->>pi(Delta_mu)$. The kernel of this map has a filtration by $pi(Delta_lambda)$ where $lambda>mu$. Then, if $pi(P_mu)$ is projective, the above vanishing of $Ext^2$ follows by the long exact sequence given by 
	$ Ext^1(K,pi(nabla_nu))-->Ext^2(pi(Delta_mu),pi(nabla_nu))-->Ext^2(pi(P_mu),pi(nabla_nu)) $
	where the last term is 0 by projectivity and the first is 0 by analysing extensions. Thus it suffices to prove projectivity. If not, consider a non-split surjection $pi(M)->>pi(P_mu)$. This surjection is represented by a map $M'->P_mu\/N'$ where $M\/M'$ and $N'$ lies in $cal(A)_(Lambda')$. Moreover, by surjectivity, this map must have cokernel lying in $cal(A)_(Lambda')$. However, since $P_mu->>IC_mu$ is a projective cover with $mu in.not Lambda'$, the cokernel must necessarily vanish, so the representing map is itself surjective. Thus, $M'->>P_mu$ splits, which contradicts $pi(M)->>pi(P_mu)$ not split. 
]

#prop[
	Let $cal(A)$ be a highest weight category with weight poset $Lambda$. Then we have the following. 
	+	The embedding $iota:D(cal(A)_(Lambda'))inj D(cal(A))$ is fully faithful. 
	+	The embedding $iota:D(cal(A)_(Lambda'))inj D(cal(A))$ admit left and right adjoints, denoted by $iota^L$ and $iota^R$. Moreover, the projection $pi:D(cal(A))->D(cal(A)\/cal(A)_(Lambda'))$ admit left and right adjoints, denoted by $pi^L$ and $pi^R$. These adjoints provide a semi-orthogonal decomposition of $D(cal(A))$, namely 
]

#def[
	Tilting objects
]

#todo[
	Finish this section. 
]

=== Where is Koszul duality? 

== Koszul Duality for Kac--Moody groups 

In this chapter, we give a review of Bezrukavnikov-Yun's paper @KosKacMoody

=== Kac--Moody lie algebras and Kac--Moody groups 

#def[
	We define a generalized Cartan matrix of size $ell$ to be a matrix $A in Mat_(ell times ell)(ZZ)$, such that the following conditions are satisfied: 
	+	$a_(i,i)=2$; 
	+	$a_(i,j)<=0$ for $i!=j$; 
	+	$a_(i,j)=0$ iff $a_(j,i)=0$. 

	We define a realization of a generalized Cartan matrix to be a triple $(frak(h),pi,pi^or)$, where $frak(h)$ is a complex $(2ell-rank A)$-dimensional vector space, $pi={alpha_1,dots.c,alpha_ell} subset frak(h)^*$ a set of roots, and $pi^or={alpha^or_1,dots.c,alpha^or_ell}subset frak(h)$ a set of coroots, subject to the relation $alpha_j (alpha_i^or)=a_(i,j)$. 
	
	By linear algebra, such realization exists and is unique up to isomorphism. 
] <Def_gen_Cartan_matrix>

#const[
	Given a generalized Cartan matrix $A$, we construct its associated Kac--Moody Lie algebra $frak(g)(A)$ by the following presentation: 
	-	It is generated by $frak(h)$ and symbols ${e_1,dots.c,e_ell,f_1,dots.c,f_ell}$. 
	-	The relations are given by 
		+	$[frak(h),frak(h)]=0$. 
		+	$[h,e_i]=alpha_i (h)e_i$, $[h,f_i]=-alpha_i (h)f_i$. 
		+	$[e_i,f_j]=delta_(i,j)alpha_i^or$. 
		+	$(ad e_i)^(1-a_(i,j))(e_j)=0$ for $i!=j$, and $(ad f_i)^(1-a_(i,j))(f_j)=0$. 
	
	We denote $frak(n)$ and $frak(n)^-$ by the subalgebra generated by ${e_i}$ and ${f_i}$ respectively. We define $frak(b)=frak(n)+frak(h)$ and $frak(b)^-=frak(n)^-+frak(h)$ the standard Borel subalgebras. We also define $tilde(frak(g))$ to be the Lie algebra generated by the same generators but only subject to the relations (1), (2), and (3). 
] <Const_Kac_Moody_Alg>

#def[
	Let $alpha in frak(h)^*$. We define the root space $frak(g)_alpha subset frak(g)$ to be the subspace 
	$ frak(g)_alpha={x in frak(g) | [h,x]=alpha(h)x,forall h in frak(h)} $
	We define $Q=plus.o.big ZZ alpha_i$, and $Q^+=plus.o.big ZZ_(>=0) alpha_i$ the root lattice and nonnegative root lattice. $Q^-$ is defined likewise. We say $alpha in Q^+$ is a positive root if $frak(g)_alpha!=0$. We denote the set of positive roots by $R^+$. We likewise define $R$ and $R^-$. 

	For a root $alpha$, we define $|alpha|=sum n_i$, where $alpha=sum n_i alpha_i$. 
] <Def_root_space>

#thm[
	We have the following decompositions for $frak(g)$: #h(1fr)
	+	$frak(g)=frak(n)plus.o frak(h)plus.o frak(n)^-$ as vector spaces. 
	+	$ frak(n)^plus.minus=plus.o.big_(alpha in Q^plus.minus)frak(g)_alpha $
		Moreover, each root space is finite dimensional. 
] <Thm_decomp_Kac_Moody_alg>
#proof[
	Omitted. 
]

#const[
	Then, we slightly enlarge the above constructed Lie algebra. We define the complete version of the Lie algebra 
	$ hat(frak(n))=product_(alpha in R^+)frak(g)_alpha $
	equipped with the natural Lie bracket. This is well-defined because each root space is finite dimensional. Then, notice the family of ideals 
	$ hat(frak(n))(k)=product_(alpha in R^+\ |alpha|>=k)frak(g)_alpha $
	gives $hat(frak(n))$ a structure of a pro-Lie algebra. Moreover, it is pro-nilpotent. Thus, its exponential gives a well-defined pro-algebraic group $cal(U)$, namely given by 
	$ cal(U)=lim_k exp(hat(frak(n))\/hat(frak(n))(k)) $
	Then, one defines the Kac--Moody group $G$ by adding the weight 0 and negative part one by one, with no completion involved in the process. 
] <Const_naive_max_pro_unip>

However, the above construction has two caveats: firstly, it works well only for characteristic 0 fields. To work over base fields of arbitrary characteristic, we need to slightly modify the above and arrive at the following integral construction. Secondly, it lacks the additional root datum as in the finite dimensional case to define a group, and will arrive at only the simply connected Kac--Moody groups. 

#def[
	We define a Kac--Moody root datum of a generalized Cartan matrix $A$ to be a finite rank free Abelian group $X$ and morphisms of lattices $alpha:Q->X$ and $alpha^or:Q^or->X^or$, such that the pairing is preserved under the morphisms. Explicitly, we choose ${alpha_i}subset X$ and ${alpha_i^or}subset X^or$ such that $bracket(#[$alpha_j,alpha_i^or$])=a_(i,j)$. We call this datum $cal(D)$.
] <Def_Kac_Moody_root_datum>

#const(name: [Mathieu])[
	We construct the Kac--Moody Lie algebra $frak(g)(cal(D))$ associated to the Kac--Moody root datum $cal(D)$. In fact, the construction is completely analogous to @Const_Kac_Moody_Alg, but with the naive $frak(h)$ replaced by $X^or times.o QQ$, and everything works rationally. We will not copy the generators and relations again. 

	We then define the Chevalley--Tits integral enveloping algebra $cal(U)_ZZ (frak(g))subset U_QQ (frak(g))$. We take 
	$ e_i^((n))=e_i^n/n!,f_i^((n))=f_i^n/n!,binom(x^or,n)=(x^or dot.c (x^or-1)dot.c dots.c dot.c (x^or-n+1))/n! $
	We then take $cal(U)_ZZ (frak(g))$ to be the integral lattice spanned by the above generators. 
	
	We can likewise define $cal(U)_ZZ^+=cal(U)_ZZ (frak(n)^+)=U_QQ (frak(n)^+)inter cal(U)_ZZ (frak(g))$, or equivalently generated by the elements $e_i^((n))$, by an integral version of the PBW theorem. More generally, take $Psi subset Delta_+$ a subset of positive roots closed under addition. We take 
	$ frak(g)_Psi=plus.o.big_(alpha in Psi)frak(g)_alpha $
	and $cal(U)_ZZ (Psi)=U(frak(g)_Psi)inter cal(U)_ZZ (frak(g))$. 
	
	Then, we define the restricted gradewise dual of the above Hopf algebra
	$ ZZ[U_Psi^max]:=plus.o.big_(gamma in NN Psi)cal(U)_ZZ (Psi)_gamma^or $
	where $cal(U)_ZZ (Psi)_gamma$ denote the graded piece of $cal(U)_ZZ (Psi)$ with weight $gamma$. Then since $cal(U)_ZZ (Psi)$ is a cocommutative Hopf algebra, we have $ZZ[U_Psi^max]$ a commutative Hopf algebra, whose spectrum defines a group scheme 
	$ U_Psi^max = Spec ZZ[U_Psi^max] $
	We can see that this is a pro-unipotent group via the following height filtration: 
	$ U_Psi^max = lim U_Psi^max \/ U_(Psi,>=n)^max $
	where $(Psi,>=n)$ is the subset of $Psi$ containing of positive roots $alpha$ such that $|alpha|>=n$. We can also compute its $k$-points for any $k$. Take 
	$ hat(cal(U),size:#140%)_k (Psi)=product_(gamma in NN Psi)(cal(U)_ZZ (Psi)times.o k) $ 
	and we have $U_Psi^max (k)$ the group-like elements in $hat(cal(U),size:#140%)_k (Psi)$, which is another evidence of pro-unipotence. 
	For $Psi=Delta_+$, we define $U_+^max=U_Psi^max$. 
] <Const_Kac_Moody_Alg_root_dat_max_pro_unip>

#const(name: [Mathieu])[
	Now we construct the whole group. For this, we first need the exponential map. Let $x in frak(g)_(alpha,ZZ)$. We define an exponential sequence for $x$ to be $(x^([n]))_(n>=0)$, where $x^([n])in cal(U)_(ZZ,n alpha)^+$, subject to the conditions $x^[0]=1$, $x^[1]=x$, $x^[n]-x^((n)) in F_(n-1)U_QQ (frak(g))$, where $F$ is the PBW filtration (this means their difference is measured by polynomials of degree at most $n-1$). Moreover, we require the formula 
	$ Delta(x^[n])=sum_(a+b=n)x^[a]times.o x^[b],epsilon(x^[n])=0,n>0 $

	For any $x$, an exponential sequence always exists: firstly one finds integral lifts of $x^((n))$, and modulo low PBW filtered terms to adjust to the final formula. 

	Notice that for $alpha$ a real root, we may choose $x^[n]=x^((n))$ because $alpha$ is conjugate to some simple root $alpha$, so $x^((n))$ is known to be integral. The above formulas are obviously satisfied. 
	
	We now use this exponential sequence to construct an exponential map. Let $R$ be any commutative ring. For $lambda in R$, we define $[exp](lambda x):=sum lambda^n x^[n] in hat(cal(U),size:#140%)_R^+$. The above formulas ensure that $[exp](lambda x)$ is a group-like element, so lies in $U_+^max (R)$. Then, this map is functorial in $R$, so assembles to a map $E_x:AA^1_ZZ->U_+^max$. Note that by unwinding definitions, this map is a group homomorphism iff 
	$ x^[m]x^[n]=binom(m+n,m)x^[m+n] $
	which holds for $alpha$ a real root, but not necessarily holds for imaginary roots. 
	
	We take $H$ to be the torus with root lattice $X$ and coroot lattice $X^or$. Then, we have $H lact U^max_+$ via $h dot.c [exp](lambda x) dot.c h^(-1)=[exp](alpha(h)lambda x)$ for $x in frak(g)_alpha$. We left it to the readers that this action is indeed well-defined. With this property, we may define 
	$ B_+^max = U_+^max times.r H $

	We then extend this definition to negative roots. For each simple root $alpha_i$, the $frak(s l)_2$-triple $e_i,f_i,alpha_i^or$ integrates to a reductive group $G_i$ with positive part $U_i$, and take $G_i *_(U_i)B_+^max$ gives a minimal parabolic group $P_i supset B_+^max$, with the quotient $P_i\/B_+^max$ given by $PP^1$. 

	Then let $W$ denote the Weyl group of the Kac--Moody algebra (i.e., the subgroup of $GL(X times.o QQ)$ generated by the reflections $s_i: alpha mapsto alpha-bracket(#[$alpha,alpha^or_i$])alpha_i$). Take a word presentation $bold(s)=s_i_1 dot dots.c dot s_i_n$. We define $E(bold(s))=P_i_1 times^B P_i_2 times^B dots.c times^B P_i_n$ (in this construction, we abbreviate $B_+^max$ by $B$). Then, we define the Bott-Samuelson variety $D(bold(s))=E(bold(s))\/B$, where $B$ acts on the right of $P_i_n$. If we take $bold(s)'=s_i_1 dot dots.c dot s_i_(n-1)$, we have that $D(bold(s))->>D(bold(s)')$ by forgetting the final factor. This is actually a $PP^1$-bundle since $P_i_n\/B=PP^1$. Then, $D(nothing)=pt$, so $D(bold(s))$ is smooth, projective, and geometrically integral. We remark here that $D(bold(s))$ is the compactification of 
	$ B s_i_1 B times^B B s_i_2 B times^B dots.c times^B B_s_i_n B\/B=AA^n:=D(w)^circle $
	We then construct the Schubert cells. Take a regular dominant weight $lambda$ and its highest weight module $L(lambda)$ (finite dimesional) with highest weight vector $v_lambda$. Then, for $w in W$ we pick a reduced word presentation (which we abuse notations and also denote by $w$). We have a map 
	$ pi_w:D(w)->PP(L(lambda)), [p_1,dots.c,p_n]mapsto[p_1 dot p_2 dot dots.c dot p_n dot v_lambda] $
	The image is well-defined since $B$-action preserves the highest weight line in $L(lambda)$. Then, picking a set of Weyl lifts $dot(s)_i_j$, $pi_w ([dot(s)_i_1,dots.c,dot(s)_i_n])$ is the line $[L(lambda)_(w lambda)]$. We define $S_w=overline(B[L(lambda)_(w lambda)])subset PP(E_w (lambda))$
	where $E_w (lambda)=U(frak(b))L(lambda)_(w lambda)$ is upward part of $L(lambda)$ over $L(lambda)_(w lambda)$ (sorry for the unfortunate notation). This image has the image of a projective scheme, induced by $pi_(w,*)cal(O)_(D(w))$, hence we obtain a map of projective schemes $pi_w:D(w)->>S_w$. After we have finished constructed $G$ and $G\/B$, we should think $S_w approx overline(B w B\/B)$, and the projection $pi_w:D(w)->>S_w$ as the multiplication map 
	$ P_i_1 times^B dots.c times^B P_i_n \/B->overline(B w B\/B) $ 
	Moreover, we have $pi_w$ an isomorphism on the open cells $pi_w:D(w)^circle->^tilde.eq C_w=im(D(w)^circle)$. 

	Finally, we construct $B(w)$, which is a $B$-torsor over $S_w$, which we should think of the closed cell $overline(B w B)$. We first let $cal(L)(M)$ be the constant quasi-coherent sheaf over $D(w)$ associated to the $B$-module $M$, and $cal(L)_w (M)=pi_(w,*)cal(L)(M)$. We define $B(w)=underline(Spec)_(S_w)cal(L)_w (k[B])$, which gives an affine morphism $nu_w:B(w)->S_w$. Actually, we have the non-trivial fact that $B(w)=Spec Gamma(E(w),cal(O)_(E(w)))$. However the core property we want to use is that $B(w)->S_w$ is a $B$-torsor. 

	For $u,v in W$, recall that we can define $u*v in W$ to be the element defined recursively: pick a reduced word presentation $s_i_1 dot dots.c dot s_i_r = v$, we define $u*v:=u*s_i_1 *s_i_2 *dots.c*s_i_r$, and for a simple reflection $s$, we define $u*s=max(u,u s)$. Then, the above construction gives a multiplication $E(u)times E(v)->B(u*v)$, which descends to $B(u)times B(v)->B(u*v)$ (to be thought of $overline(B u B)times overline(B v B)subset overline(B(u*v)B)$) by affinization. With these structural maps, we take 
	$ G=colim_(w in W)B(w) $
	which gives a ind-group structure. 
] <Const_Kac_Moody_grp>

#const[
	We define $Fl=G\/B=colim S_w$ to be the affine flag variety, which is also canonically an ind-scheme. The open Schubert cell $Fl_w=B w B\/B=AA^ell(w)$, which can also be thought of the image of $C_w$ constructed previously. We hence have
	$ Fl=product.co_(w in W)Fl_w,S_w=product.co_(v<=w)Fl_w $
	Likewise, we may define the enhanced flag variety $tilde(Fl,size:#140%)=G\/U$, which is a $H$-torsor over $Fl=G\/B$. 
] <Const_Kac_Moody_flag_var>

#const[
	If we let $Sigma subset W$ denote the subset of simple reflections, and take $Theta subset Sigma$ such that the subgroup of $W$ generated by $Theta$ is finite, likewise to the construction of $P_i$'s in @Const_Kac_Moody_grp we can construct a parabolic subgroup $P_Theta$. Then, we define $L_Theta$ the Levi subgroup, and $U_Theta$ the unipotent radical of $P_Theta$. We let $B_Theta$ be the Borel of $L_Theta$. Finally, we define $U^-_L_Theta$ to be the negative unipotent radical of $L_Theta$. 

	In the following chapter, we will adopt the left flag variety notation. That is, we take $Fl=B\\G$, and for any $Theta$ satisfying the condition above, take $attach(Fl,bl:Theta)=P_Theta\\G$. Moreover, we let $W_Theta$ denote the Weyl group of $L_Theta$, and $[W_Theta\\W]subset W$ the set of minimal length representatives of the cosets. It inherits a length function and a poset structure from $W$. We denote the maximal length element $w_Theta in W_Theta$ of length $ell_Theta$. Then, we have the strata of $P_Theta\\G\/B$ indexed by $overline(w) in [W_Theta\\W]$. We make the following definitions 
	$ i_overline(w):attach(Fl,bl:Theta)_(overline(w))inj attach(Fl,bl:Theta), #h(2em) i_(<overline(w)):attach(Fl,bl:Theta)_(<overline(w))inj attach(Fl,bl:Theta), #h(2em) i_(<=overline(w)):attach(Fl,bl:Theta)_(<=overline(w))inj attach(Fl,bl:Theta) $
	The stratas are affine spaces of corresopnding dimensions. When $Theta=nothing$, this reduces to the plain flag variety case. 

	Then, consider $U_Theta U^-_L_Theta$. The orbits of $U_Theta U^-_L_Theta\\G\/B$ are still indexed by $w in W$, and we take 
	$ attach(Fl,bl:Theta)^w=U_Theta U^-_L_Theta dot B w B\/B subset attach(Fl,bl:Theta), #h(2em) attach(Fl,bl:Theta)^(<=^Theta w)=overline(attach(Fl,bl:Theta)^w) $ 
	where $s<=^Theta t$ means $w_Theta s <= w_Theta t$. 

	Finally, we take $tilde(Fl,size:#140%)=G\/U$, and make the likewise definitions $tilde(i)_w:tilde(Fl,size:#140%)_w inj tilde(Fl,size:#140%)$ to be the preimages of $Fl_w$. The other definitions are done likewise. 
] <Const_Kac_Moody_parabolics>

#const[
	We construct the big cell $C subset Fl$. In the finite dimensional case, this construction coincides with the cell $B^- B\/B$. Again we construct it as an ind-scheme. Recall that we have a projective embedding $S_w inj PP(E_w (lambda))$, where $E_w (lambda)=U(frak(b))L(lambda)_(w lambda)$. Then, the contragradient $L(lambda)^*$ has a lowest weight line $sigma_(-lambda)$. We define $C_w$ to be the complement to the hyperplane $sigma_(-lambda)=0$, and $C=colim C_w$. 
] <Const_big_cell>

#lem[
	Let $mu:GG_m->H$ be any antidominant regular coweight. Then for any $w in W$, $C_w$ contracts to the base point $B\/B in Fl$ under the left action of $mu(GG_m)$. Hence, for any $v, w in W$, $v C inter Fl_(<=w)$ contracts to the point $v B\/B in Fl$ under the action of $(v mu)GG_m$. 
] <Lem_big_cell_contracts_Weyl_grp>
#proof[
	By definition of $C_w$. 
]

=== A realization result 

#def[
	Consider the category $Vect_(overline(QQ)_ell)$. We define a Frobenius module $M$ to be an object $M in Mod_(overline(QQ)_ell)$ equipped with an automorphism $Fr_M :M->M$. We denote the category of Frobenius modules by $Mod(Fr)$. We define a Frobenius module to be locally finite if it is a union of its finite submodules. For any Frobenius module $M$, we denote $M^f$ by the union of its finite submodules. 

	There is clearly a forgetful functor $Mod(Fr)->Vect_(overline(QQ)_ell)$ given by $M mapsto M^(Fr)$, the fixed point functor. Later on, we will use this functor to realize a category enriched over $Mod(Fr)$ to a DG category over $overline(QQ)_ell$. 
] <Def_Frob_mod>

#def[
	We define a locally finite Frobenius module to be continuous if the action $ZZ lact M$ through Frobenius extends to an action $hat(ZZ,size:#12pt) lact M$. For a locally finite Frobenius module, we may define its weights as in the usual convention. For a general Frobenius module $M$, we make the above definitions after applying $M^f$. 

	From now on, we assume every Frobenius module to be continuous with integral weights. 
]

#def[
	Let $M$ be a Frobenius module. We define $M^(Fr#[-]unip)$ to be the Frobenius submodule of $M$ on which $Fr_M$ acts unipotently. We define $M^op$ to denote the Frobenius module with the same underlying vector space as $M$, but with the inverse Frobenius action. 
]

#def[
	Let $E$ be a $overline(QQ)_ell$-algebra. Let $E$ be equipped with a continuous Frobenius module structure compatible with its algebra structure, we define $Mod_(E,Fr)$ to be the category of $E$-modules equipped with a Frobenius automorphism compatible with the Frobenius module structure on $E$. 
]

In this section, our main goal is to answer the following question. 

#question[
	For a category $cal(D)$ enriched in $Mod_Fr$, when do we have a fully faithful inclusion $cal(D)inj Mod_(E,Fr)$? 
]

We will show this with the following assumptions. 

#ass[
	Let $cal(D)$ to be a $overline(QQ)_ell$-linear category enriched in $D(Fr)$ (equivalently, the $Hom$ and $Ext$ groups are Frobenius modules), and is equipped with the following data: 
	+	A finite poset $Lambda$ such that $cal(D)$ has a recollement indexed by $Lambda$ (that is, a series of open-closed semi-orthogonal decompositions). We define $cal(D)_lambda=cal(D)_(<=lambda)\/cal(D)_(<lambda)$. 
	+	A full additive subcategory $cal(C)_lambda subset cal(D)_lambda$ stable under taking tensor with unipotent Frobenius modules, such that for any objects $c_1,c_2 in cal(C)_lambda$, we have 
		$ Ext^i_(cal(D)_lambda) #h(-3pt) (c_1,c_2)^(Fr#[-]unip)=0 $
	+	$cal(C)_lambda$ generates $cal(D)_lambda$ as a triangulated category. Moreover, there is an object $bb(1)_lambda in cal(C)_lambda$ such that every object in $cal(C)_lambda$ is of the form $bb(1)_lambda times.o M$ for some $M in D(Fr)$ (however, for arbitrary $M$, the object $bb(1)_lambda times.o M in cal(D)_lambda$ may not lie in $cal(C)_lambda$). 
	+	There exists an object $c_lambda in cal(C)_(<=lambda)$ such that $i_lambda^*c_lambda=bb(1)_lambda$. Moreover, the induced ring morphism 
		$ i_alpha^*:End(c_lambda)->End(bb(1)_lambda) $
		has a nilpotent kernel. 
	We let $cal(C)$ denote the full subcategory of $cal(D)$ consisting of objects $d$ such that $i_lambda^*d,i_lambda^!d in cal(C)_lambda$. 
] <Ass_realization>

In practice, $cal(D)$ will be a category of mixed $ell$-adic sheaves constructible with respect to a certain stratification, and $cal(C)_alpha$ the weight 0 constant sheaves (normally we would have locally constant, but we require constant in our case) over a strata. Then $cal(C)$ will be the category of weight 0 sheaves. 

The main theorem is the following, which would be our main technical tool later on. 

#thm[
	For a category $cal(D)$ satisfying the requirements in @Ass_realization, there is a $overline(QQ)_ell$-algebra $E$ with a Frobenius action, such that $cal(D)inj D(E,Fr)$ is fully faithful in the sense that both categories are enriched in $Set$ rather than $D(Fr)$. Moreover, such construction is functorial for functors preserving the subcategory $cal(C)$. 
] <Thm_realization>

We will begin with a simple lemma on the computation of a homotopy fixed point. 

#lem[
	Let $M in D(Fr)$. Then, 
	$ 0-->H^(i-1)(M)_(Fr)-->H^i (M^(h Fr))-->H^i (M)^Fr-->0 $
]
#proof[
	Consider the following description of homotopy fixed points of a $ZZ$ action as a fiber 
	$ M^(h Fr)-->M-->^(Fr-id)M $
	Then the desired exact sequence follows from the long exact sequence of the fiber sequence. 
]

#coro[
	Let $cal(D)$ satisfy the condition (1) and (2) in @Ass_realization. Then, for $c_1,c_2 in cal(C)$, we have 
	$ Ext_cal(D)^i (c_1,c_2)^(Fr#[-]unip)=0, i!=0 $
	and 
	$ H^i (RHom_cal(D)(c_1,c_2)^(h Fr))=cases(Hom_cal(C)(c_1,c_2)^Fr &"if" i=0, Hom_cal(C)(c_1,c_2)_Fr &"if" i=1,0 &"otherwise") $
] <Cor_compute_Ext_conc>
#proof[
	For the first assertion, we apply induction on the stratas. On one strata, this is precisely condition (2). Then consider the excision triangle, which gives rise to the following long exact sequence for $c_1,c_2 in cal(C)_(<=lambda)$
	$ dots.c -->Ext^i_(cal(C)_(<lambda))(i_(<lambda)^*c_1,i_(<lambda)^! c_2)^(Fr#[-]unip)-->Ext^i (c_1,c_2)^(Fr#[-]unip)-->Ext^i_(cal(C)_lambda)(i^*_lambda c_1,i^*_lambda c_2)^(Fr#[-]unip)-->dots.c $
	which gives the vanishing result. 

	For the second assertion, notice that for any $M in Mod_Fr$, we have $M^Fr subset M^(Fr#[-]unip)$. The rest follows from the previous lemma. 
]

#lem[
	We adopt the decreasing filtration convention. Then, there is an equivalence of categories 
	$ tilde(gr,size:#120%):Fil(cal(C))->Ch(cal(C)) $
	where $Fil(cal(C))$ is the full subcategory of $Fil(cal(D))$ such that $gr^i (F^bullet d) in cal(C)[-i]$, and $Ch(cal(C))$ is the category of chain complexes without any homotopy relations. Here, chain complexes mean the composite of two differentials are homotopic to 0. The equivalence is given by 
	$ tilde(gr,size:#120%)(F^bullet d)=dots.c-->gr^i (d)[i]-->gr^(i+1)(d)[i+1]-->dots.c $
	where the transition maps are given by the following triangle 
	$ gr^(i+1) (F^bullet d)-->gr^([i,i+1])(F^bullet d)-->gr^i (F^bullet d)-->gr^(i+1)(F^bullet d)[1] $ 
]
#proof[
	This is well-known if $cal(C)$ is a stable $oo$-category. Now, $cal(C)$ is a additive subcategory of such, the proof is likewise. 
]

#def[
	Let $K_acyc (cal(C))subset K(cal(C))$ denote the subcategory of the bounded homotopy category spanned by objects equivalent to $0 in cal(D)$.  
]

#lem[
	For any $c in cal(C)$, the functors 
	$ Hom(c,-)^(Fr#[-]unip),Hom(-,c)^(Fr#[-]unip):K_acyc (cal(C))->K_acyc (cal(C)) $
	maps any complex to an exact sequence. 
] <Lem_Fr_unip_Hom_exact>
#proof[
	Fix an object $cal(F) in Fil(cal(C))$ such that $tilde(gr,size:#120%)cal(F) in K_acyc (cal(C))$. Consider the spectral sequence 
	$ E_1^(p,q)=Ext^(p+q)(c,gr^p cal(F))=Ext^q (c,gr^p cal(F)[p])==>Ext^(p+q)(c,cal(F)) $
	However, since $tilde(gr,size:#120%)cal(F) in K_acyc (cal(C))$, $cal(F)tilde.eq 0 in cal(D)$. Thus, the above spectral sequence converges to 0. Then, applying $(-)^(Fr#[-]unip)$ to it, the spectral sequence degenerates at page 1 because $q$ is forced to be 0. Thus, since the spectral sequence also converges to zero, the complex at $q=0$ is exact. 
]

#def[
	We define $cal(C)^(Fr#[-]unip)$ to be the category with the same objects as $cal(C)$, but with $Hom$ groups replaced by 
	$ Hom_(cal(C)^(Fr#[-]unip))(c_1,c_2)=Hom_cal(C) (c_1,c_2)^(Fr#[-]unip) $
]

#const[
	Notice that the forgetful functor $cal(C)->cal(C)^(Fr#[-]unip)$ admits a pro-left adjoint $cal(C)^(Fr#[-]unip)->Pro(cal(C))$, given by $c mapsto c[[t]]=lim c[t]\/t^n=c times.o overline(QQ)_ell [[t]]$, where Frobenius acts on $overline(QQ)_ell [[t]]$ by multiplying by $exp t$. Explicitly, we have 
	$ Hom(c,c')^(Fr#[-]unip)=Hom(c[[t]],c')^Fr $
	We remark that the exponential here is used to ensure unipotency. 
]

#prop[
	We have a well-defined functor $rho(cal(C)):K(cal(C))\/K_acyc (cal(C))->cal(D)$. Moreover, it is fully faithful, and is essentially surjective if $cal(C)_alpha$ generates $cal(D)_alpha$ as a triangulated category. 
] <Prop_half_realization>
#proof[
	Recall that maps $Hom_(K(cal(C))\/K_acyc (cal(C)))(c_1,c_2)$ are computed by spans $c_1<-c->c_2$, where $cofib(c->c_1) in K_acyc (cal(C))$. We may assume that $c_1 in cal(C)$, and we first show that taking the two term complex $c_1[[t]]->c_1[[t]]$ is an initial (pro-) object mapping to $c_1$ with an acyclic cone. For this, we suppose $c->c_1$ has an acyclic cone. Writing 
	$ c=dots.c-->c^(-1)-->c^0-->c^1-->dots.c $
	the cone is of the form 
	$ dots.c-->c^(-1)-->c^0-->c^1 plus.o c_1-->dots.c $
	Thus, by @Lem_Fr_unip_Hom_exact, taking $Hom(c_1,-)^(Fr#[-]unip)$, we obtain a long exact sequence 
	$ dots.c-->Hom(c_1,c^0)^(Fr#[-]unip)-->Hom(c,c^1 plus.o c_1)^(Fr#[-]unip)-->dots.c $
	This amounts to the exact sequence 
	$ dots.c-->Hom(c_1[[t]],c^0)^Fr-->Hom(c_1[[t]],c^1plus.o c_1)^Fr-->dots.c $
	Note the Frobenius equivariant map $(0,p):c_1[[t]]->c^1 plus.o c_1$ has zero image, thus it comes from a map $phi_0:c_1[[t]]->c^0$. Then, since we want $-times t:c_1[[t]]->c_1[[t]]$, we also have $t phi_0:c_1[[t]]->c^0$ zero, so it comes from a map $phi^(-1):c_1[[t]]->c^(-1)$. Thus, we obtain a commutative square // https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJjXzFbW3RdXSJdLFsxLDAsImNfMVtbdF1dIl0sWzAsMSwiY14oLTEpIl0sWzEsMSwiY14wIl0sWzAsMSwidCJdLFswLDIsInBoaV8oLTEpIiwyXSxbMSwzLCJwaGlfMCJdLFsyLDNdXQ==
	#align(center, diagram({
		node((0, 0), [$c_1[[t]]$])
		node((1, 0), [$c_1[[t]]$])
		node((0, 1), [$c^(-1)$])
		node((1, 1), [$c^0$])
		edge((0, 0), (1, 0), [$t$], label-side: left, "->")
		edge((0, 0), (0, 1), [$phi_(-1)$], label-side: right, "->")
		edge((1, 0), (1, 1), [$phi_0$], label-side: left, "->")
		edge((0, 1), (1, 1), "->")
	}))
	which in turn exhibits initialness. 

	Hence, $Hom^bullet_(K(cal(C))\/K_acyc (cal(C)))(c_1,c_2)^(h Fr)$ is equivalently the two term complex 
	$ 0-->Hom(c_1[[t]],c_2)^Fr-->^((times t)^*)Hom(c_1[[t]],c_2)^Fr-->0 $
	which, by the universal property, is the complex 
	$ 0-->Hom(c_1,c_2)^(Fr#[-]unip)-->^(log Fr)Hom(c_1,c_2)^(Fr#[-]unip)-->0 $
	which is precisely the complex computing $Hom^bullet_cal(D) (c_1,c_2)^Fr$, by @Cor_compute_Ext_conc. Thus the functor is fully faithful. The image is clearly generated by the $cal(C)_alpha$'s, in a somewhat inaccurate sense. 
]

Now, we notice that $cal(C)^(Fr#[-]unip)$ is in some sense the Frobenius semisimplification, as opposed to $cal(C)^Fr$ is removing the Frobenius structure. This can be shown in the following lemma. 

#lem[
	From now on, we require $cal(D)$ to satisfy all assumptions from @Ass_realization. For any $c in cal(C)$, there are complexes $M_lambda in D(Fr)$, such that 
	$ c=plus.o.big c_lambda times.o M_lambda in cal(C)^(Fr#[-]unip) $
] <Lem_Frob_semisimplification>
#proof[
	Notice that we have $Ext^1_(cal(C)_(<lambda))(i^*_(<lambda)c_1,i^!_(<lambda)c_2)^(Fr#[-]unip)=0$, so the restriction map 
	$ Hom_(cal(C))(c_1,c_2)^(Fr#[-]unip)->>Hom_(cal(C)_lambda)(i_lambda^*c_1,i_lambda^*c_2)^(Fr#[-]unip) $
	is surjective. 

	To prove the statement, we apply induction on the support of $c$. Suppose $c in cal(C)_(<=lambda)$. Then we have $i_lambda^*c=bb(1)_lambda times.o M_lambda$. Moreover, since the left isomorphism is naturally Frobenius invariant, by the above surjection, the isomorphism lifts to a retraction diagram 
	$ c_lambda times.o M_lambda->c->c_lambda times.o M_lambda $
	This is a retraction since $End(c_lambda)->End(bb(1)_lambda)$ has nilpotent kernel, so any preimage of an isomorphism is an isomorphism. 

	Since retractions splits off, we may assume $c=c_lambda times.o M_lambda plus.o c'$, where $c'$ is supported on $cal(C)_(<lambda)$. Thus by induction, the proof is finished. 
]

#coro[
	Let $c in cal(C)$ be such that $End(c)$ is $Fr$-semisimple. Then, 
	$ c tilde.eq plus.o.big c_lambda times.o M_lambda in cal(C) $
	such that $M_lambda$ is a Frobenius semisimple complex. 
] <Cor_End_semisimple_Fr_semisimple>
#proof[
	The idempotents corresponding to $c_lambda times.o M_lambda$ in $cal(C)^(Fr#[-]unip)$ is actually Frobenius invariant because $End(c)$ is semisimple, so the direct sum decomposition occurs in $cal(C)$. Then, obviously each $M_lambda$ would be semisimple, otherwise $End(M_lambda)$ would not be semisimple. 
]

Now, suppose there is a family of objects $d_lambda in cal(C)_(<=lambda)$ also pulling back to $bb(1)_lambda$. For example, $d_lambda=c_lambda$ is a valid choice. 

#lem[
	$cal(D)$ is generated by ${d_lambda}_(lambda in Lambda)$. 
]
#proof[
	Again we apply induction on the stratas. Suppose $cal(D)_(<lambda)$ is generated by $d_mu$s for $mu<lambda$. Then, by adjunction, we have a map $i_(lambda!)bb(1)_lambda->d_lambda$, whose cofiber lies in $cal(D)_(<lambda)$, so is generated by $d_mu$s for $mu<lambda$. Thus, $i_(lambda!)bb(1)$ is generated by $d_mu$s for $mu<=lambda$. But $cal(D)_(<=lambda)$ is generated by $i_(lambda!)bb(1)_lambda$ and $cal(D)_(<lambda)$ by assumption (3). Thus, we are done. 
]

#proof[
	Now we are ready to prove @Thm_realization. We let $d=plus.o.big d_lambda$, and take the $overline(QQ)_ell$-algebra $E$ to be 
	$ E=plus.o.big_(i in ZZ)Ext^i_(cal(D))(d,d)^op $
	In particular, this is concentrated at degree 0, so not a DG algebra. We will prove that we have a fully faithful functor $cal(C)inj Mod_(E,Fr)$, and then take derived categories, and prove $K(cal(C))\/K_acyc (cal(C))inj D(E,Fr)$ is fully faithful. Finally, by @Prop_half_realization, we obtain the desired fully faithful map. 

	Firstly, the functor $cal(C)inj Mod_(E,Fr)$ is via the obvious Yoneda functor 
	$ h_d=plus.o.big_(i in ZZ)Ext^i_cal(D)(d,-):cal(C)->Mod_(E,Fr) $
	Note that by definition 
	$ Hom_(Mod_(E,Fr))(h_d (c_1),h_d (c_2))=Hom_E (h_d (c_1),h_d (c_2))^(Fr) $
	so we only need 
	$ Hom_(cal(C))(c_1,c_2)^(Fr#[-]unip)->^tilde.eq Hom_E (h_d (c_1),h_d (c_2))^(Fr#[-]unip) $
	For this, if we have $c_1=d$, then 
	$ Hom_E (h_d (d),h_d (c_2))^(Fr#[-]unip)=Hom_E (E,h_d (c_2))^(Fr#[-]unip)=h_d (c_2)^(Fr#[-]unip)=Hom_(cal(C))(d,c_2)^(Fr#[-]unip) $
	And then, by projecting to direct summands in $cal(C)^(Fr#[-]unip)$, we see the above map is an isomorphism for $d_lambda$s. Finally, since the $d_lambda$s generates $cal(C)^(Fr#[-]unip)$ under direct sums, we have the functor fully faithful. 

	Then passing to homotopy categories, we first prove $K_acyc (cal(C))$ is null-homotopic in $K(cal(C)^(Fr#[-]unip))$. This is done by @Lem_Fr_unip_Hom_exact, and explicitly constructing the contracting homotopy via the exactness of $Hom$ functors. Thus, we have a well-defined map $K(cal(C))\/K_acyc (cal(C))->D(E,Fr)$. However, in this case, the $Ext$ groups are computed likewise as above, so we are done. 

	Finally, for the functoriality, for a map $Phi:cal(D)->cal(D)'$ with $Phi|_cal(C):cal(C)->cal(C)'$, we claim that we have the following commutative diagram: // https://q.uiver.app/#r=typst&q=WzAsNixbMCwwLCJjYWwoRCkiXSxbMCwxLCJjYWwoRCknIl0sWzEsMCwiSyhjYWwoQykpXFwvS19hY3ljIChjYWwoQykpIl0sWzEsMSwiSyhjYWwoQyknKVxcL0tfYWN5YyAoY2FsKEMpJykiXSxbMiwwLCJEKEUsRnIpIl0sWzIsMSwiRChFJyxGcikiXSxbMCwxLCJQaGkiLDJdLFsyLDMsIksoUGhpfF8oY2FsKEMpKSkiLDJdLFs0LDUsIkJfUGhpIHRpbWVzLm9fRSAoLSkiXSxbMiwwLCJyaG8oY2FsKEMpKSIsMl0sWzMsMSwicmhvKGNhbChDKScpIl0sWzIsNCwiaF9kIl0sWzMsNSwiaF8oZCcpIiwyXV0=
	#align(center, diagram({
		node((-1, 0), [$cal(D)$])
		node((-1, 1), [$cal(D)'$])
		node((0, 0), [$K(cal(C))\/K_acyc (cal(C))$])
		node((0, 1), [$K(cal(C)')\/K_acyc (cal(C)')$])
		node((1, 0), [$D(E,Fr)$])
		node((1, 1), [$D(E',Fr)$])
		edge((-1, 0), (-1, 1), [$Phi$], label-side: right, "->")
		edge((0, 0), (0, 1), [$K(Phi|_(cal(C)))$], label-side: right, "->")
		edge((1, 0), (1, 1), [$B_Phi times.o_E (-)$], label-side: left, "->")
		edge((0, 0), (-1, 0), [$rho(cal(C))$], label-side: right, "->")
		edge((0, 1), (-1, 1), [$rho(cal(C)')$], label-side: left, "->")
		edge((0, 0), (1, 0), [$h_d$], label-side: left, "->")
		edge((0, 1), (1, 1), [$h_(d')$], label-side: right, "->")
	}))
	where $B_Phi=Hom_(cal(C)')(d',Phi(d))$. The left square obviously commutes, and for the right square, it suffices to show the following square commutes: 
	// https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJjYWwoQykiXSxbMCwxLCJjYWwoQyknIl0sWzEsMCwiTW9kXyhFLEZyKSJdLFsxLDEsIk1vZF8oRScsRnIpIl0sWzAsMSwiUGhpfF8oY2FsKEMpKSIsMl0sWzIsMywiQl9QaGkgdGltZXMub19FICgtKSJdLFswLDIsImhfZCJdLFsxLDMsImhfKGQnKSIsMl1d
	#align(center, diagram({
		node((0, 0), [$cal(C)$])
		node((0, 1), [$cal(C)'$])
		node((1, 0), [$Mod_(E,Fr)$])
		node((1, 1), [$Mod_(E',Fr)$])
		edge((0, 0), (0, 1), [$Phi|_(cal(C))$], label-side: right, "->")
		edge((1, 0), (1, 1), [$B_Phi times.o_E (-)$], label-side: left, "->")
		edge((0, 0), (1, 0), [$h_d$], label-side: left, "->")
		edge((0, 1), (1, 1), [$h_(d')$], label-side: right, "->")
	}))
	for this square, note we have a natural transformation 
	$ B_Phi times.o_E (-)=Hom_(cal(C)')(d',Phi(d))times.o_E Hom_(cal(C))(d,-)->Hom_(cal(C)')(d',Phi(-)) $
	via the composition map. It suffices to prove this map is an isomorphism for all $c in cal(C)$. Obviously, it is an isomorphism for $c=d$ hence $d_lambda$ for any $lambda$. By @Lem_Frob_semisimplification, $c_lambda$ is a direct summand of $d_lambda$ in $cal(C)^(Fr#[-]unip)$, hence the above map is an isomorphism for all $c_lambda$. But since $c_lambda$ generates the whole category as in @Lem_Frob_semisimplification, we are done. 
]

Finally, we will also be able to compute the image of the above fully faithful functor. 

#coro[
	The image of the functor $cal(D)inj Mod(E,Fr)$ is the full subcategory generated by the twists of $Hom(d,d_lambda)$s as a triangulated category. 
] <Coro_ess_image_realization>
#proof[
	Obvious. 
]

Another first corollary is the computation of $A$-equivariant derived category over a point, where $A$ is any torus. 

#def[
	Let $A$ be any torus over a finite field. Then we define its $ell$-adic Tate module 
	$ T_ell (A)=lim_(n->oo)A[ell^n] $
	where $A[ell^n]$ is the $ell^n$-torsion points of $A$, and $V_A=T_ell (A)times_(ZZ_ell)overline(QQ)_ell=H_1(A,overline(QQ)_ell)$. By definition, this is a $Fr$-module of weight -2. 

	We then define $check(S)_A=Sym V_A^or$, which is a $overline(QQ)_ell$-algebra with $Fr$-action. We can also define the graded version $check(S)_A^bullet$, where we put $V_A^or$ in degree 2. 
] <Def_Tate_mod_torus>

#rem[
	Notice that the Tate module $T_ell (A)$ is equivalently the pro-$ell$ part of $pi_1^(#[tame])(A)$, since $A[ell^k]$ can be identified as the Galois group of the $ell^k$-th power covering $A->A$. 
]

#coro[
	Take any torus $A$, we have an equivalence of categories 
	$ D_m (BB A)tilde.eq D(check(S)_A,Fr)^omega $
	The pullback functor $D_m (BB A)->D_m (pt)=D(Fr)$ corresponds to the functor $(-)times.o_(check(S)_A)overline(QQ)_ell$ using the natural augmentation of $check(S)_A$. 
] <Coro_torus_equi_shves>
#proof[
	By @Thm_realization, it suffices to verify that $D_m (BB A)$ satisfies the assumptions @Ass_realization. For (1), we simply pick the trivial decomposition. For (2), we take $cal(C)_lambda$ to be the very pure of weight 0 complexes (see @Def_very_pure_complex) such that they are constant over $overline(k)=overline(FF)_q$. Then, the $Ext^i_(D_lambda)(c_1,c_2)$ would be pure of weight $i$ by the same argument as in @Prop_weight_0_ext_weight, whose Frobenius unipotent part obviously vanish. They are clearly stable under taking tensors with unipotent Frobenius modules. 

	For (3), we take $bb(1)_lambda$ to be the constant sheaf. Since the torus $A$ is connected, the space $BB A$ is simply connected, so $D_m (BB A)$ is generated by the object $bb(1)_lambda$, let along the subcategory $cal(C)$ of very pure of weight 0 complexes. By definition, every constant very pure of weight 0 complex is the tensor product of $bb(1)_lambda$ with some complex of Frobenius module $M$. The condition (4) is obvious since there is only 1 stratum. 

	Finally, the essential image of the fully faithful embedding is given by @Coro_ess_image_realization, which is $D(check(S)_A,Fr)^omega$, or equivalently, the smallest triangulated subcategory generated by the constant sheaf. 

	The second assertion follows from the functoriality of $check(S)_A$ by @Thm_realization. 
]

=== Application 1: The equivariant (irreducible) side

In this section, we will consider the properties of the category $D_m (B\\G\/B)$ and its parabolic variant $D_m (P_Theta\\G\/B)$. 

#def[
	For each $overline(w)in[W_Theta\\W]$, we define the following objects in $D_m (P_Theta\\G\/B)$: 
	$ Delta_(overline(w))=i_(overline(w),!)overline(QQ)_ell [ell(overline(w))](ell(overline(w))\/2), #h(1em) nabla_(overline(w))=i_(overline(w),*)overline(QQ)_ell [ell(overline(w))](ell(overline(w))\/2), #h(1em) IC_(overline(w))=i_(overline(w),!*)overline(QQ)_ell [ell(overline(w))](ell(overline(w))\/2) $
	The projection $attach(pi,bl:Theta):Fl->attach(Fl,bl:Theta)$ is proper, so we obtain two pairs of adjunctions 
	// https://q.uiver.app/#r=typst&q=WzAsMixbMCwwLCJEX20gKFBfVGhldGFcXFxcR1xcL0IpIl0sWzIsMCwiRF9tIChCXFxcXEdcXC9CKSJdLFswLDEsImF0dGFjaChwaSxibDpUaGV0YSlfKiJdLFsxLDAsImF0dGFjaChwaSxibDpUaGV0YSleKiIsMix7ImN1cnZlIjozfV0sWzEsMCwiYXR0YWNoKHBpLGJsOlRoZXRhKV4hIiwwLHsiY3VydmUiOi0zfV1d
	#align(center, diagram({
		node((-1, 0), [$D_m (P_Theta\\G\/B)$])
		node((1, 0), [$D_m (B\\G\/B)$])
		edge((-1, 0), (1, 0), [$attach(pi,bl:Theta)_*$], label-side: left, "->")
		edge((1, 0), (-1, 0), [$attach(pi,bl:Theta)^*$], label-side: right, "->", bend: -54deg)
		edge((1, 0), (-1, 0), [$attach(pi,bl:Theta)^!$], label-side: left, "->", bend: 54deg)
		node((0, -0.5), [$bot$])
		node((0, 0.5), [$bot$])
	}))
] <Def_std_costd_irr_equivariant>

We will first investigate the relations between the categories $D_m (P_Theta\\G\/B)$ through the projection $attach(pi,bl:Theta)$. 

#lem[
	For $w in W$, we write $w=u overline(w)$ for $u in W_Theta$ and $overline(w)in[W_Theta\\W]$. Then, we have 
	$ attach(pi,bl:Theta)_*(Delta_w)=Delta_(overline(w))[-ell(u)](-ell(u)\/2),attach(pi,bl:Theta)_*(nabla_w)=nabla_(overline(w))[ell(u)](ell(u)\/2) $
] <Lem_std_costd_push_preserve_shift>
#proof[
	Firstly, notice that the map of cells $Fl_w->attach(Fl,bl:Theta)_overline(w)$ is the projection 
	$ attach(pi,bl:Theta)_w:AA^ell(w)=AA^(ell(u))times AA^(ell(overline(w)))->>AA^(ell(overline(w))) $
	Then, we have the computation 
	$ 
		attach(pi,bl:Theta)_*(Delta_w)=attach(pi,bl:Theta)_!(Delta_w)=&attach(pi,bl:Theta)_!i_(w,!)overline(QQ)_ell [ell(w)](ell(w)\/2) \
		=&i_(overline(w),!)attach(pi,bl:Theta)_(w,!)overline(QQ)_ell [ell(w)](ell(w)\/2) \
		=&i_(overline(w),!)overline(QQ)_ell [ell(w)-2 ell(u)]((ell(w)-2ell(u))\/2) \
		=&(i_(overline(w),!)overline(QQ)_ell [ell(overline(w))](ell(overline(w))\/2))[-ell(u)](-ell(u)\/2) \
		=&Delta_(overline(w))[-ell(u)](-ell(u)\/2)
	$
	The pushforward of $nabla_w$ is computed likewise. 
]

The computation of pushforward of $IC_w$ is much more harder. We postpone this to the later part of this section (@Lem_IC_push). In fact, we can not give a complete characterization of this pushforward, but only a few things on its components. 

#lem[
	We have a natural isomorphism of functors $attach(pi,bl:Theta)^*attach(pi,bl:Theta)_*(-)tilde.eq bb(1)_Theta *_B (-)$. Here, $bb(1)_Theta$ is the constant sheaf on $Fl_(<=w_Theta)$ ($w_Theta$ is the maximal length element in $W_Theta$), so is equivalently $IC_(w_Theta)[-ell_Theta](-ell_Theta\/2)$. 
] <Lem_identify_pull_push_pi>
#proof[
	Firstly note that we have the following Cartesian diagram
	// https://q.uiver.app/#r=typst&q=WzAsNCxbMCwxLCJCXFxcXEciXSxbMSwxLCJQX1RoZXRhXFxcXEciXSxbMSwwLCJCXFxcXEciXSxbMCwwLCIoQl9UaGV0YVxcXFxMX1RoZXRhKSB0aW1lc14oQl9UaGV0YSkoVV9UaGV0YVxcXFxHKSJdLFsyLDEsImF0dGFjaChwaSxibDpUaGV0YSkiXSxbMCwxLCJhdHRhY2gocGksYmw6VGhldGEpIiwyXSxbMywwXSxbMywyXV0=
	#align(center, diagram({
		node((-1, 0), [$B\\G$])
		node((0, 0), [$P_Theta\\G$])
		node((0, -1), [$B\\G$])
		node((-1, -1), [$(B_Theta\\L_Theta) times^(B_Theta)(U_Theta\\G)$])
		edge((0, -1), (0, 0), [$attach(pi,bl:Theta)$], label-side: left, "->")
		edge((-1, 0), (0, 0), [$attach(pi,bl:Theta)$], label-side: right, "->")
		edge((-1, -1), (-1, 0), [$p_2$], "->")
		edge((-1, -1), (0, -1), [$m$], "->")
		node((-0.9, -0.7), [$Cartmark$])
	}))
	This square is Cartesian because we can explicitly construct a map 
	$ (B_Theta\\L_Theta)times^(B_Theta)(U_Theta\\G)->(B\\G)times_(P_Theta\\G)(B\\G), (B_Theta l, U_Theta g)mapsto (B l g,B g) $
	and this is an isomorphism by the decomposition $B=U_Theta B_Theta$, and hence we have an inverse map $(B g_1,B g_2)mapsto(B_Theta l, U_Theta g_2)$, where $l$ is the unique element such that $B g_1=B l g_2$. 

	By the proper base change along the Cartesian diagram, we have $attach(pi,bl:Theta)^*attach(pi,bl:Theta)_*(-)tilde.eq m_*p_2^*(-)$. Then, in the coordinates $(B_Theta\\L_Theta)times^(B_Theta)(U_Theta\\G)$, we can write $p_2^*(cal(F))=bb(1)_Theta times.square^(B_Theta) cal(F)$, where $B_Theta\\L_Theta$ is identified as $attach(pi,bl:Theta)^(-1)(P_Theta\\P_Theta)subset B\\G$. Finally, $m_*(bb(1)_Theta times.square^(B_Theta)cal(F))=bb(1)_Theta *_B cal(F)$, because 
	$ (B_Theta\\L_Theta)times^(B_Theta)(U_Theta\\G)=(B_Theta\\L_Theta)times^B G=attach(pi,bl:Theta)^(-1)(P_Theta\\P_Theta)times^B G subset Fl times^B G $
]

#def[
	Besides the tensor product, there is a convolution product on $D_m (B\\G\/B)$, given by the diagram 
	$ B\\G\/B times B\\G\/B<-^delta B\\ G times^B G \/B->^m B\\G\/B $
	where $delta$ sends $(g_1,g_2)$ to $(g_1,g_2)$ is well-defined, since the middle quotient splits into 2 quotients. We then define $cal(F)_1*_B cal(F)_2=m_!delta^*(cal(F)_1 times.square cal(F)_2)$. Note that here $m$ is ind-proper and $delta$ is a quotient by $B$ hence smooth. 
] <Def_convolution_equivariant>

#lem[
	If $u,v in W$ is such that $ell(u)+ell(v)=ell(u v)$, then 
	$ Delta_u *_B Delta_v=Delta_(u v),#h(1em)nabla_u*_B nabla_v=nabla_(u v) $
] <Lem_convolution_std_costd_add>
#proof[
	Follows from that $Fl_u times^B Fl_v->Fl_(u v)$ is an isomorphism. 
]

#prop[
	For $cal(F)_1,cal(F)_2 in D_m (B\\G\/B)$ very pure of weight 0, we have $cal(F)_1 *_B cal(F)_2$ very pure of weight 0. 
] <Prop_very_pure_wt_0_closed_convolution>
#proof[
	Note that the category of very pure complexes of weight 0 is 
	$ bracket(#[$Delta_w|w in W$])inter bracket(#[$nabla_w|w in W$]) $
	where $bracket(-)$ denote the additive category generated by some objects under extensions. Then, we have 
	$ Delta_u*_B Delta_v in bracket(#[$Delta_w bracket(<=0)|w in W$]) $
	and 
	$ nabla_u*_B nabla_v in bracket(#[$nabla_w bracket(>=0)|w in W$]) $
	by writing the standard and costandard sheaves into convolutions of standard and costandard sheaves associated to simple reflections using @Lem_convolution_std_costd_add. The convolution $Delta_s *_B Delta_s$ is a very classical computation using excision on $PP^1$, and we invite the readers not familiar with the result to compute it by themselves. 

	Thus, we have 
	$ cal(F)_1 *_B cal(F)_2 in bracket(#[$Delta_w bracket(<=0)|w in W$])inter bracket(#[$nabla_w bracket(>=0)|w in W$]) $
	which implies $cal(F)_1*_B cal(F)_2$ is pure of weight 0. Hence by @Lem_equi_pure_equiv_very_pure, it is very pure of weight 0. 
]

#def[
	Let $X=product.co X_lambda$ be a stratified scheme, and suppose $cal(F) in D_m (X)$ is constructible with respect to the stratification. Then, let $i_lambda:X_lambda inj X$ denote the embeddings, we say $cal(F)$ is $*$-pure or $!$-pure of weight $n$ if for each $lambda$ and each $m in ZZ$, we have $H^m (i_lambda^* (cal(F)))$ or $H^m (i_lambda^! (cal(F)))$ is a sheaf pointwise pure of weight $m+n$. We say $cal(F)$ is very pure of weight 0 if it is both $!$-pure and $*$-pure of weight 0. 
] <Def_very_pure_complex>

#lem[
	Let $V$ be a variety over $k$, equipped with a $GG_m$-action contracting $V$ to a point $v in V$. Then, we have for any complex of $GG_m$-equivariant constructible $ell$-adic sheaf $cal(F)$, the cohomology $H^*(V,cal(F))=cal(F)_v$. 
] <Lem_one_contr_point_coh_equal_stalk>
#proof[
	By the spectral sequence computing the hypercohomology, it suffices to prove that for any $GG_m$-equivariant $ell$-adic sheaf $cal(F)$, the cohomology $H^*(V,cal(F))=cal(F)_v$ (in particular, the higher cohomologies vanishes). Then, by replacing $cal(F)=ker(cal(F)->v_* v^* cal(F))$, we may assume $cal(F)_v=0$. We now prove $cal(F)$ has trivial cohomology. 
	
	We denote $mu:GG_m times V->V$, and extend $mu$ naturally to $mu:AA^1 times V->V$, where $(0,u)mapsto v$ for any $u in V$. Then, consider the shearing map $tau:AA^1 times V ->AA^1 times V$, which sends $(t,u)mapsto (t,mu(t,u))$. Note that $tau$ is an $AA^1$-morphism, where $AA^1 times V$ is equipped with the $AA^1$-scheme structure by the map $pi_1:AA^1 times V->AA^1$. 

	Since $cal(F)$ is $GG_m$-equivariant, we have $pi_2^*(cal(F))|_(GG_m times V)=tau^*pi_2^*(cal(F))|_(GG_m times V)$. Then, $tau^*pi_2^*(cal(F))|_(0 times V)=0$ by assumption, so if we let $j:GG_m times V inj AA^1 times V$ denote the inclusion, we have 
	$ tau^*pi_2^*(cal(F))=i_!i^*pi_2^*(cal(F)) $
	Applying the counit $i_!i^*->id$ and the derived projection to $AA^1$, we obtain a map 
	$ alpha:pi_(1,*)tau^*pi_2^*(cal(F))->pi_(1,*)pi_2^*(cal(F)) $
	On the other hand, since we have the commutative triangle 
	// https://q.uiver.app/#r=typst&q=WzAsMyxbMCwwLCJBQV4xIHRpbWVzIFYiXSxbMiwwLCJBQV4xIHRpbWVzIFYiXSxbMSwxLCJWIl0sWzAsMiwicGlfMSIsMl0sWzAsMSwidGF1Il0sWzEsMiwicGlfMSJdXQ==
	#align(center, diagram({
		node((-1, 0), [$AA^1 times V$])
		node((1, 0), [$AA^1 times V$])
		node((0, 1), [$V$])
		edge((-1, 0), (0, 1), [$pi_1$], 	label-side: right, "->")
		edge((-1, 0), (1, 0), [$tau$], label-side: left, "->")
		edge((1, 0), (0, 1), [$pi_1$], label-side: left, "->")
	}))
	we have a natural transformation $pi_(1,*)->pi_(1,*)tau^*$ given by $pi_(1,*)=pi_(1,*)tau_*$, so 
	$ pi_(1,*)->^eta pi_(1,*)tau_*tau^*->^tilde.eq pi_(1,*)tau^* $
	Applying this to $pi_2^*(cal(F))$, we obtain a map 
	$ beta:pi_(1,*)pi_2^*(cal(F))->pi_(1,*)tau^*pi_2^*(cal(F)) $
	Notice that $pi_(1,*)pi_2^*(cal(F))$ is the constant sheaf with values $pi_(2,*)(cal(F))$ by smooth base change. Also, note the stalk of $alpha compose beta$ at $1in AA^1$ is bijective, and the stalk of this map at $0$ is 0. Since it is a constant sheaf, it must be 0 everywhere. 
]

#lem[
	Suppose $cal(F)in D_m (P_Theta\\G\/B)$ is pure of weight 0. Then it is very pure of weight 0. 
] <Lem_equi_pure_equiv_very_pure>
#proof[
	Firstly, we may assume $Theta=nothing$, because the projection $attach(pi,bl:Theta)$ is smooth and $attach(pi,bl:Theta)^*$ preserves weights. By definition, we have for any $x in B\\G\/B$, the $*$-stalk $x^*(cal(F))$ having weight $<=0$. So it suffices to prove that the $*$-stalks have weights $>=0$. For this, we think $cal(F)$ as an equivariant sheaf over $Fl$, and first assume $Supp cal(F) subset Fl_(<=w)$. Consider $v<=w$, and we abuse notations to let $v=v B\/B in Fl$. Then, it suffices to prove $v^*(cal(F))$ has weight $>=0$ for all $v$, since they are representatives of all the orbits. But this is because 
	$ v^*(cal(F))=H^*(v C inter Fl_(<=w),cal(F)) $
	by @Lem_big_cell_contracts_Weyl_grp and @Lem_one_contr_point_coh_equal_stalk. Then, since $H^*$ is the $*$-pushforward to the point, it increases weight, so $v^*(cal(F))$ has weight $>=0$. Hence the assertion follows. 
]

#prop[
	If $cal(F)_1 in D_m (B\\G\/B)$ is $*$-pure of weight 0, and $cal(F)_2 in D_m (B\\G\/B)$ is $!$-pure of weight 0, then $Ext^i (cal(F)_1,cal(F)_2)$ is a Frobenius module of weight $i$, and it is free over the left or right copy of the graded algebra $check(S)^bullet$. Here, the $check(S)^bullet$ bimodule structure is given by the action 
	$ D_m (H\\pt\/H) lact D_m (B\\G\/B) $
] <Prop_weight_0_ext_weight>
#proof[
	We apply induction on the support of $cal(F)_1$ and $cal(F)_2$. Suppose the statement is true for $cal(F)_1$ and $cal(F)_2$ supported on $Fl_(<w)$. Then, suppose now they are supported on $Fl_(<=w)$, consider the excision triangle 
	$ i_(<w,!)i_(<w)^!(cal(F)_2)->cal(F)_2->i_(w,*)i_w^*(cal(F)_2) $
	and applying $Hom(cal(F)_1,-)$, we obtain a long exact sequence 
	$ dots.c->Ext^i (i_(<w)^*(cal(F)_1),i_(<w)^!(cal(F)_2))->Ext^i (cal(F)_1,cal(F)_2)->Ext^i (i_w^*(cal(F)_1),i_w^*(cal(F)_2))->dots.c $
	Now, note $i_w$ is open, and by assumption $i_w^*(cal(F)_1)$ and $i_w^*(cal(F)_2)=i_w^!(cal(F)_2)$ are both pure of weight 0. We now prove that we have $Ext^i (i_w^*(cal(F)_1),i_w^*(cal(F)_2))$ pure of weight $i$. Firstly, we write $cal(G)_i=i_w^*(cal(F)_i)$. Then, since $cal(G)_i in D_m (B\\B w B\/B)=D_m (B\\Fl_w)$, we have the stabilizer of the actino $B lact Fl_w$ given by $B_w = B inter w B w^(-1)$, which is constant. Thus, the underlying sheaf of $cal(G)_i$ in $D_m (Fl_w)$ is constant. We may assume $cal(G)_i=cal(L)_w times.o M_i$ non-canonically, where $cal(L)_w=overline(QQ)_ell [d](d\/2)$ is the constant sheaf on the strata and $M_i$ is a Frobenius module pure of weight 0. Moreover, we may assume $M_i$ is dualizable. Hence, we have the following computation 
	$ Hom^bullet (cal(G)_1,cal(G)_2)=Hom^bullet (cal(L)_w,cal(L)_w times.o M_2 times.o M_1^or)=H^bullet (B\\Fl_w)times.o Hom^bullet (M_1,M_2) $
	Now, by definition, $Ext^i (M_1,M_2)$ is pure of weight $i$, and since $B\\Fl_w$ is equivalent to $BB H$ for the torus $H subset G$, $H^i (B\\Fl_w)=H^i (BB H)$ is also pure of weight $i$. Hence, taking tensor products gives the desired purity result. 

	On the other hand, $Ext^i (i_(<w)^*(cal(F)_1),i_(<w)^!(cal(F)_2))$ is pure of weight $i$ by induction hypothesis. Then, since we have an actual map of Frobenius modules 
	$ Ext^i (i_w^*(cal(F)_1),i_w^*(cal(F)_2))->Ext^(i+1)(i_(<w)^*(cal(F)_1),i_(<w)^!(cal(F)_2)) $
	by weight reasons, it must be 0. Hence, the long exact sequence splits into short exact sequences 
	$ 0->Ext^i (i_(<w)^*(cal(F)_1),i_(<w)^!(cal(F)_2))->Ext^i (cal(F)_1,cal(F)_2)->Ext^i (i_w^*(cal(F)_1),i_w^*(cal(F)_2))->0 $
	so $Ext^i (cal(F)_1,cal(F)_2)$ is pure of weight $i$. Then, it remains to prove $Ext^bullet (i_w^*(cal(F)_1),i_w^*(cal(F)_2))$ is free both as a left $check(S)^bullet$-module and as a right $check(S)^bullet$-module. This is also by the computation above, since by definition $H^bullet (B\\Fl_w)=H^bullet (BB H)$. 
]

Then we will introduce the hypercohomology functor for the convenience for certain computations. 

#def[
	By identifying $B\\G\/B=H\\(U\\G\/U)\/H$, we can project $U\\G\/U$ to a point, and obtain the equivariant cohomology functor 
	$ Gamma_(H times H)(U\\G\/U,-):D_m (B\\G\/B)->D_m (BB(H times H))=D(check(S)times.o check(S),Fr)^omega $
	where $check(S)=check(S)_H$. We denote this functor by $HH$. 
] <Def_equi_coh>

#lem[
	The functor $HH$ has a natural monoidal structure with respect to the convolution on $D_m (B\\G\/B)$ and the tensor product $-times.o_(check(S))-$ on $D(check(S)times.o check(S),Fr)^omega$. 
] <Lem_equi_coh_monoidal>
#proof[
	It suffices to prove that the tensor product $-times.o_(check(S))-$ on $D(check(S)times check(S),Fr)^omega$ is the same as the following pull-push: 
	$ H\\pt\/H times H\\pt\/H<--^(delta_H)H\\pt times^H pt\/H-->^(m_H)H\\pt\/H $
	then, clearly the convolutions (here we use $m_*delta^*$, which makes no difference on $D_m (B\\G\/B)$ by ind-properness) on the corresponding diagrams commutes with the usual pushforward functor $pi_*:D_m (B\\G\/B)->D_m (H\\pt\/H)$ (essentially by smooth base change and ignoring trivial unipotent actions). 

	On the level of derived categories, we have the following identifications: 
	// https://q.uiver.app/#r=typst&q=WzAsNixbMCwwLCJEX20gKEhcXFxccHRcXC9IIHRpbWVzIEhcXFxccHRcXC9IKSJdLFswLDEsIkQoY2hlY2soUyleKHRpbWVzLm8gNCksRnIpIl0sWzEsMCwiRF9tIChIXFxcXHB0IHRpbWVzXkggcHRcXC9IKSJdLFsxLDEsIkQoY2hlY2soUyleKHRpbWVzLm8gMyksRnIpIl0sWzIsMCwiRF9tIChIXFxcXHB0XFwvSCkiXSxbMiwxLCJEKGNoZWNrKFMpIHRpbWVzLm8gY2hlY2soUyksRnIpIl0sWzAsMiwiZGVsdGFfSF4qIl0sWzIsNCwibV8oSCwhKSJdLFsxLDMsIkYiXSxbMyw1LCJVIl0sWzAsMSwidGlsZGUuZXEiLDJdLFsyLDMsInRpbGRlLmVxIiwyXSxbNCw1LCJ0aWxkZS5lcSJdXQ==
	#align(center, diagram({
		node((-1, 0), [$D_m (H\\pt\/H times H\\pt\/H)$])
		node((-1, 1), [$D(check(S)^(times.o 4),Fr)$])
		node((0, 0), [$D_m (H\\pt times^H pt\/H)$])
		node((0, 1), [$D(check(S)^(times.o 3),Fr)$])
		node((1, 0), [$D_m (H\\pt\/H)$])
		node((1, 1), [$D(check(S) times.o check(S),Fr)$])
		edge((-1, 0), (0, 0), [$delta_H^*$], label-side: left, "->")
		edge((0, 0), (1, 0), [$m_(H,*)$], label-side: left, "->")
		edge((-1, 1), (0, 1), [$F$], label-side: left, "->")
		edge((0, 1), (1, 1), [$U$], label-side: left, "->")
		edge((-1, 0), (-1, 1), [$tilde.eq$], label-side: right, "->")
		edge((0, 0), (0, 1), [$tilde.eq$], label-side: right, "->")
		edge((1, 0), (1, 1), [$tilde.eq$], label-side: left, "->")
	}))
	Here, by @Coro_torus_equi_shves $F$ is $-times.o_(check(S)times.o check(S))check(S)$, where the bottom $check(S)times.o check(S)$ is the two in the middle. The question now is what is $U$. We claim that this is forgetting the middle $check(S)$-action, hence identifying $U compose F$ as the tensor product. 

	We first identify the functor $pi_*:D_m (BB A)->D_m (pt)$. While identifying $D_m (BB A)$ with $D(check(S)_A,Fr)$, we used the functor $Hom(bb(1),-)$, which is precisely taking the cohomology. Thus $pi_*$ is simply the forgetful functor $D(check(S)_A,Fr)->D(Fr)$. Hence in the above case, this is also the forgetful functor, but only forgetting the middle factor by the Künneth formula. 
]

#lem[
	For $cal(F)in D_m (B\\overline(B w B)\/B)$ $*$-pure or $!$-pure of weight 0, we have exact sequences 
	$ 0-->HH(j_!j^!cal(F))-->HH(cal(F))-->HH(i_*i^*(cal(F)))-->0 $
	$ 0-->HH(i_!i^!cal(F))-->HH(cal(F))-->HH(j_*j^*(cal(F)))-->0 $
	here $i:B\\Fl_(<w)inj B\\Fl_(<=w)$, and $j:B\\Fl_w inj B\\Fl_(<=w)$ are the closed and open part. We temporarily denote them by $i:Z inj X$ and $j:U inj X$. 
] <Lem_equi_coh_exact_seq_pure>
#proof[
	It suffices to prove the statements for the second exact sequence, since the others follows from taking Verdier duality. For $cal(F)$ $!$-pure of weight 0, this case follows from @Prop_weight_0_ext_weight and weight reasons. 

	Now, for $cal(F)$ $*$-pure of weight 0, suppose $cal(F)=i_(<=v)^*cal(K)$. By the long exact sequence, it suffices to show that $j^*:H^bullet (X,cal(F))->H^bullet (U,cal(F))$ is degreewise surjective. Let $v_H$ denote the inclusion of stacks $v_H:H\\v inj H\\Fl$. By $AA^1$-invariance, we have an isomorphism of cohomology groups 
	$ H^bullet (B\\Fl_G,cal(K))tilde.eq H^bullet (H\\Fl_G,cal(K)) $
	Then, one has a commutative diagram 
	// https://q.uiver.app/#r=typst&q=WzAsNyxbMCwwLCJIXmJ1bGxldCAoQlxcXFxGbCxjYWwoSykpIl0sWzAsMSwiSF5idWxsZXQgKEhcXFxcRmwsY2FsKEspKSJdLFsxLDAsIkheYnVsbGV0IChYLGNhbChGKSkiXSxbMiwwLCJIXmJ1bGxldCAoVSxjYWwoRikpIl0sWzMsMCwiSF5idWxsZXQgdl9IXipjYWwoRikiXSxbMywxLCJIXmJ1bGxldCB2X0heKiBjYWwoRikiXSxbMiwxLCJIXmJ1bGxldCAoSFxcXFx2IEMsY2FsKEspKSJdLFswLDEsIiIsMCx7ImxldmVsIjoyLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzQsNSwiIiwwLHsibGV2ZWwiOjIsInN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbMyw0LCIiLDAseyJsZXZlbCI6Miwic3R5bGUiOnsiaGVhZCI6eyJuYW1lIjoibm9uZSJ9fX1dLFs2LDUsIiIsMix7ImxldmVsIjoyLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzEsNiwiYWxwaGEiXSxbMCwyXSxbMiwzLCJiZXRhIl1d
	#align(center, diagram({
		node((-2, 0), [$H^bullet (B\\Fl,cal(K))$])
		node((-2, 1), [$H^bullet (H\\Fl,cal(K))$])
		node((-1, 0), [$H^bullet (X,cal(F))$])
		node((0, 0), [$H^bullet (U,cal(F))$])
		node((1, 0), [$H^bullet v_H^*cal(F)$])
		node((1, 1), [$H^bullet v_H^* cal(F)$])
		node((0, 1), [$H^bullet (H\\v C,cal(K))$])
		edge((-2, 0), (-2, 1), "=")
		edge((1, 0), (1, 1), "=")
		edge((0, 0), (1, 0), "=")
		edge((0, 1), (1, 1), "=")
		edge((-2, 1), (0, 1), [$alpha^*$], label-side: left, "->")
		edge((-2, 0), (-1, 0), "->")
		edge((-1, 0), (0, 0), [$j^*$], label-side: left, "->")
	}))
	Here, the rightmost horizontal arrows are taking stalks at the contraction point, so by @Lem_one_contr_point_coh_equal_stalk is an isomorphism. Now, to prove $j^*$ surjective, it suffices to prove $alpha^*$ surjective, where $alpha:H\\v C inj H\\Fl$ is an open immersion of stacks. We take $beta$ to be the reduced complement closed of $alpha$, we have 
	$ dots.c-->H^k (H\\Fl,cal(K))-->H^k (H\\v C,cal(K))-->H^(k+1)(H\\(Fl-v C),beta^!cal(K))-->dots.c $
	Note that we may assume $cal(K)$ is pure of weight 0. Hence, $beta^!(cal(K))$ is of weight $>=0$. Thus, the $Fr$-module $H^(k+1)(H\\(Fl-v C),beta^!cal(K))$ is of weight $>=k+1$. On the other hand, as a $Fr$-module we have $H^k (H\\v C,cal(K))=H^k (v_H^*(cal(K)))$, so this group has weight $k$. Hence the connecting morphism is 0, so we obtain the surjectivity of $alpha^*$. 
]

The main evidence that $HH$ is useful for detecting data in $D_m (B\\G\/B)$ is given by the following proposition. 

#prop[
	For $cal(F)_1,cal(F)_2 in D_m (B\\G\/B)$ very pure of weight 0, the natural map 
	$ Ext^bullet (cal(F)_1,cal(F)_2)->Hom_(check(S)times.o check(S))(HH(cal(F)_1),HH(cal(F)_2)) $
	is an isomorphism of $Fr$-modules. 
] <Prop_equi_coh_fully_faithful_wt_0>
#proof[
	We first prove that for $cal(F)_1,cal(F)_2 in D_m (B\\G\/B)$ supported on $B\\overline(B w B)\/B$ very pure of weight 0, we have $Hom^bullet (cal(F)_1,cal(F)_2)tilde.eq Hom^bullet_(A_(<=w))(HH(cal(F)_1),HH(cal(F)_2))$. Here $A_(<=w):=H^bullet (B\\Fl_(<=w))$. We apply induction on the Bruhat order, and prove that for any $v$, we have 
	$ Hom^bullet (i_(<=v,*)i_(<=v)^*(cal(F)_1),i_(<=v,*)i_(<=v)^!(cal(F)_2))tilde.eq Hom_(A_(<=v))(HH(i_(<=v,*)i_(<=v)^*(cal(F)_1)),HH(i_(<=v,*)i_(<=v)^!(cal(F)_2))) $
	The assertion for $v=e$ is trivial. Then, for the induction step, we should apply @Lem_equi_coh_exact_seq_pure. We claim that we have a morphism of exact sequences 
	// https://q.uiver.app/#r=typst&q=WzAsMTAsWzAsMCwiMCJdLFswLDQsIjAiXSxbMSwwLCIwIl0sWzEsNCwiMCJdLFswLDEsIkhvbV5idWxsZXQgKGlfKmleKihjYWwoRilfMSksaV8qaV4hKGNhbChGKV8yKSkiXSxbMCwyLCJIb21eYnVsbGV0IChjYWwoRilfMSxjYWwoRilfMikiXSxbMCwzLCJIb21eYnVsbGV0IChqXypqXiooY2FsKEYpXzEpLGpfKmpeKihjYWwoRilfMikpIl0sWzEsMSwiSG9tXyhBXyg8dikpKEhIKGlfKmleKihjYWwoRilfMSkpLEhIKGlfKmleIShjYWwoRilfMikpKSJdLFsxLDIsIkhvbV8oQV8oPD12KSkoSEgoY2FsKEYpXzEpLEhIKGNhbChGKV8yKSkiXSxbMSwzLCJIb21fKEheYnVsbGV0IChVKSkoSEgoal8qal4qKGNhbChGKV8xKSksSEgoal8qal4qKGNhbChGKV8yKSkpIl0sWzAsNF0sWzQsNV0sWzUsNl0sWzYsMV0sWzIsN10sWzcsOF0sWzgsOV0sWzksM10sWzYsOV0sWzUsOF0sWzQsN11d
	#align(center, diagram({
		node((-1, -2), [$0$])
		node((-1, 2), [$0$])
		node((0, -2), [$0$])
		node((0, 2), [$0$])
		node((-1, -1), [$Hom^bullet (i_*i^*(cal(F)_1),i_*i^!(cal(F)_2))$])
		node((-1, 0), [$Hom^bullet (cal(F)_1,cal(F)_2)$])
		node((-1, 1), [$Hom^bullet (j_*j^*(cal(F)_1),j_*j^*(cal(F)_2))$])
		node((0, -1), [$Hom_(A_(<v))(HH(i_*i^*(cal(F)_1)),HH(i_*i^!(cal(F)_2)))$])
		node((0, 0), [$Hom_(A_(<=v))(HH(cal(F)_1),HH(cal(F)_2))$])
		node((0, 1), [$Hom_(H^bullet (U))(HH(j_*j^*(cal(F)_1)),HH(j_*j^*(cal(F)_2)))$])
		edge((-1, -2), (-1, -1), "->")
		edge((-1, -1), (-1, 0), "->")
		edge((-1, 0), (-1, 1), "->")
		edge((-1, 1), (-1, 2), "->")
		edge((0, -2), (0, -1), "->")
		edge((0, -1), (0, 0), "->")
		edge((0, 0), (0, 1), "->")
		edge((0, 1), (0, 2), "->")
		edge((-1, 1), (0, 1), "->")
		edge((-1, 0), (0, 0), "->")
		edge((-1, -1), (0, -1), "->")
	}))
	Now, we know that the left line is an exact sequence, the right line is exact at top and bottom, and that the top and bottom horizontal arrows are isomorphisms, either by the induction hypothesis or by the computation on the case of a torus (note $U=B\\B w B\/B tilde.eq H\\pt$ up to factors of $AA^1$'s). Now, it suffices to prove that the right line is exact in the middle, so we can finish the induction step. 

	Firstly, note that we have an exact sequence 
	$ 0-->H_c^bullet (U)-->A_(<=v)-->A_(<v)-->0 $
	By the above equivalence, $H^bullet (U)$ is a free $check(S)$-module of rank 1, so we may choose a generator $[U] in H_c^(2 ell(v))(U)$. Then, the action of $[U]$ on $HH(cal(F)_i)$ would then kill the closed part, hence factors as 
	$ HH(cal(F)_i)surj HH(j_*j^*(cal(F)_i))->^u HH(j_!j^*(cal(F)_i))[2ell(v)](ell(v))inj HH(cal(F)_i)[2ell(v)](ell(v)) $
	Now, suppose there is some $phi:HH(cal(F)_1)->HH(cal(F))_2$ induces the zero map $HH(j_*j^*(cal(F)_1))->HH(j_*j^*(cal(F)_2))$, then we have $[U]compose phi=0$ by the above factoring. Hence, $phi compose [U]=0$ since $phi$ is an $A_(<=v)$-module map. Thus $phi=0$ on the image of $[U]$, which is $HH(j_!j^*(cal(F)_1))$. Thus it comes from an $A_(<v)$-module map $HH(i_*i^*(cal(F)_1))->HH(i_*i^!(cal(F)_2))$, hence the claim follows. 
] 

Then, we can compute the equivariant cohomology of the standard, costandard, and intersection cohomology sheaves. 

#lem[
	For each $w in W$, we have an isomorphism in $Mod^gr_(check(S)^bullet times.o check(S)^bullet,Fr)$
	$ HH(Delta_w)=cal(O)_(Gamma(w))[-ell(w)](-ell(w)\/2) $
	$ HH(nabla_w)=cal(O)_(Gamma(w))[ell(w)](ell(w)\/2) $
	Here, $Gamma(w)subset V_H times V_H=Spec check(S)times.o check(S)$ is the graph of the map $w:V_H->V_H$, given by the action $W lact V_H$. 
] <Lem_equi_coh_std_costd>
#proof[
	Note that the projection $B\\G\/B->pt$ is ind-proper, so the hypercohomologies in question are actually given by 
	$ HH(Delta_w)[-ell(w)](-ell(w)\/2)=H^bullet_c (B\\B w B\/B,overline(QQ)_ell), #h(1em) HH(nabla_w)[ell(w)](ell(w)\/2)=H^bullet (B\\B w B\/B, overline(QQ)_ell) $
	We first compute the cohomology of the costandard object. Notice that by @Lem_one_contr_point_coh_equal_stalk we have an isomorphism $H^bullet (B\\B w B\/B,overline(QQ)_ell)=H^bullet (H\\H w H\/H,overline(QQ)_ell)$. We then suffices to identify it with the ring of functions over $cal(O)_(Gamma(w))$. Note the $H times H$-action on $H w H$ is given by $(h_1,h_2)dot x=h_1 x h_2^(-1)$, so the stabilizer is given by $K_w={(w h w^(-1),h)|h in H}$. Thus, we can furthermore identify the stack $H\\H w H\/H=BB K_w$. However, by the identifying $K_w$ with $H$, we have $H tilde.eq K_w inj H times H$ induces $V_H inj V_H times V_H$, $v mapsto (w v,v)$ on the level of Tate modules, hence its image is precisely $Gamma(w)$. Hence the claim for the second part follows. 

	For the first part, note that 
	$ H^bullet_c (B\\B w B\/B, overline(QQ)_ell)=H^bullet (H\\H w H\/H, iota^! overline(QQ)_ell) $
	where $iota:H\\H w H\/H inj B\\B w B\/B$ is the inclusion of the left $H$-contraction point, and by @Lem_one_contr_point_coh_equal_stalk, we have $H^bullet (-)=iota^*(-)$, so by taking Verdier dual $H^bullet_c (-)=iota^!(-)$. This time, by purity for the section of an affine bundle, we have $iota^!overline(QQ)_ell=overline(QQ)_ell [-2ell(w)](-ell(w))$. Hence the conclusion follows. 
]
#rem[
	The cohomologies are actually isomorphism to each other if we forget the Tate twists, cohomological grading, and $X_*(H)$-gradings. Indeed, we have $cal(O)_(Gamma(w))=cal(O)_(V_H)$ regarded as a plain $check(S)$-module. 

	The cohomologies of $IC_w$'s are much more interesting. They can be described as the algebra of functions over a union of the orbits, which gives a algebro-geometric description of Soergel bimodules. For example, it is well-known that in the case $G=SL_2$, $HH(IC_s)$ is the Soergel bimodule $check(S)times.o_(check(S)^s)check(S)$. This can be interpreted by definition as $cal(O)(Gamma(e)union Gamma(s))[1](1\/2)$. 
]

#lem[
	For $w in W$, we have $HH_w:=HH(IC_w)$ is a direct sum of $Fr$-modules $overline(QQ)_ell [n](n\/2)$ for $n equiv ell(w)(mod 2)$. 
] <Lem_IC_coh_parity>
#proof[
	For the case where $w$ is a simple reflection, it follows from the computation of $SL_2$. In general, take a reduced word presentation $w=s_i_1 dot dots.c dot s_i_m$, and we claim
	$ IC_w subset IC_s_i_1 *_B dots.c *_B IC_s_i_n $
	is a direct summand. Note
	$ End(IC_s_i_1*_B dots.c*_B IC_s_i_n)subset End_(check(S)times.o check(S))(HH_s_i_1 times.o_(check(S))dots.c times.o_(check(S))HH_s_i_n) $
	is the 0-th graded direct summand and the latter is Frobenius semisimple since it is an endomorphism $Fr$-module of a semisimple $Fr$-module, and by @Cor_End_semisimple_Fr_semisimple $IC_w times.o M_w$ would be a direct summand. However $M_w$ must be $overline(QQ)_ell$ by counting the dimension of $H^(ell(w))(-)$. So $IC_w$ is indeed a direct summand. 

	Hence $HH_w$ is a direct summand of $HH_s_i_1 times.o_(check(S))dots.c times.o_(check(S))HH_s_i_n$, and in the latter, only $overline(QQ)_ell [n](n\/2)$ appears for $n equiv ell(w)(mod 2)$
]
#rem[
	I believe the proof using Bott-Samuelson resolutions is also available. 
]

#lem[
	For $w_1,w_2 in W$, the convolution $IC_w_1*_B IC_w_2$ is a direct sum of $IC_w [n](n\/2)$'s where $n equiv ell(w)-ell(w_1)-ell(w_2)(mod 2)$. In particular, if $ell(w)_1+ell(w_2)=ell(2)$, then $IC_w$ appears with multiplicity 1. 
] <Lem_IC_convolution>
#proof[
	Let $cal(F)=IC_w_1*_B IC_w_2$. Again, we have
	$ End(cal(F))subset End_(check(S)times.o check(S))(HH_w_1 times.o_(check(S))HH_w_2) $ 
	is the 0-th graded direct summand. Hence $cal(F)$ decomposes into $IC_w times.o M_w$ for $Fr$-semisimple modules. Then, we have $HH(cal(F))=HH_w_1 times.o_(check(S))HH_w_2$ is a direct sum of $HH_w times.o M_w$. Hence by @Lem_IC_coh_parity, we can compute $M_w$ and see that it is a direct sum of $overline(QQ)_ell [n](n\/2)$ with the desired parity. 

	In the case $ell(w_1)+ell(w_2)=ell(w)$, the map $overline(B w_1 B)times^B overline(B w_2 B)->overline(B w B)$ is birational, hence the multiplicity 1 follows. 
]

#lem[
	For $w in W$, the complex $attach(pi,bl:Theta)_*(IC_w)$ is a direct sum of $IC_(overline(v))[n](n\/2)$ with $n equiv ell(overline(w))-ell(overline(v))(mod 2)$. In particular, if $w in [W_Theta\\W]$, we have $IC_(overline(w))$ a direct summand of $attach(pi,bl:Theta)_*(IC_w)$ with multiplicity 1. 
] <Lem_IC_push>
#proof[
	Again we compute the endomorphism algebra 
	$ End_(D_m (P_Theta\\G\/B))(attach(pi,bl:Theta)_*(IC_w))tilde.eq Hom_(D_m (B\\G\/B))(bb(1)_Theta*_B IC_w,IC_w) $
	and the latter is again Frobenius semisimple by applying $HH$. Hence $attach(pi,bl:Theta)_*(IC_w)$ is a direct sum of $IC_overline(v) times.o M_(overline(v))$, hence $attach(pi,bl:Theta)^*attach(pi,bl:Theta)_*(IC_w)=bb(1)_Theta *_B IC_w$ is a direct sum of $attach(pi,bl:Theta)^*(IC_overline(v))times.o M_(overline(v))$. Applying $HH$ and again use @Lem_IC_coh_parity we have the statement for the parity. The multiplicity 1 again follows from birationality. 
]

Finally, we show that we can apply @Thm_realization to give a computation of $D_m (B\\G\/B)$, but we will postpone the actual computation to later parts. 

#prop[
	Suppose $X$ is any scheme with an action of a reductive group $G$ having finitely many orbits $X_lambda$. Moreover, assume each orbit inclusion $X_lambda inj X$ is affine. Then, the category $D_m (G\\X)$ satisfies @Ass_realization. 
] <Prop_fin_strat_has_realization>
#proof[
	+	The finite poset is given by $Lambda$, with the order given by taking boundaries. Each strata is given by $cal(D)_lambda=D_m (G\\X_lambda)$. 
	+	For each $D_m (G\\X_lambda)$, we take $cal(C)_lambda$ to be the subcategory of constant pure of weight 0 complexes. Thus by a similar argument as @Prop_weight_0_ext_weight, the Frobenius unipotent part of the higher $Ext$ groups vanish. 
	+	We can take $bb(1)_lambda$ to be the constant sheaf, and since $cal(C)_lambda$ consists of constant complexes, every $c in cal(C)_lambda$ is of the form $bb(1)_lambda times.o M$. The generation is because $G\\X_lambda$ is of the form $BB G_lambda$ where $G_lambda$ is the stabilizer of some point. Then, $G_lambda$ is connected so $pi_1(BB G_lambda)=0$. Hence $D_m (BB G_lambda)$ is generated by the constant sheaf. 
	+	We take $c_lambda=IC_lambda$. By irreducibility, we have the map $End(c_lambda)=End(bb(1)_lambda)$ is an isomorphism. 
]

#coro[
	$D_m (P_Theta\\overline(P_Theta overline(w) B)\/B)$ satisfies @Ass_realization. 
]

=== Basics on (completed) monodromic categories

We first give a recap on the definition of monodromic sheaves. In this part, all monodromic means unipotently monodromic. 

#def[
	Recall $tilde(Fl,size:#140%)=G\/U$ is the enhanced flag variety. We define $D_m^mon (U\\G\/U)$ to be the subcategory of $D_m (B\\G\/B)$ spanned by the image of $pi^!:D_m (U\\G\/U)->D_m (B\\G\/B)$. Equivalently, we may take $D_m^mon (U\\G\/U)$ to be the subcategory of $D_m (B\\G\/B)$ spanned by the image of $pi^!:D_m (U\\G\/B)->D_m (B\\G\/B)$ by stratawise computations. 
] <Def_monodromic_cat>

However, this category is not what we need. Rather, we need a certain completion of this category. We can see this from the following example. 

#exam[
	Take $G=GG_m$. Then, the category $D_m^mon (GG_m)$ is the subcategory spanned by the constant sheaves. We let $Loc_u (GG_m)$ denote the Abelian category of unipotent local systems over $GG_m$ (i.e., local systems $cal(L)$ over $GG_m$ equipped with a filtration $0=cal(L)_0 subset dots.c subset cal(L)_n=cal(L)$ such that $cal(L)_i\/cal(L)_(i-1)$ is constant). Then, we claim that we have the following characterization: 
	$ D_m^mon (GG_m)={cal(F)in D_m (GG_m), cal(H)^i (cal(F))in Loc_u (GG_m)} $ 
	Indeed, the right hand side is closed under taking kernels, cokernels, extensions, and direct summands, and contains the constant sheaf. Conversely, every unipotent local system must lie in $D_m^mon (GG_m)$ by considering the filtration, so the two categories are equivalent. 

	Then, we can identify $Loc(GG_m)$ with $ell$-adic representations of $pi_1 (GG_m)$. Such representations then factors through its pro-$ell$ part $T_ell (GG_m)=ZZ_ell (1)$, so we have $Loc(GG_m)=Rep(ZZ_ell (1),overline(QQ)_ell^n)$. The unipotent local systems hence corresponds to unipotent representations. 

	Now, for unipotent representations over a field of characteristic 0, we should pass to the nilpotent monodromy operator. Namely, for a representation $rho:T_ell (GG_m)->GL(overline(QQ)_ell^n)$, we have a linear map 
	$ log rho:V_GG_m->End(overline(QQ)_ell^n), #h(0.5em) v mapsto log rho(v), v in T_ell (GG_m) $
	If we choose a basis $v_0 in V$ ($V$ is 1-dimensional), clearly the data of $log rho$ is completely determined by $N:=log rho(v_0)$. Hence, $Loc_u (GG_m)=Mod^(f.l.)_(overline(QQ)_ell [[t]],Fr)$, where $Fr(t)=q^(-1)t$, and $f.l.$ denote finite length. Thus, we have by Morita theory $D_m^mon (GG_m)=D_(f.l.)(overline(QQ)_ell [[t]],Fr)$. 

	Notice that the whole category $D(overline(QQ)_ell [[t]],Fr)$ is a completion of $D_(f.l.)(overline(QQ)_ell [[t]],Fr)$. So we see that we need a completion $hat(D)_m^mon (GG_m)$ instead. In particular, we will need the object corresponding to the module $overline(QQ)_ell [[t]]$. 
]

#const[
	Recall that $Pro(D_m^mon (U\\G\/U))$ admits a natural stable $oo$-structure. 
] <Const_completed_monodromic>

=== Application 2: The monodromic (tilting) side



= The Bezrukavnikov-Arkhipov equivalence 

See my thesis. 

