#import "import.typ": *

= Gestalten

== Higher presentable categories 

=== Presentability 

We first recall the following definitions of presentable categories. As usual, we fix a regular cardinal $kappa$. 

#def[
	Let $cal(C)$ be an $(oo,1)$-category and $c in cal(C)$ an object. We say a diagram in $cal(C)$ is $kappa$-filtered if any subdiagram of size $<kappa$ can be extended to a right cone. 
	
	We say $c$ is $kappa$-compact if $Hom(c,-)$ commutes with $kappa$-filtered colimits. We denote the $kappa$-compact objects by $cal(C)^kappa$. 
	
	We say $cal(C)$ is $kappa$-presentable if there is a subset $S subset cal(C)$ of $kappa$-compact objects such that $cal(C)$ is generated by these $kappa$-compact objects under colimits. By Theorem 5.5.1.1 of @HTT, this is equivalent to the condition $cal(C)=upright("Ind")_kappa (cal(C)^kappa)$. 

	We say $cal(C)$ is presentable if it is $kappa$-presentable for some $kappa$. Again by Theorem 5.5.1.1 of @HTT, this is equivalent to the condition that $cal(C)$ is a localization of a presheaf category. 
] <Def_kappa_cpt_presentable>

#def[
	We define $Pr^L$ to be the non-locally small $(oo,1)$-category whose objects are the class of the presentable categories and morphisms the colimit preserving functors (technically speaking, we cannot define $Pr^L$ because its morphisms form a class). We define $Pr^L_kappa subset Pr^L$ to be the 1-full subcategory with objects the $kappa$-presentable categories and morphisms the functors preserving $kappa$-compact objects. This time it is indeed locally small. 
] <Def_cat_kappa_presentable_cat>

#thm[
	We have $Pr^L_kappa in Pr^L_kappa$. 
] <Thm_kappa_presentable_cat_kappa_presentable>
#proof[
	By the equivalent incarnation of $kappa$-presentable categories, we have $Pr^L_kappa$ equivalent to the categories that are of the form $cal(C)^kappa$ for $cal(C) in Pr^L_kappa$. This condition is formulated as $cal(C)^kappa$ is small, admits all $kappa$-small colimits and retracts, and the functors between them preserving $kappa$-small colimits. We denote this equivalent category by $Rex_kappa$. We now prove $Rex_kappa$ is $kappa$-presentable. 

	Note that the forgetful functor $U:Rex_kappa->Cat$ admit a left adjoint given by $cal(C) mapsto pSh(cal(C))^kappa$. We claim that this is a pair of monadic adjunction, so that $Rex_kappa$ is the algebra of the monad $U compose F$. By Proposition 4.7.3.5 of @HA, it suffices to prove that $U$ is conservative, $Rex_kappa$ admits and $U$ preserves $U$-split geometric realizations. Clearly $U$ is conservative (it is faithful). Then, let $cal(C)_bullet$ be a simplicial diagram in $Rex_kappa$, admitting a geometric realization $cal(C)_(-1) in Cat$, with a splitting of $cal(C)_bullet->cal(C)_(-1) in Cat$. But then, $Fun(I,cal(C)_bullet)->Fun(I,cal(C)_(-1))$ is a split geometric realization in $Cat$ for any $kappa$-small diagram $I$, extending to $I^triangle.r.small$ shows that $cal(C)_(-1) in Rex_kappa$. 

	Finally, we use this to show that $Rex_kappa$ is $kappa$-presentable. Firstly it admit all colimits because it is the algebra of a monad, and $Cat$ admits all colimits. Note that $Cat$ is the category of all small categories, hence compactly generated by the categories $Delta^n$. Upon showing $U$ preserves $kappa$-filtered colimits, we can show $F$ preserves $kappa$-compact objects, which shows that $Rex_kappa$ is $kappa$-compactly generated. For a $kappa$-filtered diagram $cal(D)_i in Rex_kappa$, their $kappa$-filtered colimit in $Cat$ $cal(D)$ admits all $kappa$-small colimits by the construction of colimit categories, and the functors $cal(D)_i->cal(D)$ preserves $kappa$-small colimits. This finishes the proof. 
]

We recall more facts on the category $Pr^L$. 

#thm(name: [Adjoint functor theorem, @HTT Corollary 5.5.2.9])[
	Let $F:cal(C)->cal(D)$ be a functor between presentable categories. Then 
	+	$F$ admits a right adjoint iff $F$ preserves all colimits. 
	+	$F$ admits a left adjoint iff $F$ preserves all limits and preserves $kappa$-filtered colimits for some regular cardinal $kappa$. In this case, its left adjoint preserves $kappa$-compact objects. 
] <Thm_adj_fct_thm>

#def[
	We define $Pr^R$ and $Pr^R_kappa$ to be the categories of ($kappa$-) presentable categories with morphisms right adjoints. They are opposite to $Pr^L$ and $Pr^L_kappa$ respectively. 
] <Def_cat_kappa_presentable_cat_right>

#thm(name: [@HA, Proposition 5.5.3.13, Theorem 5.5.3.18, Proposition 5.5.7.6])[
	The category $Pr^L$ admits all limits, and the forgetful functor $Pr^L->hat(Cat)$ preserves limits. 
	
	The category $Pr^L$ admits all colimits, equivalently, the category of $Pr^R$ admits all limits, and the forgetful functor $Pr^R->hat(Cat)$ preserves limits. 

	The analogous statements hold for $Pr^L_kappa$ and $Pr^R_kappa$. 
] <Thm_lim_colim_cat_kappa_presentable_cat>

Then, we recall the definition of Lurie tensor products of presentable categories. 

#const[
	For $cal(C),cal(D) in Pr^L$, there is a category $cal(C)times.o cal(D) in Pr^L$, universal among presentable categories with a functor $cal(C)times cal(D)->cal(C)times.o cal(D)$. An analogous construction works for $cal(C),cal(D)in Pr^L_kappa$. 

	The construction goes as follows: suppose $cal(C)=pSh(cal(C)_0)[W^(-1)]$, and $cal(D)=pSh(cal(D)_0)[V^(-1)]$, we have 
	$ cal(C)times.o cal(D)=pSh(cal(C)_0 times cal(D)_0)[W^(-1)times V^(-1)] $

	It can be verified that this gives a symmetric monoidal structure on $Pr^L$ and $Pr^L_kappa$. 
] <Const_Lurie_tensor_product>

#thm[
	The category $Pr^L$ is Cartesian closed. The internal $Hom$ object is given by $Fun^L (-,-)$. Similarly, the category of $Pr^L_kappa$ has internal $Hom$ object $upright("Ind")_kappa Fun^(Rex_kappa)((-)^kappa,(-)^kappa)$. 
]

