#import "/void-template/1.0.0/void-import.typ": *

#let documentclass = "thu_undergraduate_thesis"
#let showtableofcontent = true
#let base-level = 2
//reloading environments invoking base-level
#let thm = theorem.with(base-level:base-level)
#let lem = lemma.with(base-level:base-level)
#let problem = problem.with(base-level:base-level)
#let rem = remark.with(base-level:base-level)
#let def = definition.with(base-level:base-level)
#let conj = conjecture.with(base-level:base-level)
#let exam = example.with(base-level:base-level)
#let notation = notation.with(base-level:base-level)
#let properties = properties.with(base-level:base-level)
#let exercise = exercise.with(base-level:base-level)
#let observation = observation.with(base-level:base-level)
#let const = construction.with(base-level:base-level)
#let prop = proposition.with(base-level:base-level)
#let question = question.with(base-level:base-level)
#let fact = fact.with(base-level:base-level)
#let coro = corollary.with(base-level:base-level)
#let solution = solution.with(base-level:base-level)

#let DefCatBold(name) = [
	#math.op(math.bold(name))
	#label("categories-bold-"+name)
]
#let DefCatStr(name) = [
	#math.op(math.upright(name))
	#label("categories-str-"+name)
]

#let Set = DefCatBold("Set")
#let Fin = DefCatBold("Fin")
#let Ani = DefCatBold("Ani")
#let Sp = DefCatBold("Sp")
#let Cat = DefCatBold("Cat")
#let DGCat = DefCatBold("DGCat")
#let Mon = DefCatBold("Mon")
#let Alg = DefCatBold("Alg")
#let CMon = DefCatBold("CMon")
#let CAlg = DefCatBold("CAlg")
#let Mod = DefCatBold("Mod")
#let coMod = DefCatBold("coMod")
#let Ab = DefCatBold("Ab")
#let Vect = DefCatBold("Vect")
#let Pr = DefCatBold("Pr")
#let Aff = DefCatBold("Aff")
#let Stk = DefCatBold("Stk")
#let pStk = DefCatBold("pStk")
#let Rep = DefCatBold("Rep")
#let Sh = DefCatStr("Sh")
#let pSh = DefCatStr("pSh")
#let QCoh = DefCatStr("QCoh")
#let Coh = DefCatStr("Coh")
#let IndCoh = DefCatStr("IndCoh")
#let Perf = DefCatStr("Perf")
#let Desc = DefCatStr("Desc")
#let Sat = DefCatStr("Sat")
#let Perv = DefCatBold("Perv")

#let Ind = math.op("Ind")

#let lim = math.op("lim", limits: true)
#let colim = math.op("colim", limits: true)
#let op = math.upright("op")
#let St = math.upright("St")
#let Fun = math.op("Fun")
#let Hom = math.op("Hom")
#let Map = math.op("Map")
#let LKE = math.op("LKE")
#let RKE = math.op("RKE")
#let gr = math.op("gr")
#let Span = math.op("Span")
#let RHom = math.op("RHom")
#let Gal = math.op("Gal")
#let Ext = math.op("Ext")

#let cn = math.upright("cn")
#let conv = math.upright("conv")
#let ft = math.upright("ft")
#let lft = math.upright("lft")
#let aft = math.upright("aft")
#let laft = math.upright("laft")
#let perf = math.upright("perf")
#let unip = math.upright("unip")
#let glob = math.upright("glob")
#let act = math.upright("act")
#let waki = math.upright("waki")
#let triv = math.upright("triv")
#let mixed = math.upright("mixed")
#let sph = math.upright("sph")
#let ren = math.upright("ren")
#let mon = math.upright("mon")

#let inj = sym.arrow.r.hook
#let surj = sym.arrow.r.twohead
#let End = math.op("End")
#let Aut = math.op("Aut")
#let LHS = math.op("LHS")
#let RHS = math.op("RHS")
#let adj = sym.tack.l
#let Idem = math.op("Idem")

#let Spec = math.op("Spec")
#let Gr = math.upright("Gr")
#let GL = math.upright("GL")
#let SL = math.upright("SL")
#let PGL = math.upright("PGL")
#let Fl = math.upright("Fl")
#let Coord = math.upright("Coord")
#let Supp = math.op("Supp")

#let Inv = math.op("Inv")
#let Ad = math.op("Ad")
#let IC = math.upright("IC")
#let CT = math.op("CT")
#let Frac = math.op("Frac")
#let rank = math.op("rank")

#let lact = rotate(90deg, sym.arrow.cw)
#let ract = rotate(270deg, sym.arrow.ccw)

#let res = math.op("res")
#let ind = math.op("ind")
#let coind = math.op("coind")
#let red = math.upright("red")
#let fr = math.upright("fr")
#let pt = math.upright("pt")
#let loc = math.upright("loc")
#let ext = math.upright("ext")
#let aff = math.upright("aff")
#let Stab = math.op("Stab")
#let oblv = math.op("oblv")

#let IW = math.cal("IW")
#let AS = math.bb("AS")
#let Av = math.op("Av")

#let Sym = math.op("Sym")

#let check(sth) = [$caron(sth, size: #0%)$]