#import "import.typ": *

= Gestalten

== Higher presentable categories 

=== Presentability 

We first recall the following definitions of presentable categories. As usual, we fix an uncountable regular cardinal $kappa$. 

#def[
	Let $cal(C)$ be an $(oo,1)$-category and $c in cal(C)$ an object. We say a diagram in $cal(C)$ is $kappa$-filtered if any subdiagram of size $<kappa$ can be extended to a right cone. 
	
	We say $c$ is $kappa$-compact if $Hom(c,-)$ commutes with $kappa$-filtered colimits. We denote the $kappa$-compact objects by $cal(C)^kappa$. 
	
	We say $cal(C)$ is $kappa$-presentable if there is a subset $S subset cal(C)$ of $kappa$-compact objects such that $cal(C)$ is generated by these $kappa$-compact objects under colimits. By Theorem 5.5.1.1 of @HTT, this is equivalent to the condition $cal(C)=upright("Ind")_kappa (cal(C)^kappa)$. 

	We say $cal(C)$ is presentable if it is $kappa$-presentable for some $kappa$. Again by Theorem 5.5.1.1 of @HTT, this is equivalent to the condition that $cal(C)$ is a localization of a presheaf category. 
] <Def_kappa_cpt_presentable>

#def[
	We define $Pr^L$ to be the non-locally small $(oo,1)$-category whose objects are the class of the presentable categories and morphisms the colimit preserving functors (technically speaking, we cannot define $Pr^L$ because its morphisms form a class). We define $Pr^L_kappa subset Pr^L$ to be the 1-full subcategory with objects the $kappa$-presentable categories and morphisms the functors preserving $kappa$-compact objects. This time it is indeed locally small. 
] <Def_cat_kappa_presentable_cat>

#thm[
	We have $Pr^L_kappa in Pr^L_kappa$. 
] <Thm_kappa_presentable_cat_kappa_presentable>
#proof[
	By the equivalent incarnation of $kappa$-presentable categories, we have $Pr^L_kappa$ equivalent to the categories that are of the form $cal(C)^kappa$ for $cal(C) in Pr^L_kappa$. This condition is formulated as $cal(C)^kappa$ is small, admits all $kappa$-small colimits and retracts, and the functors between them preserving $kappa$-small colimits. We denote this equivalent category by $Rex_kappa$. We now prove $Rex_kappa$ is $kappa$-presentable. 

	Note that the forgetful functor $U:Rex_kappa->Cat$ admit a left adjoint given by $cal(C) mapsto pSh(cal(C))^kappa$. We claim that this is a pair of monadic adjunction, so that $Rex_kappa$ is the algebra of the monad $U compose F$. By Proposition 4.7.3.5 of @HA, it suffices to prove that $U$ is conservative, $Rex_kappa$ admits and $U$ preserves $U$-split geometric realizations. Clearly $U$ is conservative (it is faithful). Then, let $cal(C)_bullet$ be a simplicial diagram in $Rex_kappa$, admitting a geometric realization $cal(C)_(-1) in Cat$, with a splitting of $cal(C)_bullet->cal(C)_(-1) in Cat$. But then, $Fun(I,cal(C)_bullet)->Fun(I,cal(C)_(-1))$ is a split geometric realization in $Cat$ for any $kappa$-small diagram $I$, extending to $I^triangle.r.small$ shows that $cal(C)_(-1) in Rex_kappa$. 

	Finally, we use this to show that $Rex_kappa$ is $kappa$-presentable. Firstly it admit all colimits because it is the algebra of a monad, and $Cat$ admits all colimits. Note that $Cat$ is the category of all small categories, hence compactly generated by the categories $Delta^n$. Upon showing $U$ preserves $kappa$-filtered colimits, we can show $F$ preserves $kappa$-compact objects, which shows that $Rex_kappa$ is $kappa$-compactly generated. For a $kappa$-filtered diagram $cal(D)_i in Rex_kappa$, their $kappa$-filtered colimit in $Cat$ $cal(D)$ admits all $kappa$-small colimits by the construction of colimit categories, and the functors $cal(D)_i->cal(D)$ preserves $kappa$-small colimits. This finishes the proof. 
]

We recall more facts on the category $Pr^L$. 

#thm(name: [Adjoint functor theorem, @HTT Corollary 5.5.2.9])[
	Let $F:cal(C)->cal(D)$ be a functor between presentable categories. Then 
	+	$F$ admits a right adjoint iff $F$ preserves all colimits. 
	+	$F$ admits a left adjoint iff $F$ preserves all limits and preserves $kappa$-filtered colimits for some regular cardinal $kappa$. In this case, its left adjoint preserves $kappa$-compact objects. 
] <Thm_adj_fct_thm>

#def[
	We define $Pr^R$ and $Pr^R_kappa$ to be the categories of ($kappa$-) presentable categories with morphisms right adjoints. They are opposite to $Pr^L$ and $Pr^L_kappa$ respectively. 
] <Def_cat_kappa_presentable_cat_right>

#thm(name: [@HA, Proposition 5.5.3.13, Theorem 5.5.3.18, Proposition 5.5.7.6])[
	The category $Pr^L$ admits all limits, and the forgetful functor $Pr^L->hat(Cat)$ preserves limits. 
	
	The category $Pr^L$ admits all colimits, equivalently, the category of $Pr^R$ admits all limits, and the forgetful functor $Pr^R->hat(Cat)$ preserves limits. 

	The analogous statements hold for $Pr^L_kappa$ and $Pr^R_kappa$. 
] <Thm_lim_colim_cat_kappa_presentable_cat>

Then, we recall the definition of Lurie tensor products of presentable categories. 

#const[
	For $cal(C),cal(D) in Pr^L$, there is a category $cal(C)times.o cal(D) in Pr^L$, universal among presentable categories with a functor $cal(C)times cal(D)->cal(C)times.o cal(D)$. An analogous construction works for $cal(C),cal(D)in Pr^L_kappa$. 

	The construction goes as follows: suppose $cal(C)=pSh(cal(C)_0)[W^(-1)]$, and $cal(D)=pSh(cal(D)_0)[V^(-1)]$, we have 
	$ cal(C)times.o cal(D)=pSh(cal(C)_0 times cal(D)_0)[W^(-1)times V^(-1)] $

	It can be verified that this gives a symmetric monoidal structure on $Pr^L$ and $Pr^L_kappa$. 
] <Const_Lurie_tensor_product>

#thm[
	The category $Pr^L$ is Cartesian closed. The internal $Hom$ object is given by $Fun^L (-,-)$. Similarly, the category of $Pr^L_kappa$ has internal $Hom$ object $upright("Ind")_kappa Fun_(Rex_kappa)((-)^kappa,(-)^kappa)$. 
]

=== Stefanich rings and higher modules

#def[
	Recall from @Thm_kappa_presentable_cat_kappa_presentable that we have $Pr_kappa^L in Pr_kappa^L$. We iteratively define $(n+1)Pr_kappa^L:=Mod_(n Pr_kappa^L)(Pr_kappa^L)$, where $1Pr_kappa^L:=Pr_kappa^L$, $0Pr_kappa^L=Ani$. 

	This should be think of the analogous fact that $(oo,2)$-categories are in some sense categories enriched in $(oo,1)$-categories. 
] <Def_n_Pr>

#thm[
	Let $cal(C) in CAlg(Pr_kappa^L)$ be a presentably symmetric monoidal category. Then, the functor $CAlg(cal(C))->CAlg(Mod_(cal(C))(Pr_kappa^L))$ given by $A mapsto Mod_A$ (or $LMod_A$ equivalently, if we want the explicit $EE_oo$-tensor structure on the category) is fully faithful, and admits a right adjoint given by $cal(D) mapsto End_(cal(D))(bb(1)_(cal(D)))$. In particular, $End_(Mod_A)(A)=A$. 
] <Thm_Mod_fully_faithful>

#rem[
	The formula $Mod_A times.o_(Mod_B)Mod_C=Mod_(A times.o_B C)$ can be regarded as the commutation of the above functor with pushouts. 
]

From now on, we often fix $kappa=aleph_1$ (the cardinality $2^(aleph_0)$), and omit $kappa$'s and $L$'s from all $Pr_kappa^L$'s when we do so. 

#def[
	We define the $kappa$-presentably symmetric monoidal $(oo,1)$-category of Stefanich rings to be 
	$ StRing=colim_(Mod_((-)))(CAlg(0Pr)inj CAlg(1Pr)inj CAlg(2Pr)inj dots.c) $
	where the colimit is taken in $Pr_kappa^L$, the transition map given as in @Thm_Mod_fully_faithful. Equivalently, we can define 
	$ StRing=lim_(End_((-)))(CAlg(0Pr)<-CAlg(1Pr)<-CAlg(2Pr)<-dots.c) $
	this time computing the limit as plain categories. 
] <Def_StRing>

#lem[
	Let $(cal(C)_n)_(n>=n_0)$ be a sequence of objects of $Pr_kappa^L$, with transition functors fully faithful left adjoints $F_n:cal(C)_n inj cal(C)_(n+1)$. Then, the inclusion 
	$ iota_n:cal(C)_n inj cal(C):=colim_(Pr_kappa^L)(cal(C)_(n_0)inj cal(C)_(n_0+1)inj dots.c) $
	is fully faithful. 
] <Lem_fully_faithful_colim_fully_faithful>
#proof[
	We denote the right adjoint to $F_n$ by $G_n$. Since ${m|m>=n}subset{m|m>=n_0}$ is cofinal, we may assume $n=n_0$. Then, 
	$ cal(C)=lim_(Cat)(dots.c->cal(C)_(n+1)->cal(C)_(n)) $
	Then, the above inclusion is left adjoint to the projection $q_n:cal(C)->>cal(C)_n$. We must show that the unit map $id_(cal(C)_n)->q_n iota_n$ is an equivalence. Let $c in cal(C)_n$, we claim that $iota_n (c)$ is computed by the sequence of objects $(c,F_n (c),F_(n+1)compose F_n (c),dots.c)$. To prove this, take any $(d_n,d_(n+1),dots.c) in cal(C)$, consider 
	$ 
		Hom_(cal(C))((c,F_n (c),dots.c),(d_n,d_(n+1),dots.c))=&lim_(j>=n)Hom_(cal(C)_j)(F_j compose dots.c compose F_n (c),d_j) \
		=&lim_(j>=n)Hom_(cal(C)_n)(c,G_n compose dots.c compose G_j (d_j)) \
		=&Hom_(cal(C)_n)(c,d_n)
	$
	Thus, the composition is obviously the identity. 
]

We now fix an appropriate category of commutative algebras $CAlg$, for example, $CAlg=CAlg(Sp)$. 

#const[
	By the above lemma, the faithful inclusion $Mod:CAlg inj CAlg(1Pr)$ gives rise to a fully faithful functor 
	$ cal(O):CAlg inj CAlg(1Pr) inj StRing $
	We take $Aff=CAlg^op$, and also denote the functor 
	$ cal(O):Aff^op inj StRing $
	Take $Spec f:Spec B->Spec A in Aff$. The $n$-th component of $cal(O)(Spec f):cal(O)(Spec A)->cal(O)(Spec B)$ is given by 
	$ f_n^*:n Pr_A->n Pr_B $
	Explicitly, $f_0^*:Mod_A->Mod_B$ is given by $-times.o_A B$, and 
	$ f_n^*:Mod_((n-1)Pr_A)(1Pr)->Mod_((n-1)Pr_B)(1Pr) $
	is given by $-times.o_((n-1)Pr_A)(n-1)Pr_B$, with the structure morphism given by $f_(n-1)^*$. 
]

We will then show that the above data of $f_n^*$ can be upgraded to a six-functor formalism over $Aff$. 

#def[
	Let $cal(C) in CAlg(Pr_L^kappa)$, and $f:A->B in CAlg(cal(C))$. We say $f$ is $kappa$-finitely presented if $B in CAlg(Mod_A (cal(C)))^kappa$. 
]

#lem[
	Let $cal(C) in CAlg(Pr_L)$. Then, the forgetful functor $CAlg(cal(C))->cal(C)$ preserves sifted colimits. 
] <Lem_CAlg_forgetful_preserve_sifted>
#proof[
	We denote $F:cal(C)sadj CAlg(cal(C)):U$ the free-forgetful adjunction. Let $I$ be any sifted diagram. Then, take $i mapsto A_i in CAlg(cal(C))$, and let $M=colim_(I)U A_i$. Then, we construct an $EE_oo$-algebra structure on $M$ such that it becomes equivalent to $colim_I A_i$. The structural maps are given by the identifications 
	$ M^(times.o n)=colim_(I^n)U A_(i_1) times.o dots.c U A_(i_n)=colim_I A_i^(times.o n) $
	where the first equivalence is due to the distribution law on colimits and tensors, and the second by the assumption that $I$ is sifted. The above identification gives an $EE_oo$-structure on $M$, which we will denote the corresponding algebra by $tilde(M)$. Equivalently, expressing $tilde(M)$ by the monad $U F$, it is given by 
	$ T M=colim T U A_i->colim U A_i=M $
	
	Then, for any algebra $A$, since the adjunction $F ladj U$ is monadic, we have an equivalence 
	$ A=colim_(Delta^op)F(U F)^n U A $
	Hence, we have the chain of equivalences 
	$
		Hom_(CAlg(cal(C)))(tilde(M),B)=&lim_(Delta)Hom_cal(C)((U F)^n U tilde(M),U B) \
		=&lim_(Delta)Hom_cal(C)((U F)^n M, U B) \
		=&lim_Delta lim_(I^op)Hom_cal(C)((U F)^n U A_i,U B) \
		=&lim_(I^op)lim_Delta Hom_cal(C)(F(U F)^n U A_i,B) \
		=&lim_(I^op)Hom_cal(C)(A_i,B)
	$
	hence expressing $tilde(M)=colim_I A_i$. 
]

#lem[
	Let $cal(C)in CAlg(Pr_L^kappa)$. Then the functor $Mod_((-)):CAlg(cal(C))->CAlg(Mod_(cal(C))(Pr_L^kappa))$ is a functor in $Pr_L^kappa$. Namely, we have $Mod_((-))$ preserves $kappa$-compact objects and equivalently its right adjoint $End_((-))(bb(1))$ preserves $kappa$-filtered colimits. 
] <Lem_Mod_functor_kappa_presentable>
#proof[
	We prove the statement on the right adjoint $End_((-))(bb(1))$. Firstly, in the proof of @Thm_kappa_presentable_cat_kappa_presentable, we have shown that the forgetful functor $Rex_kappa->Cat$ preserves $kappa$-filtered colimits. Now, take $I$ an $kappa$-filtered diagram, $cal(D)_i in CAlg(Mod_(cal(C))(Pr_L^kappa))$, $cal(D)=colim_I cal(D)_i$, and algebras $A_i=End_(cal(D)_i)(bb(1)_i)$, $A=End_cal(D)(bb(1))$. We must show the colimit taken in $CAlg(cal(C))$ $colim_I A_i->A$ is equivalent to $A$. 

	By the claim that $Rex_kappa->Cat$ preserves $kappa$-filtered colimits, $cal(D)=colim_I cal(D)_i$ gives $cal(D)^kappa=colim_I cal(D)_i^kappa$, where the right colimit is taken in $Cat$. It suffices to show that $Hom(c,colim A_i)=Hom(c,A)$ for all $c in cal(C)^kappa$. 

	By compactness of $c$, we have 
	$ Hom_cal(C)(c,colim A_i)=colim Hom_cal(C)(c,A_i) $ 
	Then, the algebra units $cal(C)->cal(D)_i$ given by $c mapsto c times.o bb(1)_i$ is a morhpism in $Pr_kappa^L$, so preserves $kappa$-compact objects. Moreover, it admit a right adjoint given by $Hom(bb(1)_i,-)$. Thus, we have equivalences
	$ 
		colim Hom_cal(C)(c,A_i)=&colim Hom_cal(D)_i (c times.o bb(1)_i,bb(1)_i) \
		=&Hom_cal(D)(c times.o bb(1),bb(1))=Hom_cal(C)(c,A)
	$
]

#thm[
	Let $cal(C) in CAlg(Pr_L^kappa)$. Let $f:A->B$ be a $kappa$-finitely presented map. Then, the induced map $g^*:Mod_A->Mod_B$ is also $kappa$-finitely presented. 
] <Thm_Mod_preserve_kappa_fin_presented>
#proof[
	Apply @Lem_Mod_functor_kappa_presentable to $cal(C)=Mod_A (cal(C))$. 
]

#coro[
	Let $f:A->B$ be a $kappa$-finitely presented map. Then for each $n>=0$, by iteratively applying the previous theorem, we have $f_n^*:n Pr_A->n Pr_B$ is a $kappa$-finitely presented functor. 
] <Coro_kappa_fin_presented_preserve_nPr>

#lem[
	Let $cal(C) in CAlg(Pr_kappa^L)$. Then for $A in CAlg(cal(C))$, we have $A$ is $kappa$-compact iff its underlying object is $kappa$-compact. 
] <Lem_alg_cpt_iff_mod_cpt>
#proof[
	Consider the free-forgetful adjunction $F:cal(C) sadj CAlg(cal(C)):U$. Note that for $M in cal(C)^kappa$, we have 
	$ U compose F(M)=plus.o.big_(n in NN)(M^(times.o n))_(h Sigma_n) $ 
	which is a countable direct sum of $kappa$-compact objects, hence $kappa$-compact since $kappa$ is uncountable. Then, by @Lem_CAlg_forgetful_preserve_sifted, $U$ preserves sifted colimits hence $kappa$-filtered colimits, so $F$ preserves $kappa$-compact objects, hence $F(M)$ is compact in $CAlg(cal(C))$. Also, notice that $F(M)$ generate the category $CAlg(cal(C))^kappa$ under retracts and $kappa$-small colimits. So, now it suffices to prove that algebras with underlying modules $kappa$-compact are closed under retracts and $kappa$-small colimits. 

	For retracts the claim is obvious. For $kappa$-small colimits, we represent the colimit using its simplicial replacement. This refers to the following general procedure: let $I$ be any diagram and $A_i$ are objects indexed by this diagram, we have 
	$ colim_I A_i=colim_([n] in Delta^op) product.co_(f in Hom(Delta^n,I))f(0) $
	with the obvious transition maps. For $I$ a $kappa$-small diagram, each coproduct in the simplicial replacement is still $kappa$-small. Then, by @Lem_CAlg_forgetful_preserve_sifted, the functor $U$ preserves geometric realizations, so it suffices to prove $U (product.co f(0))$ is $kappa$-small, which is by assumption. Thus, we have proven that every compact algebra is compact as a module. 

	For the converse, suppose $U(A)in cal(C)$ is compact. Then by monadicity we have $A=colim (F U)^n A$. However every term in the simplicial diagram is $kappa$-compact as an algebra, we obtain that $A$ is also $kappa$-compact. 
]

#lem[
	Let $cal(C) in CAlg(Pr_kappa^L)$. Then, for $A in CAlg(cal(C))$, if $A$ is a $kappa$-finitely presented algebra, then $M in Mod_A (cal(C))$ is $kappa$-compact iff its underlying object is $kappa$-compact. 
] <Lem_kappa_fin_pres_pre_cpt>
#proof[
	Let $M in Mod_A (cal(C))^kappa$. Note the $kappa$-compact $A$-modules are generated by free $A$-modules generated by $kappa$-compact objects under retracts and $kappa$-small colimits. Hence, since the forgetful functor preserves colimits, it suffices to prove that free $A$-modules generated by $kappa$-compact objects have their underlying objects compact. This is obvious, since $A$ is $kappa$-compact and hence $A^(plus.o alpha)$ is $kappa$-compact for all $alpha<kappa$. 

	Then, suppose the underlying object of $M$ is compact. The argument follows again from the monadic free-forgetful adjunction as in the previous proof of @Lem_alg_cpt_iff_mod_cpt. 
]

#thm[
	For every $n>=0$, we have a six-functor formalism $n Pr^(*,*)$ given by 
	$ Span(Aff,#[all],#[$aleph_1$-finitely presented maps])->(n+1)Pr $
	$ Spec A mapsto n Pr_A, (Spec B<-^f Spec A->^g Spec C) arrow.bar.long (n Pr_B-->^(f_n^*)n Pr_A-->^(g_(n,*))n Pr_C) $
	Explicitly, we make the following requirements: 
	+	$n Pr_A$ is a Cartesian closed symmetric monoidal $aleph_1$-presentable $(oo,n+1)$-category. 
	+	For all maps $Spec f:Spec A->Spec B$, there is a pullback functor $f_n^*:n Pr_B->n Pr_A$, preserving all colimits and canonically compatible with composition of functors. 
	+	For $aleph_1$-finitely presented maps $Spec g:Spec A->Spec C$ (i.e., the map $g:C->A$ is $aleph_1$-finitely presented), there is a pushforward functor $g_(n,*)$, preserving all colimits and canonically compatible with composition of functors. 
	+	For any Cartesian diagram in $Aff$ // https://q.uiver.app/#r=typst&q=WzAsNCxbMCwwLCJTcGVjIEEnIl0sWzEsMCwiU3BlYyBBIl0sWzAsMSwiU3BlYyBCJyJdLFsxLDEsIlNwZWMgQiJdLFswLDEsImcnIl0sWzAsMiwiZiciLDJdLFsxLDMsImYiXSxbMiwzLCJnIiwyXV0=
		#align(center, diagram({
			node((0, 0), [$Spec A'$])
			node((1, 0), [$Spec A$])
			node((0, 1), [$Spec B'$])
			node((1, 1), [$Spec B$])
			edge((0, 0), (1, 0), [$g'$], label-side: left, "->")
			edge((0, 0), (0, 1), [$f'$], label-side: right, "->")
			edge((1, 0), (1, 1), [$f$], label-side: left, "->")
			edge((0, 1), (1, 1), [$g$], label-side: right, "->")
			node((0.2, 0.3), [$Cartmark$])
		}))
		with $f$ hence $f'$ $aleph_1$-finitely presented, we have a canonical base change isomorphism 
		$ g_n^*compose f_(n,*) =f'_(n,*)compose g'_n^* $
		compatible with horizontal and vertical composition of Cartesian squares. 
	+	For each $f:Spec B->Spec A$ $aleph_1$-finitely presented, a canonical projection formula isomorphism 
		$ f_(n,*)M times.o N=f_(n,*)(M times.o f_n^* N) $
		for any $M in n Pr_B, N in n Pr_A$
] <Thm_6ff_nPrA>
#proof[
	We define $g_(n,*)$ to be the right adjoint of $g_n^*$, the forgetful functor or restriction of scalars. It naturally admits a right adjoint given by coinduction, so we verify that it preserves $aleph_1$-compact objects. For $g:C->A$ $aleph_1$-finitely presented, by @Coro_kappa_fin_presented_preserve_nPr we have $g_m^*:m Pr_C->m Pr_A$ $aleph_1$-finitely presented for all $m$. Then, by applying @Lem_kappa_fin_pres_pre_cpt with $cal(C)=n Pr_A$, $A=(n-1) Pr_B$, we have $g_(n,*)$ preserves $aleph_1$-compact object, hence defines a morphism in $Pr_(aleph_1)^L$. 

	Now, the functorialities are all obvious, and we now unwind the required conditions of the base change isomorphism and projection formula. 

	For the base change isomorphism, consider a pushout diagram of algebras $D=B times.o_A C$. Then, the category of modules fit into the following square 
	// https://q.uiver.app/#r=typst&q=WzAsNCxbMSwxLCJNb2RfRCJdLFswLDAsIk1vZF9BIl0sWzEsMCwiTW9kX0IiXSxbMCwxLCJNb2RfQyJdLFszLDEsImcnXyoiXSxbMCwyLCJnXyoiLDJdLFsxLDIsImYnXioiXSxbMywwLCJmXioiLDJdXQ==
	#align(center, diagram({
		node((1, 1), [$Mod_D$])
		node((0, 0), [$Mod_A$])
		node((1, 0), [$Mod_B$])
		node((0, 1), [$Mod_C$])
		edge((0, 1), (0, 0), [$g'_*$], label-side: left, "->")
		edge((1, 1), (1, 0), [$g_*$], label-side: right, "->")
		edge((0, 0), (1, 0), [$f'^*$], label-side: left, "->")
		edge((0, 1), (1, 1), [$f^*$], label-side: right, "->")
	}))
	since unwinding definitions, let $M in Mod_C$, $f'^*compose g'_*(M)=B times.o_A M$, $g_* compose f^*(M)=D times.o_C M$, and we have 
	$ D times.o_C M=(B times.o_A C)times.o_C M=B times.o_A M $

	the base change isomorphism. Then, take $A,B,C,D$ to be the corrsponding $(n-1)Pr_#[]$'s give the original base change isomorphism. 

	Now it suffices to treat the projection formula. Take $f:A->B$ a map of algebras, and take modules $M in Mod_B$, $N in Mod_A$. Then, the projection formula reads 
	$ M times.o_B f_*(N)=f_*(f^*(M)times.o_A N) $
	Note that both sides preserves colimits in $M$, so we may assume that $M$ is free, and in which case the assertion is obvious. Finally taking $A$ and $B$ to be the corrsponding $(n-1)Pr$'s give the original projection formula result. 
]
#rem[
	The requirements that $g$'s should be $aleph_1$-finitely presented could be removed, and the above construction will have result a six-functor formalism in $Pr^L$ instead of $Pr_kappa^L$. 
]

=== Further properties of the six-functor formalism

#prop[
	Let $cal(C)$ be an $(oo,3)$-category. Let $F:c->d$ be a morphism in $cal(C)$, then the following ara equivalent. 
	+	$F$ admits a right adjoint $F^R:d->c$, and both $eta:id_c->F^R compose F in End(c)$ and $epsilon:F compose F^R->id_d in End(d)$ admit right adjoints, in the sense that $End(c)$ and $End(d)$ are $(oo,2)$-categories. 
	+	$F$ admits a left adjoint $F^L:d->c$, and both $eta:id_d:F compose F^L in End(d)$ and $epsilon:F^R compose F->id_c$ admit left adjoints. 
	When the equivalent condition holds, we have a natural identification $F^L tilde.eq F^R$. One also call this pair of morphisms by fully adjointable morphisms. 
] <Prop_fully_adjointable_ambidexterity>
#proof[
	We prove that under the condition of $(1)$, we have $F^R$ also the left adjoint of $F$. The other direction is dual. 

	We will attempt to find $eta':id_d->F compose F^R in End(d)$ and $epsilon':F^R compose F->id_c in End(c)$ such that they are the data of unit and counit for $F^R ladj F$. We define $eta':=epsilon^R$ and $epsilon':=eta^R$. One can easily check that these data satisfies the condition (2).  
]

#coro[
	Let $Spec f:Spec B->Spec A$ be a morphism in $Aff$. Suppose $f:A->B$ is $aleph_1$-finitely presented, then for $n>=1$, we have the functor $f_n^*:n Pr_A->n Pr_B$ satisfy the equivalent conditions of @Prop_fully_adjointable_ambidexterity. In particular, $f_(n,*):n Pr_B->n Pr_A$ is also left adjoint to $f_n^*$. 
] <Coro_nPr_countably_presented_ambidexterity>
#proof[
	Firstly note that we may take the ambient category to be $(n+1)Pr_A$, which lies in $(n+2)Pr$, so admits an $(oo,3)$-category structure. Now, it suffices to prove that the unit and counit of the adjunction $f_n^* ladj f_(n,*)$ admit right adjoints. 
	
	For the unit $id_(n Pr_A)->f_(n,*)f_n^*$, its right adjoint would be a natural transformation $f_(n,*)f_n^*->id_(n Pr_A)$, such that there are further units and counits such that the adjunction identity holds. But note here that everything is $n Pr_A$-linear, it suffices to construct the right adjoint of $(id_(n Pr_A)->f_(n,*)f_n^*)((n-1)Pr_A)$, and extend linearly to a full right adjoint. Here, we can identify the functor simply as $f_(n-1)^*:(n-1)Pr_A->(n-1)Pr_B$, which admit an obvious right adjoint. 

	For the counit $f_n^*f_(n,*)->id_(n Pr_B)$, we consider the following identification: 
	$ 
	End_((n+1)Pr_A)(n Pr_B)=&End_(Mod_(n Pr_A)(1Pr))(Mod_((n-1)Pr_B)(n Pr_A)) \
	=&Mod_((n-1)Pr_B)(n Pr_A)times.o_(Mod_((n-1)Pr_A)(n Pr_A)) Mod_((n-1)Pr_B)(n Pr_A) \
	&(#[since module categories are self-dual]) \
	=&Mod_((n-1)Pr_B times.o_((n-1)Pr_A)(n-1)Pr_B)(n Pr_A)
	$
	Under this identification, the counit is simply the diagonal 
	$ Delta_(n-1)^*:(n-1)Pr_B times.o_((n-1)Pr_A)(n-1)Pr_B->(n-1)Pr_B $
	which admits a right adjoint. 
]

#rem[
	As in the previous case, if we remove the $aleph_1$-finitely presented condition, we will still get an ambidexterity result, but in the category $Pr^L$ instead of $Pr_kappa^L$. 
]

We now temporarily set $CAlg=CAlg(Sp)$, and prove a descent result. 

#thm[
	For $n>=1$, the functor $n Pr^(*,*):Aff^op->(n+1)Pr$ is a sheaf in the flat topology. 
]
#proof[
	By construction, we have $n Pr^(*,*)$ sends coproducts to products. Hence, it suffices to prove that for a flat hypercover of $EE_oo$-rings $A->A_bullet$, the map $n Pr_A->lim_Delta^* n Pr_A_bullet$ is an equivalence (on the level of rings, we have slightly unfortunately that the functor $f_n^*$ is covariant). 

	Firstly, we assume that $A->A_bullet$ is an $aleph_1$-finitely presented hypercover (i.e., the maps $f^i:A->A_i$ are $aleph_1$-finitely presented). We prove in this case that the functor 
	$ 0Pr_A->attach(lim_Delta,tr:!) 0Pr_A_bullet=attach(colim_(Delta^op),br:*)0Pr_A_bullet $ 
	is fully faithful and essentially surjective. We note here that the functor $0Pr_A->lim^! 0Pr_A_bullet$ given by $!$-pullback admit a left adjoint given by $(M_n) mapsto colim f_*^n M_n$. 

	For full faithfulness, take $M in 0Pr_A$, we must show that the counit map 
	$ colim_(Delta^op)f^i_*f^(i,!)M->M $
	an equivalence. Notice that by definition, we have $f^(i,!)M=Hom_A (A_i,M)$ regarded as an $A_i$-module. Thus, we have $f^i_*f^(i,!)M=Hom_A (A_i,M)$ the underlying $A$-module. Then, we may compute the colimit as 
	$ colim_(Delta^op)f^i_*f^(i,!)M=colim_(m>=0)colim_(Delta^op_(<=m))Hom_A (A_i,M)=colim_(m>=0)Hom_A (lim_(Delta_(<=m))A_i,M) $
	where the final equivalence is true because $lim_(Delta_(<=m))$ is a finite colimit, hence preserved by the exact functor $Hom_A (-,M)$. Note that 
	$ M=colim_(m>=0)M=colim_(m>=0)Hom_A (A,M) $
	thus it suffices to identify the pro-systems $underline(lim)A$ and $underline(lim)lim_()A_i$. 

	By flatness, we may assume that $A$ and $A_i$'s are connective by replacing by their connective covers. Then, to show that $underline(lim)A$ and $underline(lim)A_i$ are equivalent as pro-objects, we may equivalently prove that the cofiber of $underline(lim)A->underline(lim)A_i$ is zero. This cofiber is given by 
]
#rem[
	We remark here that it is important that we have set $1Pr_A=Mod_(0Pr_A)(Pr^L_aleph_1)$ instead of $Mod_(0Pr_A)(Pr^L)$. 
]